"""Regression tests for auto-wired TotalStack providers (TS-GAP-037).

The auto-wired providers (``totalstack/services/*/provider.py``, generated by
``development/auto_wire_providers.py``) install ``@handler`` wrappers via
``setattr``. localstack-core's ``create_dispatch_table`` resolves each handler
by ``fn.__name__`` and re-looks it up with ``getattr(delegate, fn.__name__)``.

Before the fix every wrapper was named ``_w``, so the lookup raised
``AttributeError`` and EVERY operation 500'd under
``PROVIDER_OVERRIDE_<svc>=totalstack`` — even before any handler ran. The
fix names the wrapper like the attribute it is attached under, derives the
operation name from the handler-file stem without mangling PascalCase, and
picks the real ``handler`` function instead of the injected no-op
``dataclass`` lambda.

These tests build the dispatch table through the same factory the runtime
uses (``MotoFallbackDispatcher``, see ``totalstack/providers.py``) and invoke
operations in-process — no emulator required.
"""
import os

import pytest
from totalstack.services.dynamodbstreams.provider import TotalStackDynamodbstreamsProvider
from totalstack.services.s3tables.provider import TotalStackS3tablesProvider
from totalstack.services.transcribe.provider import TotalStackTranscribeProvider

from localstack.aws.api import CommonServiceException, ServiceException, handler
from localstack.services.moto import MotoFallbackDispatcher

# mirror the emulator environment when the totalstack provider variant is active
for _svc in ("dynamodbstreams", "s3tables", "transcribe"):
    os.environ.setdefault(f"PROVIDER_OVERRIDE_{_svc}", "totalstack")

PROVIDERS = {
    "dynamodbstreams": (
        TotalStackDynamodbstreamsProvider,
        {"DescribeStream", "GetRecords", "GetShardIterator", "ListStreams"},
    ),
    "s3tables": (
        TotalStackS3tablesProvider,
        {
            "CreateNamespace",
            "CreateTable",
            "CreateTableBucket",
            "DeleteNamespace",
            "DeleteTable",
            "DeleteTableBucket",
            "GetNamespace",
            "GetTable",
            "GetTableBucket",
            "GetTableBucketEncryption",
            "GetTableBucketMaintenanceConfiguration",
            "GetTableEncryption",
            "GetTableMaintenanceConfiguration",
            "ListNamespaces",
            "ListTableBuckets",
            "ListTables",
            "ListTagsForResource",
            "RenameTable",
            "TagResource",
            "UntagResource",
        },
    ),
    "transcribe": (
        TotalStackTranscribeProvider,
        {
            "CreateLanguageModel",
            "CreateVocabulary",
            "CreateVocabularyFilter",
            "DeleteLanguageModel",
            "DeleteTranscriptionJob",
            "DeleteVocabulary",
            "DeleteVocabularyFilter",
            "DescribeLanguageModel",
            "GetTranscriptionJob",
            "GetVocabulary",
            "GetVocabularyFilter",
            "ListLanguageModels",
            "ListTranscriptionJobs",
            "ListVocabularies",
            "ListVocabularyFilters",
            "StartTranscriptionJob",
            "UpdateVocabulary",
            "UpdateVocabularyFilter",
        },
    ),
}


class _Ctx:
    """Minimal context stand-in — dispatchers only pass it through."""


@pytest.mark.parametrize("service", sorted(PROVIDERS))
def test_dispatch_table_builds_with_all_handler_ops(service):
    """The dispatch table must build (no AttributeError) and cover every op."""
    provider_cls, expected_ops = PROVIDERS[service]
    table = MotoFallbackDispatcher(provider_cls())  # production path (providers.py)
    assert expected_ops <= set(table.keys())
    for op in expected_ops:
        assert table[op] is not None


def test_s3tables_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackS3tablesProvider())
    ctx = _Ctx()

    create = table["CreateTableBucket"](ctx, {"name": "ts-gap-037-bucket"})
    assert "arn" in create and "ts-gap-037-bucket" in create["arn"]
    arn = create["arn"]

    get = table["GetTableBucket"](ctx, {"tableBucketARN": arn})
    assert get["name"] == "ts-gap-037-bucket"

    listed = table["ListTableBuckets"](ctx, {})
    assert any(b["arn"] == arn for b in listed.get("tableBuckets", []))

    tagged = table["TagResource"](
        ctx, {"resourceArn": arn, "tags": [{"key": "k", "value": "v"}]}
    )
    assert tagged == {}

    with pytest.raises(CommonServiceException) as exc:
        table["GetTableBucket"](ctx, {"tableBucketARN": "arn:aws:s3tables:::bucket/missing"})
    assert exc.value.code == "NotFoundException"


def test_dynamodbstreams_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackDynamodbstreamsProvider())
    ctx = _Ctx()

    assert table["ListStreams"](ctx, {}) == {"Streams": []}

    with pytest.raises(CommonServiceException) as exc:
        table["DescribeStream"](
            ctx,
            {
                "StreamArn": (
                    "arn:aws:dynamodb:us-east-1:000000000000:table/t/"
                    "stream/2024-01-01T00:00:00.000"
                )
            },
        )
    assert exc.value.code == "ResourceNotFoundException"


def test_transcribe_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackTranscribeProvider())
    ctx = _Ctx()

    create = table["CreateVocabulary"](
        ctx, {"VocabularyName": "ts-gap-037-vocab", "LanguageCode": "en-US"}
    )
    assert create["VocabularyName"] == "ts-gap-037-vocab"

    listed = table["ListVocabularies"](ctx, {})
    assert any(
        v["VocabularyName"] == "ts-gap-037-vocab" for v in listed.get("Vocabularies", [])
    )

    with pytest.raises(CommonServiceException) as exc:
        table["CreateVocabulary"](
            ctx, {"VocabularyName": "ts-gap-037-vocab", "LanguageCode": "en-US"}
        )
    assert exc.value.code == "ConflictException"


class _TypedValidationError(ServiceException):
    code = "ValidationException"


class _ProbeProvider:
    """Provider whose handler raises an already-typed ServiceException."""

    @handler("ListStreams", expand=False)
    def list_streams(self, context, request):
        raise _TypedValidationError("bad input")


def test_typed_service_exceptions_pass_through_unchanged():
    """Already-typed service errors must not be rewrapped (keeps 400s intact)."""
    table = MotoFallbackDispatcher(_ProbeProvider())
    with pytest.raises(_TypedValidationError):
        table["ListStreams"](_Ctx(), {})
