"""Regression tests for auto-wired TotalStack providers (TS-GAP-037/038).

The auto-wired providers (``totalstack/services/*/provider.py``, generated by
``development/auto_wire_providers.py``) install ``@handler`` wrappers via
``setattr``. localstack-core's ``create_dispatch_table`` resolves each handler
by ``fn.__name__`` and re-looks it up with ``getattr(delegate, fn.__name__)``.

Before the fix every wrapper was named ``_w``, so the lookup raised
``AttributeError`` and EVERY operation 500'd under
``PROVIDER_OVERRIDE_<svc>=totalstack`` — even before any handler ran. The
fix names the wrapper like the attribute it is attached under, derives the
operation name from the handler-file stem without mangling PascalCase, and
picks the real ``handler`` function instead of the injected no-op
``dataclass`` lambda.

TS-GAP-038 (the five stale providers cloudfront/cloudtrail/cognito-identity/
ecr/transfer) has no assembled specs left, so auto-wire regeneration cannot
touch them; they were hand-patched with the same fixed ``_attach_handler``.
Their spec dirs are empty, so no handlers attach yet — the dispatch table
builds empty and the provider stays importable/selectable under
``PROVIDER_OVERRIDE_<svc>=totalstack``. The wrapper-naming and
exception-mapping regression is covered per service by
``test_stale_provider_attach_handler_names_wrapper_and_maps_errors``.

These tests build the dispatch table through the same factory the runtime
uses (``MotoFallbackDispatcher``, see ``totalstack/providers.py``) and invoke
operations in-process — no emulator required.
"""
import os
from importlib import import_module

import pytest
from totalstack.services.cloudfront.provider import TotalStackCloudfrontProvider
from totalstack.services.cloudtrail.provider import TotalStackCloudtrailProvider
from totalstack.services.dynamodbstreams.provider import TotalStackDynamodbstreamsProvider
from totalstack.services.ecr.provider import TotalStackEcrProvider
from totalstack.services.s3tables.provider import TotalStackS3tablesProvider
from totalstack.services.transcribe.provider import TotalStackTranscribeProvider
from totalstack.services.transfer.provider import TotalStackTransferProvider

# "cognito-identity" contains a hyphen — not a valid import identifier
TotalStackCognitoIdentityProvider = import_module(
    "totalstack.services.cognito-identity.provider"
).TotalStackCognitoIdentityProvider

from localstack.aws.api import CommonServiceException, ServiceException, handler
from localstack.services.moto import MotoFallbackDispatcher

# mirror the emulator environment when the totalstack provider variant is active
for _svc in (
    "dynamodbstreams",
    "s3tables",
    "transcribe",
    "cloudfront",
    "cloudtrail",
    "cognito-identity",
    "ecr",
    "transfer",
):
    os.environ.setdefault(f"PROVIDER_OVERRIDE_{_svc}", "totalstack")

PROVIDERS = {
    "dynamodbstreams": (
        TotalStackDynamodbstreamsProvider,
        {"DescribeStream", "GetRecords", "GetShardIterator", "ListStreams"},
    ),
    "s3tables": (
        TotalStackS3tablesProvider,
        {
            "CreateNamespace",
            "CreateTable",
            "CreateTableBucket",
            "DeleteNamespace",
            "DeleteTable",
            "DeleteTableBucket",
            "GetNamespace",
            "GetTable",
            "GetTableBucket",
            "GetTableBucketEncryption",
            "GetTableBucketMaintenanceConfiguration",
            "GetTableEncryption",
            "GetTableMaintenanceConfiguration",
            "ListNamespaces",
            "ListTableBuckets",
            "ListTables",
            "ListTagsForResource",
            "RenameTable",
            "TagResource",
            "UntagResource",
        },
    ),
    "transcribe": (
        TotalStackTranscribeProvider,
        {
            "CreateLanguageModel",
            "CreateVocabulary",
            "CreateVocabularyFilter",
            "DeleteLanguageModel",
            "DeleteTranscriptionJob",
            "DeleteVocabulary",
            "DeleteVocabularyFilter",
            "DescribeLanguageModel",
            "GetTranscriptionJob",
            "GetVocabulary",
            "GetVocabularyFilter",
            "ListLanguageModels",
            "ListTranscriptionJobs",
            "ListVocabularies",
            "ListVocabularyFilters",
            "StartTranscriptionJob",
            "UpdateVocabulary",
            "UpdateVocabularyFilter",
        },
    ),
    # TS-GAP-038: no assembled specs left for these five (their
    # specs/aws/.speclang/assembled/<svc> dirs are empty), so the setattr loop
    # attaches zero handlers — the dispatch table builds empty. The entries
    # keep the providers inside the import/instantiation/table-build sweep
    # (module import + class resolution + create_dispatch_table must not
    # AttributeError), and the helper regression itself is asserted per
    # service by test_stale_provider_attach_handler_names_wrapper_and_maps_errors.
    "cloudfront": (TotalStackCloudfrontProvider, set()),
    "cloudtrail": (TotalStackCloudtrailProvider, set()),
    "cognito-identity": (TotalStackCognitoIdentityProvider, set()),
    "ecr": (TotalStackEcrProvider, set()),
    "transfer": (TotalStackTransferProvider, set()),
}


class _Ctx:
    """Minimal context stand-in — dispatchers only pass it through."""


@pytest.mark.parametrize("service", sorted(PROVIDERS))
def test_dispatch_table_builds_with_all_handler_ops(service):
    """The dispatch table must build (no AttributeError) and cover every op."""
    provider_cls, expected_ops = PROVIDERS[service]
    table = MotoFallbackDispatcher(provider_cls())  # production path (providers.py)
    assert expected_ops <= set(table.keys())
    for op in expected_ops:
        assert table[op] is not None


@pytest.mark.parametrize(
    "provider_module",
    [
        "totalstack.services.cloudfront.provider",
        "totalstack.services.cloudtrail.provider",
        "totalstack.services.cognito-identity.provider",
        "totalstack.services.ecr.provider",
        "totalstack.services.transfer.provider",
    ],
)
def test_stale_provider_attach_handler_names_wrapper_and_maps_errors(provider_module):
    """TS-GAP-038: the five stale providers' _attach_handler must (1) name the
    attached wrapper like the attribute it is attached under (create_dispatch_table
    resolves handlers via fn.__name__ → getattr(delegate, fn.__name__), so a _w
    wrapper 500s every op with AttributeError) and (2) map untyped exceptions to
    a typed CommonServiceException (code from the exception's .code/class name).
    """
    attach_handler = import_module(provider_module)._attach_handler

    def _handler(store, request):
        raise ValueError("boom")

    class _Probe:
        def __init__(self):
            self.store = None

        probe_op = attach_handler("ProbeOp", "probe_op", _handler)

    # the wrapper is attached under its attribute name, not as `_w`
    assert _Probe.probe_op.__name__ == "probe_op"

    table = MotoFallbackDispatcher(_Probe())
    assert "ProbeOp" in table

    with pytest.raises(CommonServiceException) as exc:
        table["ProbeOp"](_Ctx(), {})
    assert exc.value.code == "ValueError"
    assert "boom" in str(exc.value)


def test_s3tables_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackS3tablesProvider())
    ctx = _Ctx()

    create = table["CreateTableBucket"](ctx, {"name": "ts-gap-037-bucket"})
    assert "arn" in create and "ts-gap-037-bucket" in create["arn"]
    arn = create["arn"]

    get = table["GetTableBucket"](ctx, {"tableBucketARN": arn})
    assert get["name"] == "ts-gap-037-bucket"

    listed = table["ListTableBuckets"](ctx, {})
    assert any(b["arn"] == arn for b in listed.get("tableBuckets", []))

    tagged = table["TagResource"](
        ctx, {"resourceArn": arn, "tags": [{"key": "k", "value": "v"}]}
    )
    assert tagged == {}

    with pytest.raises(CommonServiceException) as exc:
        table["GetTableBucket"](ctx, {"tableBucketARN": "arn:aws:s3tables:::bucket/missing"})
    assert exc.value.code == "NotFoundException"


def test_dynamodbstreams_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackDynamodbstreamsProvider())
    ctx = _Ctx()

    assert table["ListStreams"](ctx, {}) == {"Streams": []}

    with pytest.raises(CommonServiceException) as exc:
        table["DescribeStream"](
            ctx,
            {
                "StreamArn": (
                    "arn:aws:dynamodb:us-east-1:000000000000:table/t/"
                    "stream/2024-01-01T00:00:00.000"
                )
            },
        )
    assert exc.value.code == "ResourceNotFoundException"


def test_transcribe_ops_return_proper_responses():
    table = MotoFallbackDispatcher(TotalStackTranscribeProvider())
    ctx = _Ctx()

    create = table["CreateVocabulary"](
        ctx, {"VocabularyName": "ts-gap-037-vocab", "LanguageCode": "en-US"}
    )
    assert create["VocabularyName"] == "ts-gap-037-vocab"

    listed = table["ListVocabularies"](ctx, {})
    assert any(
        v["VocabularyName"] == "ts-gap-037-vocab" for v in listed.get("Vocabularies", [])
    )

    with pytest.raises(CommonServiceException) as exc:
        table["CreateVocabulary"](
            ctx, {"VocabularyName": "ts-gap-037-vocab", "LanguageCode": "en-US"}
        )
    assert exc.value.code == "ConflictException"


class _TypedValidationError(ServiceException):
    code = "ValidationException"


class _ProbeProvider:
    """Provider whose handler raises an already-typed ServiceException."""

    @handler("ListStreams", expand=False)
    def list_streams(self, context, request):
        raise _TypedValidationError("bad input")


def test_typed_service_exceptions_pass_through_unchanged():
    """Already-typed service errors must not be rewrapped (keeps 400s intact)."""
    table = MotoFallbackDispatcher(_ProbeProvider())
    with pytest.raises(_TypedValidationError):
        table["ListStreams"](_Ctx(), {})
