# Test inputs for acm
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'RequestCertificate': {'DomainName': 'shape-test.example.com'},
            'DescribeCertificate': lambda store: {'CertificateArn': store.request_certificate(DomainName='test.com')['CertificateArn']},  # noqa: E501
            'ListCertificates': {},
            'DeleteCertificate': lambda store: {'CertificateArn': store.request_certificate(DomainName='del-test.com')['CertificateArn']},  # noqa: E501
            'GetCertificate': lambda store: {'CertificateArn': store.import_certificate(Certificate="test", PrivateKey="test")['CertificateArn']},  # noqa: E501
            'ImportCertificate': {'Certificate': 'test-cert', 'PrivateKey': 'test-key'},  # noqa: E501
            'GetAccountConfiguration': {},
            'PutAccountConfiguration': {'ExpiryEvents': {'DaysBeforeExpiry': 30}},  # noqa: E501
            'AddTagsToCertificate': lambda store: {'CertificateArn': store.request_certificate(DomainName='tag-test.com')['CertificateArn'], 'Tags': [{'Key': 'test', 'Value': 'val'}]},  # noqa: E501
            'ListTagsForCertificate': lambda store: {'CertificateArn': store.request_certificate(DomainName='lt-test.com')['CertificateArn']},  # noqa: E501
            'RemoveTagsFromCertificate': lambda store: {'CertificateArn': store.request_certificate(DomainName='rt-test.com')['CertificateArn'], 'Tags': [{'Key': 'test', 'Value': 'val'}]},  # noqa: E501
            'RenewCertificate': lambda store: {'CertificateArn': store.import_certificate(Certificate="test", PrivateKey="test")['CertificateArn']},  # noqa: E501
            'RevokeCertificate': lambda store: {'CertificateArn': store.import_certificate(Certificate="test", PrivateKey="test")['CertificateArn'], 'RevocationReason': 'UNSPECIFIED'},  # noqa: E501
            'UpdateCertificateOptions': lambda store: {'CertificateArn': store.import_certificate(Certificate="test", PrivateKey="test")['CertificateArn'], 'Options': {'CertificateTransparencyLoggingPreference': 'ENABLED'}},  # noqa: E501
            'RequestCertificate': {'DomainName': 'acm-test.example.com'},
            'ImportCertificate': {'Certificate': 'base64-cert-data', 'PrivateKey': 'base64-key-data'},  # noqa: E501
            'DescribeCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn']})[1],  # noqa: E501
            'GetCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn']})[1],  # noqa: E501
            'ListCertificates': {},
            'DeleteCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn']})[1],  # noqa: E501
            'UpdateCertificateOptions': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn'], 'Options': {'CertificateTransparencyLoggingPreference': 'ENABLED'}})[1],  # noqa: E501
            'ListTagsForCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn']})[1],  # noqa: E501
            'AddTagsToCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn'], 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],  # noqa: E501
            'RemoveTagsFromCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data', Tags=[{'Key': 'env', 'Value': 'test'}]), {'CertificateArn': r['CertificateArn'], 'Tags': [{'Key': 'env', 'Value': 'test'}], 'TagKeys': ['env']})[1],  # noqa: E501
            'RenewCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), [setattr(v, 'Status', 'ISSUED') for v in store._certificates.values()], {'CertificateArn': r['CertificateArn']})[2],  # noqa: E501
            'RevokeCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), {'CertificateArn': r['CertificateArn'], 'RevocationReason': 'UNSPECIFIED'})[1],  # noqa: E501
            'ExportCertificate': lambda store: (r := store.import_certificate(Certificate='base64-cert-data', PrivateKey='base64-key-data'), setattr(store._certificates[r['CertificateArn']], 'Type', 'PRIVATE'), {'CertificateArn': r['CertificateArn'], 'Passphrase': b'test-pass'})[2],  # noqa: B010
            'ResendValidationEmail': lambda store: (r := store.request_certificate('acm-test.example.com'), {'CertificateArn': r['CertificateArn'], 'Domain': 'test.example.com', 'ValidationDomain': 'test.example.com'})[1],  # noqa: E501
            'GetAccountConfiguration': {},
            'PutAccountConfiguration': {'ExpiryEvents': {'DaysBeforeExpiry': 7}},  # noqa: E501
}
