# Test inputs for amp
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateWorkspace': {'alias': 'amp-shape'},
            'DescribeWorkspace': lambda store: (
                ws := store.create_workspace(alias='amp-desc'),
                {'workspaceId': ws['workspaceId']}
            )[1],
            'ListWorkspaces': {},
            'DeleteWorkspace': lambda store: (
                ws := store.create_workspace(alias='amp-del'),
                {'workspaceId': ws['workspaceId']}
            )[1],
            'UpdateWorkspaceAlias': lambda store: (
                ws := store.create_workspace(alias='amp-upd-old'),
                {'workspaceId': ws['workspaceId'], 'alias': 'amp-upd-new'}
            )[1],
            'CreateScraper': {'alias': 'amp-scraper', 'source': {'eksConfiguration': {'clusterArn': 'arn:aws:eks:us-east-1:000000000000:cluster/test'}}, 'destination': {'ampConfiguration': {'workspaceArn': 'arn:aws:prometheus:us-east-1:000000000000:workspace/ws-test'}}},  # noqa: E501
            'DescribeScraper': lambda store: (
                sr := store.create_scraper(alias='amp-desc-scr', source={'eksConfiguration': {'clusterArn': 'arn:aws:eks:us-east-1:000000000000:cluster/test'}}, destination={'ampConfiguration': {'workspaceArn': 'arn:aws:prometheus:us-east-1:000000000000:workspace/ws-test'}}),  # noqa: E501
                {'scraperId': sr['scraperId']}
            )[1],
            'ListScrapers': {},
            'DeleteScraper': lambda store: (
                sr := store.create_scraper(alias='amp-del-scr', source={'eksConfiguration': {'clusterArn': 'arn:aws:eks:us-east-1:000000000000:cluster/test'}}, destination={'ampConfiguration': {'workspaceArn': 'arn:aws:prometheus:us-east-1:000000000000:workspace/ws-test'}}),  # noqa: E501
                {'scraperId': sr['scraperId']}
            )[1],
            'UpdateScraper': lambda store: (
                sr := store.create_scraper(alias='amp-upd-scr', source={'eksConfiguration': {'clusterArn': 'arn:aws:eks:us-east-1:000000000000:cluster/test'}}, destination={'ampConfiguration': {'workspaceArn': 'arn:aws:prometheus:us-east-1:000000000000:workspace/ws-test'}}),  # noqa: E501
                {'scraperId': sr['scraperId'], 'alias': 'amp-updated-scraper'}
            )[1],
            'GetDefaultScraperConfiguration': {},
            'CreateRuleGroupsNamespace': lambda store: (
                ws := store.create_workspace(alias='amp-rgn'),
                {'workspaceId': ws['workspaceId'], 'name': 'default', 'data': 'groups:\n  - name: test'}  # noqa: E501
            )[1],
            'DescribeRuleGroupsNamespace': lambda store: (
                ws := store.create_workspace(alias='amp-drgn'),
                store.create_rule_groups_namespace(workspaceId=ws['workspaceId'], name='default', data='groups: []'),  # noqa: E501
                {'workspaceId': ws['workspaceId'], 'name': 'default'}
            )[2],
            'ListRuleGroupsNamespaces': lambda store: (
                ws := store.create_workspace(alias='amp-lrgn'),
                {'workspaceId': ws['workspaceId']}
            )[1],
            'DeleteRuleGroupsNamespace': lambda store: (
                ws := store.create_workspace(alias='amp-delrgn'),
                store.create_rule_groups_namespace(workspaceId=ws['workspaceId'], name='default', data='groups: []'),  # noqa: E501
                {'workspaceId': ws['workspaceId'], 'name': 'default'}
            )[2],
            'PutRuleGroupsNamespace': lambda store: (
                ws := store.create_workspace(alias='ampprgn'),
                {'workspaceId': ws['workspaceId'], 'name': 'default', 'data': 'groups:\n  - name: test'}  # noqa: E501
            )[1],
            'CreateAlertManagerDefinition': lambda store: (
                ws := store.create_workspace(alias='amp-amd'),
                {'workspaceId': ws['workspaceId'], 'data': 'alertmanager_config: |\n  global:\n    slack_api_url: https://hooks.slack.com/test'}  # noqa: E501
            )[1],
            'DescribeAlertManagerDefinition': lambda store: (
                ws := store.create_workspace(alias='amp-damd'),
                amd := store.create_alert_manager_definition(workspaceId=ws['workspaceId'], data='alertmanager_config: ""'),  # noqa: E501
                {'workspaceId': ws['workspaceId']}
            )[2],
            'DeleteAlertManagerDefinition': lambda store: (
                ws := store.create_workspace(alias='amp-delamd'),
                amd := store.create_alert_manager_definition(workspaceId=ws['workspaceId'], data='alertmanager_config: ""'),  # noqa: E501
                {'workspaceId': ws['workspaceId']}
            )[2],
            'PutAlertManagerDefinition': lambda store: (
                ws := store.create_workspace(alias='amp-pamd'),
                {'workspaceId': ws['workspaceId'], 'data': 'alertmanager_config: |\n  receivers:\n  - name: default'}  # noqa: E501
            )[1],
            'amp.TagResource': lambda store: (
                ws := store.create_workspace(alias='amp-tag', tags={'env': 'test'}),  # noqa: E501
                {'resourceArn': ws['arn'], 'tags': [{'key': 'env', 'value': 'test'}]}  # noqa: E501
            )[1],
            'amp.UntagResource': lambda store: (
                ws := store.create_workspace(alias='amp-utag', tags={'env': 'test'}),  # noqa: E501
                {'resourceArn': ws['arn'], 'tagKeys': ['env']}
            )[1],
            'amp.ListTagsForResource': lambda store: (
                ws := store.create_workspace(alias='amp-ltag', tags={'env': 'test'}),  # noqa: E501
                {'resourceArn': ws['arn']}
            )[1],
}
