# Test inputs for amplify
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateApp': {'name': 'test-amplify-app'},
            'CreateBranch': lambda store: (
                store.create_app('a-cr-br'),
                {'appId': store.apps().appId if hasattr(store.apps(), 'appId') else list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'branchName': 'test-branch'})[1],
            'CreateBackendEnvironment': lambda store: (
                store.create_app('a-cr-be'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'environmentName': 'test-env'})[1],
            'CreateDomainAssociation': lambda store: (
                store.create_app('a-cr-da'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'domainName': 'example.com',
                 'subDomainSettings': [{'prefix': 'www', 'branchName': 'main'}]})[1],  # noqa: E501
            'CreateWebhook': lambda store: (
                store.create_app('a-cr-wh'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'wh-branch'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'branchName': 'wh-branch'})[2],
            'ListApps': {},
            'ListBranches': lambda store: (
                store.create_app('a-lb'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'ListBackendEnvironments': lambda store: (
                store.create_app('a-lbe'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'ListDomainAssociations': lambda store: (
                store.create_app('a-lda'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'ListWebhooks': lambda store: (
                store.create_app('a-lw'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'GetApp': lambda store: (
                store.create_app('a-get'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'GetBranch': lambda store: (
                store.create_app('a-getbr'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'get-branch'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'branchName': 'get-branch'})[2],
            'GetBackendEnvironment': lambda store: (
                store.create_app('a-getbe'),
                store.create_backend_environment(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'get-be'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'environmentName': 'get-be'})[2],
            'GetDomainAssociation': lambda store: (
                store.create_app('a-getda'),
                store.create_domain_association(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'get.da.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'domainName': 'get.da.com'})[2],
            'GetWebhook': lambda store: (
                store.create_app('a-getwh'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'getwh-br'),  # noqa: E501
                store.create_webhook(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'getwh-br'),  # noqa: E501
                {'webhookId': store.webhooks()[0].webhookId if isinstance(store.webhooks(), list) and store.webhooks() else None})[3],  # noqa: E501
            'DeleteApp': lambda store: (
                store.create_app('a-del'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'DeleteBranch': lambda store: (
                store.create_app('a-delbr'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'del-branch'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'branchName': 'del-branch'})[2],
            'DeleteBackendEnvironment': lambda store: (
                store.create_app('a-delbe'),
                store.create_backend_environment(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'del-be'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'environmentName': 'del-be'})[2],
            'DeleteDomainAssociation': lambda store: (
                store.create_app('a-delda'),
                store.create_domain_association(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'del.da.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'domainName': 'del.da.com'})[2],
            'DeleteWebhook': lambda store: (
                store.create_app('a-delwh'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'delwh-br'),  # noqa: E501
                store.create_webhook(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'delwh-br'),  # noqa: E501
                {'webhookId': store.webhooks()[0].webhookId if isinstance(store.webhooks(), list) and store.webhooks() else None})[3],  # noqa: E501
            'UpdateApp': lambda store: (
                store.create_app('a-upd'),
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'name': 'updated-app'})[1],
            'UpdateBranch': lambda store: (
                store.create_app('a-updbr'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'upd-branch'),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'branchName': 'upd-branch'})[2],
            'UpdateDomainAssociation': lambda store: (
                store.create_app('a-updda'),
                store.create_domain_association(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'upd.da.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'domainName': 'upd.da.com',
                 'subDomainSettings': [{'prefix': 'api', 'branchName': 'main'}]})[2],  # noqa: E501
            'UpdateWebhook': lambda store: (
                store.create_app('a-updwh'),
                store.create_branch(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'updwh-br'),  # noqa: E501
                store.create_webhook(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', 'updwh-br'),  # noqa: E501
                {'webhookId': store.webhooks()[0].webhookId if isinstance(store.webhooks(), list) and store.webhooks() else None})[3],  # noqa: E501
            'amplify.TagResource': lambda store: (
                store.create_app('a-tag'),
                {'resourceArn': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'tags': {'env': 'test'}})[1],
            'amplify.UntagResource': lambda store: (
                store.create_app('a-untag'),
                store.tag_resource(list(store.apps())[0].appId if isinstance(store.apps(), list) else '', {'env': 'test'}),  # noqa: E501
                {'resourceArn': list(store.apps())[0].appId if isinstance(store.apps(), list) else None,  # noqa: E501
                 'tagKeys': ['env']})[2],
            'amplify.ListTagsForResource': lambda store: (
                store.create_app('a-ltfr'),
                {'resourceArn': list(store.apps())[0].appId if isinstance(store.apps(), list) else None})[1],  # noqa: E501
            'CreateApp': {'name': 'test-app'},
            'CreateBranch': lambda store: (
                app := store.create_app('s-cb-app'),
                {'appId': app.appId, 'branchName': 'test-branch'})[1],
            'CreateBackendEnvironment': lambda store: (
                app := store.create_app('s-cbe-app'),
                {'appId': app.appId, 'environmentName': 'test-env'})[1],
            'CreateDomainAssociation': lambda store: (
                app := store.create_app('s-cda-app'),
                {'appId': app.appId, 'domainName': 'test.example.com',
                 'subDomainSettings': [{'prefix': 'www', 'branchName': 'main'}]})[1],  # noqa: E501
            'CreateWebhook': lambda store: (
                app := store.create_app('s-cw-app'),
                {'appId': app.appId, 'branchName': 'main'})[1],
            'ListApps': {},
            'ListBranches': {'appId': 'nonexistent'},
            'ListBackendEnvironments': {'appId': 'nonexistent'},
            'ListDomainAssociations': {'appId': 'nonexistent'},
            'ListWebhooks': {'appId': 'nonexistent'},
            'GetApp': lambda store: (
                app := store.create_app('s-ga-app'),
                {'appId': app.appId})[1],
            'GetBranch': lambda store: (
                app := store.create_app('s-gb-app'),
                store.create_branch(app.appId, 'test-br'),
                {'appId': app.appId, 'branchName': 'test-br'})[2],
            'GetBackendEnvironment': lambda store: (
                app := store.create_app('s-gbe-app'),
                store.create_backend_environment(app.appId, 'test-env'),
                {'appId': app.appId, 'environmentName': 'test-env'})[2],
            'GetDomainAssociation': lambda store: (
                app := store.create_app('s-gda-app'),
                store.create_domain_association(app.appId, 'test.da.example.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': app.appId, 'domainName': 'test.da.example.com'})[2],
            'GetWebhook': lambda store: (
                app := store.create_app('s-gw-app'),
                wh := store.create_webhook(app.appId, 'main'),
                {'webhookId': wh.webhookId})[2],
            'DeleteApp': lambda store: (
                app := store.create_app('s-da-app'),
                {'appId': app.appId})[1],
            'DeleteBranch': lambda store: (
                app := store.create_app('s-db-app'),
                store.create_branch(app.appId, 's-db-br'),
                {'appId': app.appId, 'branchName': 's-db-br'})[2],
            'DeleteBackendEnvironment': lambda store: (
                app := store.create_app('s-dbe-app'),
                store.create_backend_environment(app.appId, 's-dbe-env'),
                {'appId': app.appId, 'environmentName': 's-dbe-env'})[2],
            'DeleteDomainAssociation': lambda store: (
                app := store.create_app('s-dda-app'),
                store.create_domain_association(app.appId, 's-dda.example.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': app.appId, 'domainName': 's-dda.example.com'})[2],
            'DeleteWebhook': lambda store: (
                app := store.create_app('s-dw-app'),
                wh := store.create_webhook(app.appId, 'main'),
                {'webhookId': wh.webhookId})[2],
            'UpdateApp': lambda store: (
                app := store.create_app('s-ua-app'),
                {'appId': app.appId, 'name': 'updated-app'})[1],
            'UpdateBranch': lambda store: (
                app := store.create_app('s-ub-app'),
                store.create_branch(app.appId, 's-ub-br'),
                {'appId': app.appId, 'branchName': 's-ub-br', 'stage': 'DEVELOPMENT'})[2],  # noqa: E501
            'UpdateDomainAssociation': lambda store: (
                app := store.create_app('s-uda-app'),
                store.create_domain_association(app.appId, 's-uda.example.com', [{'prefix': 'www', 'branchName': 'main'}]),  # noqa: E501
                {'appId': app.appId, 'domainName': 's-uda.example.com',
                 'subDomainSettings': [{'prefix': 'www', 'branchName': 'staging'}]})[2],  # noqa: E501
            'UpdateWebhook': lambda store: (
                app := store.create_app('s-uw-app'),
                wh := store.create_webhook(app.appId, 'main'),
                {'webhookId': wh.webhookId, 'branchName': 'develop'})[2],
            'amplify.TagResource': lambda store: (
                app := store.create_app('s-tr-app'),
                {'resourceArn': app.appId,
                 'tags': [{'key': 'env', 'value': 'test'}]})[1],
            'amplify.UntagResource': lambda store: (
                app := store.create_app('s-utr-app'),
                {'resourceArn': app.appId,
                 'tagKeys': ['env']})[1],
            'amplify.ListTagsForResource': lambda store: (
                app := store.create_app('s-ltfr-app'),
                {'resourceArn': app.appId})[1],
}
