# Test inputs for appconfig
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateApplication': {'name': 'test-app', 'description': 'Test AppConfig app'},  # noqa: E501
            'GetApplication': lambda store: (
                a := store.create_application(name='ac-get-app'),
                {'applicationId': a['id']}
            )[1],
            'UpdateApplication': lambda store: (
                a := store.create_application(name='ac-upd-app'),
                {'applicationId': a['id'], 'name': 'ac-upd-renamed'}
            )[1],
            'DeleteApplication': lambda store: (
                a := store.create_application(name='ac-del-app'),
                {'applicationId': a['id']}
            )[1],
            'ListApplications': {},
            'CreateConfigurationProfile': lambda store: (
                a := store.create_application(name='ac-cp-app'),
                {'applicationId': a['id'], 'name': 'test-profile',
                 'locationUri': 'hosted://test'}
            )[1],
            'GetConfigurationProfile': lambda store: (
                a := store.create_application(name='ac-gcp-app'),
                p := store.create_configuration_profile(applicationId=a['id'], name='gcp-prof',  # noqa: E501
                    locationUri='hosted://test'),
                {'applicationId': a['id'], 'configurationProfileId': p['id']}
            )[2],
            'UpdateConfigurationProfile': lambda store: (
                a := store.create_application(name='ac-ucp-app'),
                p := store.create_configuration_profile(applicationId=a['id'], name='ucp-prof',  # noqa: E501
                    locationUri='hosted://test'),
                {'applicationId': a['id'], 'configurationProfileId': p['id'],
                 'name': 'ucp-renamed'}
            )[2],
            'DeleteConfigurationProfile': lambda store: (
                a := store.create_application(name='ac-dcp-app'),
                p := store.create_configuration_profile(applicationId=a['id'], name='dcp-prof',  # noqa: E501
                    locationUri='hosted://test'),
                {'applicationId': a['id'], 'configurationProfileId': p['id']}
            )[2],
            'ListConfigurationProfiles': lambda store: (
                a := store.create_application(name='ac-lcp-app'),
                {'applicationId': a['id']}
            )[1],
            'CreateEnvironment': lambda store: (
                a := store.create_application(name='ac-env-app'),
                {'applicationId': a['id'], 'name': 'test-env'}
            )[1],
            'GetEnvironment': lambda store: (
                a := store.create_application(name='ac-genv-app'),
                e := store.create_environment(applicationId=a['id'], name='genv-env'),  # noqa: E501
                {'applicationId': a['id'], 'environmentId': e['id']}
            )[2],
            'UpdateEnvironment': lambda store: (
                a := store.create_application(name='ac-uenv-app'),
                e := store.create_environment(applicationId=a['id'], name='uenv-env'),  # noqa: E501
                {'applicationId': a['id'], 'environmentId': e['id'],
                 'name': 'uenv-renamed'}
            )[2],
            'DeleteEnvironment': lambda store: (
                a := store.create_application(name='ac-denv-app'),
                e := store.create_environment(applicationId=a['id'], name='denv-env'),  # noqa: E501
                {'applicationId': a['id'], 'environmentId': e['id']}
            )[2],
            'ListEnvironments': lambda store: (
                a := store.create_application(name='ac-lenv-app'),
                {'applicationId': a['id']}
            )[1],
            'appconfig.TagResource': lambda store: (
                a := store.create_application(name='ac-tag-app'),
                {'resourceArn': 'arn:aws:appconfig:us-east-1:000000000000:application/' + a['id'],  # noqa: E501
                 'tags': {'env': 'test'}}
            )[1],
            'appconfig.UntagResource': lambda store: (
                a := store.create_application(name='ac-utag-app'),
                {'resourceArn': 'arn:aws:appconfig:us-east-1:000000000000:application/' + a['id'],  # noqa: E501
                 'tagKeys': ['env']}
            )[1],
            'appconfig.ListTagsForResource': lambda store: (
                a := store.create_application(name='ac-ltag-app'),
                {'resourceArn': 'arn:aws:appconfig:us-east-1:000000000000:application/' + a['id']}  # noqa: E501
            )[1],
}
