# Test inputs for application-autoscaling
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'application-autoscaling.RegisterScalableTarget': {'ResourceId': 'service/ecs-cluster/test-service', 'ScalableDimension': 'ecs:service:DesiredCount', 'ServiceNamespace': 'ecs', 'MinCapacity': 1, 'MaxCapacity': 10},  # noqa: E501
            'application-autoscaling.DescribeScalableTargets': {'ServiceNamespace': 'ecs'},  # noqa: E501
            'application-autoscaling.DeregisterScalableTarget': lambda store: (store.register_target('asg-del-tgt', 'ecs', 'ecs:service:DesiredCount', 1, 10), {'ResourceId': 'asg-del-tgt', 'ScalableDimension': 'ecs:service:DesiredCount', 'ServiceNamespace': 'ecs'})[1],  # noqa: E501
            'application-autoscaling.PutScalingPolicy': {'PolicyName': 'asg-test-policy', 'ResourceId': 'service/ecs-cluster/test-service', 'ScalableDimension': 'ecs:service:DesiredCount', 'ServiceNamespace': 'ecs', 'PolicyType': 'TargetTrackingScaling', 'TargetTrackingScalingPolicyConfiguration': {'TargetValue': 75.0, 'PredefinedMetricSpecification': {'PredefinedMetricType': 'ECSServiceAverageCPUUtilization'}, 'ScaleOutCooldown': 60, 'ScaleInCooldown': 60}},  # noqa: E501
            'application-autoscaling.DescribeScalingPolicies': {'ServiceNamespace': 'ecs'},  # noqa: E501
            'application-autoscaling.DeleteScalingPolicy': lambda store: (store.register_target('asg-delpol-tgt', 'ecs', 'ecs:service:DesiredCount', 1, 10), store.put_policy('asg-del-pol', 'asg-delpol-tgt', 'ecs', 'ecs:service:DesiredCount', 'TargetTrackingScaling', TargetTrackingScalingPolicyConfiguration={'TargetValue': 75.0, 'PredefinedMetricSpecification': {'PredefinedMetricType': 'ECSServiceAverageCPUUtilization'}}), {'PolicyName': 'asg-del-pol', 'ResourceId': 'asg-delpol-tgt', 'ScalableDimension': 'ecs:service:DesiredCount', 'ServiceNamespace': 'ecs'})[2],  # noqa: E501
}
