# Test inputs for appmesh
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateMesh': {'meshName': 'test-mesh', 'spec': {}},
            'CreateVirtualNode': lambda store: (
                store.create_mesh('s-vn-mesh'),
                {'meshName': 's-vn-mesh', 'virtualNodeName': 'test-vn',
                 'spec': {'listeners': []}})[1],
            'CreateVirtualService': lambda store: (
                store.create_mesh('s-vs-mesh'),
                {'meshName': 's-vs-mesh', 'virtualServiceName': 'test-vs',
                 'spec': {}})[1],
            'CreateVirtualRouter': lambda store: (
                store.create_mesh('s-vr-mesh'),
                {'meshName': 's-vr-mesh', 'virtualRouterName': 'test-vr',
                 'spec': {}})[1],
            'CreateRoute': lambda store: (
                store.create_mesh('s-r-mesh'),
                store.create_virtual_router('s-r-mesh', 'test-vr', spec={}),
                {'meshName': 's-r-mesh', 'virtualRouterName': 'test-vr',
                 'routeName': 'test-route', 'spec': {}})[2],
            'ListMeshes': {},
            'ListVirtualNodes': {'meshName': 'test-mesh'},
            'ListVirtualServices': {'meshName': 'test-mesh'},
            'ListVirtualRouters': {'meshName': 'test-mesh'},
            'ListRoutes': {'meshName': 'test-mesh', 'virtualRouterName': 'test-vr'},  # noqa: E501
            'DescribeMesh': lambda store: (
                store.create_mesh('s-desc-mesh'),
                {'meshName': 's-desc-mesh'})[1],
            'DescribeVirtualNode': lambda store: (
                store.create_mesh('s-desc-vn-mesh'),
                store.create_virtual_node('s-desc-vn-mesh', 's-desc-vn', spec={'listeners': []}),  # noqa: E501
                {'meshName': 's-desc-vn-mesh', 'virtualNodeName': 's-desc-vn'})[2],  # noqa: E501
            'DescribeVirtualService': lambda store: (
                store.create_mesh('s-desc-vs-mesh'),
                store.create_virtual_service('s-desc-vs-mesh', 's-desc-vs', spec={}),  # noqa: E501
                {'meshName': 's-desc-vs-mesh', 'virtualServiceName': 's-desc-vs'})[2],  # noqa: E501
            'DescribeVirtualRouter': lambda store: (
                store.create_mesh('s-desc-vr-mesh'),
                store.create_virtual_router('s-desc-vr-mesh', 's-desc-vr', spec={}),  # noqa: E501
                {'meshName': 's-desc-vr-mesh', 'virtualRouterName': 's-desc-vr'})[2],  # noqa: E501
            'DescribeRoute': lambda store: (
                store.create_mesh('s-desc-rt-mesh'),
                store.create_virtual_router('s-desc-rt-mesh', 's-desc-rt-vr', spec={}),  # noqa: E501
                store.create_route('s-desc-rt-mesh', 's-desc-rt-vr', 's-desc-rt', spec={}),  # noqa: E501
                {'meshName': 's-desc-rt-mesh', 'virtualRouterName': 's-desc-rt-vr',  # noqa: E501
                 'routeName': 's-desc-rt'})[3],
            'DeleteMesh': lambda store: (
                store.create_mesh('s-del-mesh'),
                {'meshName': 's-del-mesh'})[1],
            'DeleteVirtualNode': lambda store: (
                store.create_mesh('s-del-vn-mesh'),
                store.create_virtual_node('s-del-vn-mesh', 's-del-vn', spec={'listeners': []}),  # noqa: E501
                {'meshName': 's-del-vn-mesh', 'virtualNodeName': 's-del-vn'})[2],  # noqa: E501
            'DeleteVirtualService': lambda store: (
                store.create_mesh('s-del-vs-mesh'),
                store.create_virtual_service('s-del-vs-mesh', 's-del-vs', spec={}),  # noqa: E501
                {'meshName': 's-del-vs-mesh', 'virtualServiceName': 's-del-vs'})[2],  # noqa: E501
            'DeleteVirtualRouter': lambda store: (
                store.create_mesh('s-del-vr-mesh'),
                store.create_virtual_router('s-del-vr-mesh', 's-del-vr', spec={}),  # noqa: E501
                {'meshName': 's-del-vr-mesh', 'virtualRouterName': 's-del-vr'})[2],  # noqa: E501
            'DeleteRoute': lambda store: (
                store.create_mesh('s-del-rt-mesh'),
                store.create_virtual_router('s-del-rt-mesh', 's-del-rt-vr', spec={}),  # noqa: E501
                store.create_route('s-del-rt-mesh', 's-del-rt-vr', 's-del-rt', spec={}),  # noqa: E501
                {'meshName': 's-del-rt-mesh', 'virtualRouterName': 's-del-rt-vr',  # noqa: E501
                 'routeName': 's-del-rt'})[3],
            'UpdateMesh': lambda store: (
                store.create_mesh('s-upd-mesh'),
                {'meshName': 's-upd-mesh', 'spec': {}})[1],
            'UpdateVirtualNode': lambda store: (
                store.create_mesh('s-upd-vn-mesh'),
                store.create_virtual_node('s-upd-vn-mesh', 's-upd-vn', spec={'listeners': []}),  # noqa: E501
                {'meshName': 's-upd-vn-mesh', 'virtualNodeName': 's-upd-vn',
                 'spec': {'listeners': []}})[2],
            'UpdateVirtualService': lambda store: (
                store.create_mesh('s-upd-vs-mesh'),
                store.create_virtual_service('s-upd-vs-mesh', 's-upd-vs', spec={}),  # noqa: E501
                {'meshName': 's-upd-vs-mesh', 'virtualServiceName': 's-upd-vs',
                 'spec': {}})[2],
            'UpdateVirtualRouter': lambda store: (
                store.create_mesh('s-upd-vr-mesh'),
                store.create_virtual_router('s-upd-vr-mesh', 's-upd-vr', spec={}),  # noqa: E501
                {'meshName': 's-upd-vr-mesh', 'virtualRouterName': 's-upd-vr',
                 'spec': {}})[2],
            'UpdateRoute': lambda store: (
                store.create_mesh('s-upd-rt-mesh'),
                store.create_virtual_router('s-upd-rt-mesh', 's-upd-rt-vr', spec={}),  # noqa: E501
                store.create_route('s-upd-rt-mesh', 's-upd-rt-vr', 's-upd-rt', spec={}),  # noqa: E501
                {'meshName': 's-upd-rt-mesh', 'virtualRouterName': 's-upd-rt-vr',  # noqa: E501
                 'routeName': 's-upd-rt', 'spec': {}})[3],
            'appmesh.TagResource': lambda store: (
                store.create_mesh('s-tag-mesh'),
                {'resourceArn': store.meshes('s-tag-mesh').arn,
                 'tags': [{'key': 'env', 'value': 'test'}]})[1],
            'appmesh.UntagResource': lambda store: (
                store.create_mesh('s-untag-mesh'),
                store.tag_resource(store.meshes('s-untag-mesh').arn, [{'key': 'env', 'value': 'test'}]),  # noqa: E501
                {'resourceArn': store.meshes('s-untag-mesh').arn,
                 'tagKeys': ['env']})[2],
            'appmesh.ListTagsForResource': lambda store: (
                store.create_mesh('s-ltfr-mesh'),
                {'resourceArn': store.meshes('s-ltfr-mesh').arn})[1],
}
