# Test inputs for appsync
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateGraphqlApi': {'name': 'as-test-api', 'authenticationType': 'API_KEY'},  # noqa: E501
            'ListGraphqlApis': {},
            'ListApiKeys': {'apiId': 'as-test-api'},
            'ListDataSources': {'apiId': 'as-test-api'},
            'ListResolvers': {'apiId': 'as-test-api', 'typeName': 'Query'},
            'CreateApiKey': lambda store: (
                api := store.create_graphql_api('as-cak-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId']})[1],
            'CreateDataSource': lambda store: (
                api := store.create_graphql_api('as-cds-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId'], 'name': 'as-cds-ds', 'type': 'AWS_LAMBDA'})[1],  # noqa: E501
            'CreateResolver': lambda store: (
                api := store.create_graphql_api('as-crsv-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId'], 'typeName': 'Query', 'fieldName': 'getItem'})[1],  # noqa: E501
            'GetGraphqlApi': lambda store: (
                api := store.create_graphql_api('as-get-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId']})[1],
            'GetDataSource': lambda store: (
                api := store.create_graphql_api('as-gds-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                ds := store.create_data_source(api['apiId'], 'as-gds-ds', 'AWS_LAMBDA')['dataSource'],  # noqa: E501
                {'apiId': api['apiId'], 'name': ds['name']})[2],
            'GetResolver': lambda store: (
                api := store.create_graphql_api('as-grsv-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                rsv := store.create_resolver(api['apiId'], 'Query', 'getItem')['resolver'],  # noqa: E501
                {'apiId': api['apiId'], 'typeName': rsv['typeName'], 'fieldName': rsv['fieldName']})[2],  # noqa: E501
            'DeleteGraphqlApi': lambda store: (
                api := store.create_graphql_api('as-del-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId']})[1],
            'DeleteDataSource': lambda store: (
                api := store.create_graphql_api('as-dds-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                ds := store.create_data_source(api['apiId'], 'as-dds-ds', 'AWS_LAMBDA')['dataSource'],  # noqa: E501
                {'apiId': api['apiId'], 'name': ds['name']})[2],
            'DeleteResolver': lambda store: (
                api := store.create_graphql_api('as-drsv-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                rsv := store.create_resolver(api['apiId'], 'Query', 'getItem')['resolver'],  # noqa: E501
                {'apiId': api['apiId'], 'typeName': rsv['typeName'], 'fieldName': rsv['fieldName']})[2],  # noqa: E501
            'DeleteApiKey': lambda store: (
                api := store.create_graphql_api('as-dak-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                key := store.create_api_key(api['apiId'])['apiKey'],
                {'apiId': api['apiId'], 'id': key['id']})[2],
            'UpdateGraphqlApi': lambda store: (
                api := store.create_graphql_api('as-upd-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'apiId': api['apiId'], 'name': 'as-updated-api', 'authenticationType': 'AWS_IAM'})[1],  # noqa: E501
            'UpdateDataSource': lambda store: (
                api := store.create_graphql_api('as-uds-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                ds := store.create_data_source(api['apiId'], 'as-uds-ds', 'AWS_LAMBDA')['dataSource'],  # noqa: E501
                {'apiId': api['apiId'], 'name': ds['name'], 'type': 'AMAZON_DYNAMODB'})[2],  # noqa: E501
            'UpdateResolver': lambda store: (
                api := store.create_graphql_api('as-ursv-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                rsv := store.create_resolver(api['apiId'], 'Query', 'getItem')['resolver'],  # noqa: E501
                {'apiId': api['apiId'], 'typeName': rsv['typeName'], 'fieldName': rsv['fieldName']})[2],  # noqa: E501
            'UpdateApiKey': lambda store: (
                api := store.create_graphql_api('as-uak-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                key := store.create_api_key(api['apiId'])['apiKey'],
                {'apiId': api['apiId'], 'id': key['id']})[2],
            'appsync.TagResource': lambda store: (
                api := store.create_graphql_api('as-tag-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                {'resourceArn': api['arn'], 'tags': [{'key': 'env', 'value': 'test'}]})[1],  # noqa: E501
            'appsync.UntagResource': lambda store: (
                api := store.create_graphql_api('as-untag-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                store.tag_resource(api['arn'], [{'key': 'env', 'value': 'test'}]),  # noqa: E501
                {'resourceArn': api['arn'], 'tagKeys': ['env']})[2],
            'appsync.ListTagsForResource': lambda store: (
                api := store.create_graphql_api('as-ltr-api', 'API_KEY')['graphqlApi'],  # noqa: E501
                store.tag_resource(api['arn'], [{'key': 'env', 'value': 'test'}]),  # noqa: E501
                {'resourceArn': api['arn']})[2],
}
