# Test inputs for athena
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'StartQueryExecution': {'QueryString': 'SELECT 1'},
            'CreateWorkGroup': {'Name': 'test-workgroup'},
            'CreateDataCatalog': {'Name': 'test-catalog', 'Type': 'GLUE'},
            'CreateNamedQuery': {'Name': 'test-named-query', 'Database': 'test-db', 'QueryString': 'SELECT 1'},  # noqa: E501
            'CreatePreparedStatement': {'StatementName': 'test-stmt', 'WorkGroup': 'test-workgroup', 'QueryStatement': 'SELECT 2'},  # noqa: E501
            'ListWorkGroups': {},
            'ListDataCatalogs': {},
            'ListDatabases': {'CatalogName': 'AwsDataCatalog'},
            'ListNamedQueries': {},
            'ListPreparedStatements': {'WorkGroup': 'test-workgroup'},
            'ListQueryExecutions': {},
            'ListTableMetadata': {'CatalogName': 'AwsDataCatalog', 'DatabaseName': 'test-db'},
            'ListTagsForResource': {'ResourceARN': 'arn:aws:athena:us-east-1:000000000000:workgroup/test-workgroup'},  # noqa: E501
            # Fix: pass the name string, not the create result dict
            'GetWorkGroup': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                {'WorkGroup': 'test-workgroup'})[1],
            'GetQueryExecution': lambda store: {'QueryExecutionId': store.start_query_execution(QueryString='SELECT 1')['QueryExecutionId']},  # noqa: E501
            'GetNamedQuery': lambda store: {'NamedQueryId': store.create_named_query(Name='test-nq', Database='test-db', QueryString='SELECT 1')['NamedQueryId']},  # noqa: E501
            'GetPreparedStatement': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                store.create_prepared_statement(StatementName='test-stmt', WorkGroup='test-workgroup', QueryStatement='SELECT 2'),  # noqa: E501
                {'StatementName': 'test-stmt', 'WorkGroup': 'test-workgroup'})[2],
            'GetDataCatalog': lambda store: (
                store.create_data_catalog(Name='test-catalog', Type='GLUE'),
                {'Name': 'test-catalog'})[1],
            # Fix: create database in store before querying
            'GetDatabase': lambda store: (
                store.databases.update({('AwsDataCatalog', 'test-db'): {'Name': 'test-db'}}),
                {'CatalogName': 'AwsDataCatalog', 'DatabaseName': 'test-db'})[1],
            'GetQueryResults': lambda store: {'QueryExecutionId': store.start_query_execution(QueryString='SELECT 1')['QueryExecutionId']},  # noqa: E501
            'GetTableMetadata': lambda store: (
                store.table_metadata.update({('AwsDataCatalog', 'test-db', 'test-table'): {'Name': 'test-table', 'TableType': 'EXTERNAL_TABLE', 'Columns': [], 'PartitionKeys': [], 'Parameters': {}}}),  # noqa: E501
                {'CatalogName': 'AwsDataCatalog', 'DatabaseName': 'test-db', 'TableName': 'test-table'})[1],  # noqa: E501
            # Fix: pass name string, not create result dict
            'DeleteWorkGroup': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                {'WorkGroup': 'test-workgroup'})[1],
            'DeleteDataCatalog': lambda store: (
                store.create_data_catalog(Name='test-catalog', Type='GLUE'),
                {'Name': 'test-catalog'})[1],
            'DeleteNamedQuery': lambda store: {'NamedQueryId': store.create_named_query(Name='test-nq', Database='test-db', QueryString='SELECT 1')['NamedQueryId']},  # noqa: E501
            'DeletePreparedStatement': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                store.create_prepared_statement(StatementName='test-stmt', WorkGroup='test-workgroup', QueryStatement='SELECT 2'),  # noqa: E501
                {'StatementName': 'test-stmt', 'WorkGroup': 'test-workgroup'})[2],
            'UpdateWorkGroup': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                {'WorkGroup': 'test-workgroup', 'Description': 'updated'})[1],
            'UpdateDataCatalog': lambda store: (
                store.create_data_catalog(Name='test-catalog', Type='GLUE'),
                {'Name': 'test-catalog', 'Type': 'GLUE'})[1],
            'UpdateNamedQuery': lambda store: {'NamedQueryId': store.create_named_query(Name='test-nq', Database='test-db', QueryString='SELECT 1')['NamedQueryId'], 'Name': 'updated-query'},  # noqa: E501
            'UpdatePreparedStatement': lambda store: (
                store.create_work_group(Name='test-workgroup'),
                store.create_prepared_statement(StatementName='test-stmt', WorkGroup='test-workgroup', QueryStatement='SELECT 2'),  # noqa: E501
                {'StatementName': 'test-stmt', 'WorkGroup': 'test-workgroup', 'QueryStatement': 'SELECT 99'})[2],  # noqa: E501
            'StopQueryExecution': lambda store: {'QueryExecutionId': store.start_query_execution(QueryString='SELECT 1')['QueryExecutionId']},  # noqa: E501
            'TagResource': {'ResourceARN': 'arn:aws:athena:us-east-1:000000000000:workgroup/test-workgroup', 'Tags': [{'Key': 'env', 'Value': 'test'}]},  # noqa: E501
            'UntagResource': {'ResourceARN': 'arn:aws:athena:us-east-1:000000000000:workgroup/test-workgroup', 'TagKeys': ['env']},  # noqa: E501
            'BatchGetNamedQuery': {'NamedQueryIds': []},
            'BatchGetQueryExecution': {'QueryExecutionIds': []},
            'wafv2.TagResource': lambda store: (
                store.create_web_acl(name='s-tag-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],  # noqa: E501
                 'Tags': [{'Key': 'test', 'Value': 'val'}]})[1],
            'wafv2.UntagResource': lambda store: (
                store.create_web_acl(name='s-untag-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],  # noqa: E501
                 'TagKeys': ['test']})[1],
            'wafv2.ListTagsForResource': lambda store: (
                store.create_web_acl(name='s-ltf-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN']})[1],  # noqa: E501
}
