# Test inputs for autoscaling
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'autoscaling.CreateAutoScalingGroup': {'AutoScalingGroupName': 'asg-test', 'MinSize': 1, 'MaxSize': 3, 'AvailabilityZones': ['us-east-1a']},  # noqa: E501
            'autoscaling.CreateLaunchConfiguration': {'LaunchConfigurationName': 'asg-lc-test', 'ImageId': 'ami-12345', 'InstanceType': 't2.micro'},  # noqa: E501
            'autoscaling.DescribeAutoScalingGroups': {},
            'autoscaling.DescribeLaunchConfigurations': {},
            'autoscaling.DescribeScalingActivities': {},
            'autoscaling.UpdateAutoScalingGroup': lambda store: (
                store.create_group('asg-upd', 1, 3),
                {'AutoScalingGroupName': 'asg-upd', 'MinSize': 2}
            )[1],
            'autoscaling.SetDesiredCapacity': lambda store: (
                store.create_group('asg-sdc', 1, 3),
                {'AutoScalingGroupName': 'asg-sdc', 'DesiredCapacity': 2}
            )[1],
            'autoscaling.DeleteAutoScalingGroup': lambda store: (
                store.create_group('asg-del', 1, 1),
                {'AutoScalingGroupName': 'asg-del'}
            )[1],
            'autoscaling.DeleteLaunchConfiguration': lambda store: (
                store.create_launch_config('asg-del-lc', 'ami-12345', 't2.micro'),  # noqa: E501
                {'LaunchConfigurationName': 'asg-del-lc'}
            )[1],
}
