# Test inputs for backup
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateBackupPlan': {'BackupPlanName': 'test-plan'},
            'GetBackupPlan': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-get'),
                {'BackupPlanId': plan['BackupPlanId']}
            )[1],
            'ListBackupPlans': {},
            'DeleteBackupPlan': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-del'),
                {'BackupPlanId': plan['BackupPlanId']}
            )[1],
            'UpdateBackupPlan': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-upd'),
                {'BackupPlanId': plan['BackupPlanId']}
            )[1],
            'CreateBackupVault': {'BackupVaultName': 'test-vault'},
            'DescribeBackupVault': lambda store: (
                vault := store.create_backup_vault(BackupVaultName='vault-desc'),  # noqa: E501
                {'BackupVaultName': vault['BackupVaultName']}
            )[1],
            'ListBackupVaults': {},
            'DeleteBackupVault': lambda store: (
                vault := store.create_backup_vault(BackupVaultName='vault-del'),  # noqa: E501
                {'BackupVaultName': vault['BackupVaultName']}
            )[1],
            'CreateBackupSelection': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-sel'),
                {'BackupPlanId': plan['BackupPlanId'], 'SelectionName': 'test-sel',  # noqa: E501
                 'IamRoleArn': 'arn:aws:iam::000000000000:role/test'}
            )[1],
            'GetBackupSelection': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-gsel'),
                sel := store.create_backup_selection(BackupPlanId=plan['BackupPlanId'],  # noqa: E501
                    SelectionName='sel-get', IamRoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'BackupPlanId': plan['BackupPlanId'], 'SelectionId': sel['SelectionId']}  # noqa: E501
            )[2],
            'ListBackupSelections': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-lsel'),
                {'BackupPlanId': plan['BackupPlanId']}
            )[1],
            'DeleteBackupSelection': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-dsel'),
                sel := store.create_backup_selection(BackupPlanId=plan['BackupPlanId'],  # noqa: E501
                    SelectionName='sel-del', IamRoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'BackupPlanId': plan['BackupPlanId'], 'SelectionId': sel['SelectionId']}  # noqa: E501
            )[2],
            'StartBackupJob': lambda store: (
                vault := store.create_backup_vault(BackupVaultName='vault-job'),  # noqa: E501
                {'BackupVaultName': vault['BackupVaultName'],
                 'ResourceArn': 'arn:aws:ec2:us-east-1:000000000000:instance/i-test',  # noqa: E501
                 'IamRoleArn': 'arn:aws:iam::000000000000:role/test'}
            )[1],
            'DescribeBackupJob': lambda store: (
                vault := store.create_backup_vault(BackupVaultName='vault-djob'),  # noqa: E501
                job := store.start_backup_job(BackupVaultName=vault['BackupVaultName'],  # noqa: E501
                    ResourceArn='arn:aws:ec2:us-east-1:000000000000:instance/i-test',  # noqa: E501
                    IamRoleArn='arn:aws:iam::000000000000:role/test'),
                {'BackupJobId': job['BackupJobId']}
            )[2],
            'ListBackupJobs': {},
            'StopBackupJob': lambda store: (
                vault := store.create_backup_vault(BackupVaultName='vault-sjob'),  # noqa: E501
                job := store.start_backup_job(BackupVaultName=vault['BackupVaultName'],  # noqa: E501
                    ResourceArn='arn:aws:ec2:us-east-1:000000000000:instance/i-test',  # noqa: E501
                    IamRoleArn='arn:aws:iam::000000000000:role/test'),
                {'BackupJobId': job['BackupJobId']}
            )[2],
            'backup.TagResource': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-tag'),
                {'ResourceArn': plan['BackupPlanArn'], 'Tags': {'env': 'test'}}
            )[1],
            'backup.UntagResource': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-utag'),
                {'ResourceArn': plan['BackupPlanArn'], 'TagKeys': ['env']}
            )[1],
            'backup.ListTags': lambda store: (
                plan := store.create_backup_plan(BackupPlanName='plan-ltags'),
                {'ResourceArn': plan['BackupPlanArn']}
            )[1],
}
