# Test inputs for bedrock-runtime
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'bedrock-runtime.StartAsyncInvoke': {'modelId': 'anthropic.claude-v2', 'modelInput': {}, 'outputDataConfig': {'s3OutputDataConfig': {'s3Uri': 's3://test-bucket/output/'}}},  # noqa: E501
            'bedrock-runtime.GetAsyncInvoke': lambda store: (r := store.start_async_invoke(modelId='anthropic.claude-v2', modelInput={}, outputDataConfig={'s3OutputDataConfig': {'s3Uri': 's3://test-bucket/output/'}}), {'invocationArn': r['invocationArn']})[1],  # noqa: E501
            'bedrock-runtime.ListAsyncInvokes': {},
}
