# Test inputs for bedrock-agent
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'bedrock-agent.CreateAgent': {'agentName': 'ba-test-agent', 'foundationModel': 'anthropic.claude-v2'},  # noqa: E501
            'bedrock-agent.CreateKnowledgeBase': {'name': 'ba-test-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}},  # noqa: E501
            'bedrock-agent.ListAgents': {},
            'bedrock-agent.ListKnowledgeBases': {},
            'bedrock-agent.GetAgent': lambda store: (
                a := store.create_agent({'agentName': 'ba-get-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'agentId': a.agentId}
            )[1],
            'bedrock-agent.GetKnowledgeBase': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-get-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId}
            )[1],
            'bedrock-agent.DeleteAgent': lambda store: (
                a := store.create_agent({'agentName': 'ba-del-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'agentId': a.agentId}
            )[1],
            'bedrock-agent.DeleteKnowledgeBase': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-del-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId}
            )[1],
            'bedrock-agent.UpdateAgent': lambda store: (
                a := store.create_agent({'agentName': 'ba-upd-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'agentId': a.agentId, 'agentName': 'ba-upd-agent-renamed', 'foundationModel': 'anthropic.claude-v2'}  # noqa: E501
            )[1],
            'bedrock-agent.UpdateKnowledgeBase': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-upd-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId, 'name': 'ba-upd-kb-renamed', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}  # noqa: E501
            )[1],
            'bedrock-agent.CreateDataSource': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-ds-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId, 'name': 'ba-test-ds', 'dataSourceConfiguration': {'s3Configuration': {'bucketArn': 'arn:aws:s3:::test-bucket'}}}  # noqa: E501
            )[1],
            'bedrock-agent.GetDataSource': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-gds-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                ds := store.create_data_source({'knowledgeBaseId': kb.knowledgeBaseId, 'name': 'ba-gds-ds', 'dataSourceConfiguration': {'s3Configuration': {'bucketArn': 'arn:aws:s3:::test-bucket'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId, 'dataSourceId': ds.dataSourceId}  # noqa: E501
            )[2],
            'bedrock-agent.UpdateDataSource': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-uds-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                ds := store.create_data_source({'knowledgeBaseId': kb.knowledgeBaseId, 'name': 'ba-uds-ds', 'dataSourceConfiguration': {'s3Configuration': {'bucketArn': 'arn:aws:s3:::test-bucket'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId, 'dataSourceId': ds.dataSourceId, 'name': 'ba-uds-ds-renamed', 'dataSourceConfiguration': {'s3Configuration': {'bucketArn': 'arn:aws:s3:::test-bucket'}}}  # noqa: E501
            )[2],
            'bedrock-agent.DeleteDataSource': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-dds-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                ds := store.create_data_source({'knowledgeBaseId': kb.knowledgeBaseId, 'name': 'ba-dds-ds', 'dataSourceConfiguration': {'s3Configuration': {'bucketArn': 'arn:aws:s3:::test-bucket'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId, 'dataSourceId': ds.dataSourceId}  # noqa: E501
            )[2],
            'bedrock-agent.ListDataSources': lambda store: (
                kb := store.create_knowledge_base({'name': 'ba-lds-kb', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'knowledgeBaseConfiguration': {'type': 'VECTOR', 'vectorKnowledgeBaseConfiguration': {'embeddingModelArn': 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1'}}}),  # noqa: E501
                {'knowledgeBaseId': kb.knowledgeBaseId}
            )[1],
            'bedrock-agent.TagResource': lambda store: (
                a := store.create_agent({'agentName': 'ba-tag-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'resourceArn': a.agentArn, 'tags': {'test': 'val'}}
            )[1],
            'bedrock-agent.UntagResource': lambda store: (
                a := store.create_agent({'agentName': 'ba-untag-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                store.tag_resource(resourceARN=a.agentArn, tags={'test': 'val'}),  # noqa: E501
                {'resourceArn': a.agentArn, 'tagKeys': ['test']}
            )[2],
            'bedrock-agent.ListTagsForResource': lambda store: (
                a := store.create_agent({'agentName': 'ba-ltr-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'resourceArn': a.agentArn}
            )[1],
            'bedrock-agent.PrepareAgent': lambda store: (
                a := store.create_agent({'agentName': 'ba-prep-agent', 'foundationModel': 'anthropic.claude-v2'}),  # noqa: E501
                {'agentId': a.agentId}
            )[1],
}
