# Test inputs for bedrock
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'GetFoundationModel': {'modelIdentifier': 'anthropic.claude-v2'},
            'GetFoundationModelAvailability': {'modelId': 'anthropic.claude-v2'},  # noqa: E501
            'ListFoundationModels': {},
            'CreateGuardrail': {'name': 'test-guardrail', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'},  # noqa: E501
            'GetGuardrail': lambda store: (
                gr := store.create_guardrail({'name': 'gr-get', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'guardrailIdentifier': gr.guardrailId}
            )[1],
            'ListGuardrails': {},
            'DeleteGuardrail': lambda store: (
                gr := store.create_guardrail({'name': 'gr-del', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'guardrailIdentifier': gr.guardrailId}
            )[1],
            'UpdateGuardrail': lambda store: (
                gr := store.create_guardrail({'name': 'gr-upd', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'guardrailIdentifier': gr.guardrailId, 'name': 'gr-updated', 'blockedInputMessaging': 'Updated', 'blockedOutputsMessaging': 'Updated'}  # noqa: E501
            )[1],
            'CreateGuardrailVersion': lambda store: (
                gr := store.create_guardrail({'name': 'gr-ver', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'guardrailIdentifier': gr.guardrailId}
            )[1],
            'CreateModelCustomizationJob': {'jobName': 'test-job', 'customModelName': 'test-model', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'baseModelIdentifier': 'anthropic.claude-v2', 'trainingDataConfig': {'s3Uri': 's3://test/train.jsonl'}, 'outputDataConfig': {'s3Uri': 's3://test/output/'}},  # noqa: E501
            'GetModelCustomizationJob': lambda store: (
                job := store.create_model_customization_job({'jobName': 'job-get', 'customModelName': 'model-get', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'baseModelIdentifier': 'anthropic.claude-v2', 'trainingDataConfig': {'s3Uri': 's3://test/train.jsonl'}, 'outputDataConfig': {'s3Uri': 's3://test/output/'}}),  # noqa: E501
                {'jobIdentifier': job.jobArn}
            )[1],
            'StopModelCustomizationJob': lambda store: (
                job := store.create_model_customization_job({'jobName': 'job-stop', 'customModelName': 'model-stop', 'roleArn': 'arn:aws:iam::000000000000:role/test', 'baseModelIdentifier': 'anthropic.claude-v2', 'trainingDataConfig': {'s3Uri': 's3://test/train.jsonl'}, 'outputDataConfig': {'s3Uri': 's3://test/output/'}}),  # noqa: E501
                {'jobIdentifier': job.jobArn}
            )[1],
            'ListModelCustomizationJobs': {},
            'CreateProvisionedModelThroughput': {'modelUnits': 1, 'provisionedModelName': 'test-pt', 'modelId': 'anthropic.claude-v2'},  # noqa: E501
            'GetProvisionedModelThroughput': lambda store: (
                pm := store.create_provisioned_model_throughput({'modelUnits': 1, 'provisionedModelName': 'pm-get', 'modelId': 'anthropic.claude-v2'}),  # noqa: E501
                {'provisionedModelId': pm.provisionedModelId}
            )[1],
            'UpdateProvisionedModelThroughput': lambda store: (
                pm := store.create_provisioned_model_throughput({'modelUnits': 1, 'provisionedModelName': 'pm-upd', 'modelId': 'anthropic.claude-v2'}),  # noqa: E501
                {'provisionedModelId': pm.provisionedModelId, 'desiredProvisionedModelName': 'pm-updated'}  # noqa: E501
            )[1],
            'DeleteProvisionedModelThroughput': lambda store: (
                pm := store.create_provisioned_model_throughput({'modelUnits': 1, 'provisionedModelName': 'pm-del', 'modelId': 'anthropic.claude-v2'}),  # noqa: E501
                {'provisionedModelId': pm.provisionedModelId}
            )[1],
            'ListProvisionedModelThroughputs': {},
            'bedrock.TagResource': lambda store: (
                gr := store.create_guardrail({'name': 'gr-tag', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'resourceARN': gr.guardrailArn, 'tags': [{'key': 'env', 'value': 'test'}]}  # noqa: E501
            )[1],
            'bedrock.UntagResource': lambda store: (
                gr := store.create_guardrail({'name': 'gr-utag', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'resourceARN': gr.guardrailArn, 'tagKeys': ['env']}
            )[1],
            'bedrock.ListTagsForResource': lambda store: (
                gr := store.create_guardrail({'name': 'gr-ltag', 'blockedInputMessaging': 'Blocked', 'blockedOutputsMessaging': 'Blocked'}),  # noqa: E501
                {'resourceARN': gr.guardrailArn}
            )[1],
}
