# Test inputs for codeartifact
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'codeartifact.CreateDomain': {'domain': 'ca-test-domain'},
            'codeartifact.ListDomains': {},
            'codeartifact.DescribeDomain': lambda store: (d := store.domains.setdefault('ca-dd', DomainRecord('ca-dd', '123456789012')), store.domain_policies.setdefault('ca-dd', ''), {'domain': 'ca-dd'})[2],  # noqa: E501
            'codeartifact.DeleteDomain': lambda store: (d := store.domains.setdefault('ca-del-d', DomainRecord('ca-del-d', '123456789012')), store.domain_policies.setdefault('ca-del-d', ''), {'domain': 'ca-del-d'})[2],  # noqa: E501
            'codeartifact.CreateRepository': lambda store: (store.domains.setdefault('ca-cr-d', DomainRecord('ca-cr-d', '123456789012')), store.domain_policies.setdefault('ca-cr-d', ''), {'domain': 'ca-cr-d', 'repository': 'ca-cr-r'})[2],  # noqa: E501
            'codeartifact.ListRepositories': {},
            'codeartifact.ListRepositoriesInDomain': lambda store: (store.domains.setdefault('ca-lrid-d', DomainRecord('ca-lrid-d', '123456789012')), store.domain_policies.setdefault('ca-lrid-d', ''), {'domain': 'ca-lrid-d'})[2],  # noqa: E501
            'codeartifact.DescribeRepository': lambda store: (store.domains.setdefault('ca-dr-d', DomainRecord('ca-dr-d', '123456789012')), store.domain_policies.setdefault('ca-dr-d', ''), store.repositories.setdefault(('ca-dr-d', 'ca-dr-r'), RepositoryRecord('ca-dr-r', 'ca-dr-d', '123456789012')), {'domain': 'ca-dr-d', 'repository': 'ca-dr-r'})[3],  # noqa: E501
            'codeartifact.DeleteRepository': lambda store: (store.domains.setdefault('ca-delr-d', DomainRecord('ca-delr-d', '123456789012')), store.domain_policies.setdefault('ca-delr-d', ''), store.repositories.setdefault(('ca-delr-d', 'ca-delr-r'), RepositoryRecord('ca-delr-r', 'ca-delr-d', '123456789012')), {'domain': 'ca-delr-d', 'repository': 'ca-delr-r'})[3],  # noqa: E501
            'codeartifact.UpdateRepository': lambda store: (store.domains.setdefault('ca-ur-d', DomainRecord('ca-ur-d', '123456789012')), store.domain_policies.setdefault('ca-ur-d', ''), store.repositories.setdefault(('ca-ur-d', 'ca-ur-r'), RepositoryRecord('ca-ur-r', 'ca-ur-d', '123456789012')), {'domain': 'ca-ur-d', 'repository': 'ca-ur-r'})[3],  # noqa: E501
            'codeartifact.ListPackages': lambda store: (store.domains.setdefault('ca-lp-d', DomainRecord('ca-lp-d', '123456789012')), store.domain_policies.setdefault('ca-lp-d', ''), store.repositories.setdefault(('ca-lp-d', 'ca-lp-r'), RepositoryRecord('ca-lp-r', 'ca-lp-d', '123456789012')), {'domain': 'ca-lp-d', 'repository': 'ca-lp-r'})[3],  # noqa: E501
            'codeartifact.ListPackageVersions': lambda store: (store.domains.setdefault('ca-lpv-d', DomainRecord('ca-lpv-d', '123456789012')), store.domain_policies.setdefault('ca-lpv-d', ''), store.repositories.setdefault(('ca-lpv-d', 'ca-lpv-r'), RepositoryRecord('ca-lpv-r', 'ca-lpv-d', '123456789012')), {'domain': 'ca-lpv-d', 'repository': 'ca-lpv-r', 'format': 'npm', 'package': 'ca-test-pkg'})[3],  # noqa: E501
            'codeartifact.DescribePackageVersion': lambda store: (store.domains.setdefault('ca-dpv-d', DomainRecord('ca-dpv-d', '123456789012')), store.domain_policies.setdefault('ca-dpv-d', ''), store.repositories.setdefault(('ca-dpv-d', 'ca-dpv-r'), RepositoryRecord('ca-dpv-r', 'ca-dpv-d', '123456789012')), store.package_versions.setdefault(('ca-dpv-d', 'ca-dpv-r', 'ca-test-pkg', 'npm'), {}).setdefault('1.0.0', PackageVersionRecord('1.0.0', 'ca-test-pkg', 'npm')), {'domain': 'ca-dpv-d', 'repository': 'ca-dpv-r', 'format': 'npm', 'package': 'ca-test-pkg', 'packageVersion': '1.0.0'})[4],  # noqa: E501
            'codeartifact.GetRepositoryEndpoint': lambda store: (store.domains.setdefault('ca-gre-d', DomainRecord('ca-gre-d', '123456789012')), store.domain_policies.setdefault('ca-gre-d', ''), store.repositories.setdefault(('ca-gre-d', 'ca-gre-r'), RepositoryRecord('ca-gre-r', 'ca-gre-d', '123456789012')), {'domain': 'ca-gre-d', 'repository': 'ca-gre-r', 'format': 'npm'})[3],  # noqa: E501
            'codeartifact.GetAuthorizationToken': lambda store: (store.domains.setdefault('ca-gat-d', DomainRecord('ca-gat-d', '123456789012')), store.domain_policies.setdefault('ca-gat-d', ''), {'domain': 'ca-gat-d'})[2],  # noqa: E501
            'codeartifact.GetPackageVersionReadme': lambda store: (store.domains.setdefault('ca-gpvr-d', DomainRecord('ca-gpvr-d', '123456789012')), store.domain_policies.setdefault('ca-gpvr-d', ''), store.repositories.setdefault(('ca-gpvr-d', 'ca-gpvr-r'), RepositoryRecord('ca-gpvr-r', 'ca-gpvr-d', '123456789012')), store.package_versions.setdefault(('ca-gpvr-d', 'ca-gpvr-r', 'ca-readme-pkg', 'npm'), {}).setdefault('1.0.0', PackageVersionRecord('1.0.0', 'ca-readme-pkg', 'npm')), {'domain': 'ca-gpvr-d', 'repository': 'ca-gpvr-r', 'format': 'npm', 'package': 'ca-readme-pkg', 'packageVersion': '1.0.0'})[4],  # noqa: E501
            'codeartifact.GetDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-gdpp-d', DomainRecord('ca-gdpp-d', '123456789012')), store.domain_policies.setdefault('ca-gdpp-d', ''), {'domain': 'ca-gdpp-d'})[2],  # noqa: E501
            'codeartifact.PutDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-pdpp-d', DomainRecord('ca-pdpp-d', '123456789012')), store.domain_policies.setdefault('ca-pdpp-d', ''), {'domain': 'ca-pdpp-d', 'policyDocument': '{"Version":"2012-10-17"}'})[2],  # noqa: E501
            'codeartifact.DeleteDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-ddpp-d', DomainRecord('ca-ddpp-d', '123456789012')), store.domain_policies.setdefault('ca-ddpp-d', ''), {'domain': 'ca-ddpp-d'})[2],  # noqa: E501
            'codeartifact.GetRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-grpp-d', DomainRecord('ca-grpp-d', '123456789012')), store.domain_policies.setdefault('ca-grpp-d', ''), store.repositories.setdefault(('ca-grpp-d', 'ca-grpp-r'), RepositoryRecord('ca-grpp-r', 'ca-grpp-d', '123456789012')), {'domain': 'ca-grpp-d', 'repository': 'ca-grpp-r'})[3],  # noqa: E501
            'codeartifact.PutRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-prpp-d', DomainRecord('ca-prpp-d', '123456789012')), store.domain_policies.setdefault('ca-prpp-d', ''), store.repositories.setdefault(('ca-prpp-d', 'ca-prpp-r'), RepositoryRecord('ca-prpp-r', 'ca-prpp-d', '123456789012')), {'domain': 'ca-prpp-d', 'repository': 'ca-prpp-r', 'policyDocument': '{"Version":"2012-10-17"}'})[3],  # noqa: E501
            'codeartifact.DeleteRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-drpp-d', DomainRecord('ca-drpp-d', '123456789012')), store.domain_policies.setdefault('ca-drpp-d', ''), store.repositories.setdefault(('ca-drpp-d', 'ca-drpp-r'), RepositoryRecord('ca-drpp-r', 'ca-drpp-d', '123456789012')), {'domain': 'ca-drpp-d', 'repository': 'ca-drpp-r'})[3],  # noqa: E501
            'codeartifact.TagResource': lambda store: (d := store.domains.setdefault('ca-tag-d', DomainRecord('ca-tag-d', '123456789012')), {'resourceArn': d.arn, 'tags': [{'key': 'test', 'value': 'val'}]})[1],  # noqa: E501
            'codeartifact.UntagResource': lambda store: (d := store.domains.setdefault('ca-untag-d', DomainRecord('ca-untag-d', '123456789012')), {'resourceArn': d.arn, 'tagKeys': ['test']})[1],  # noqa: E501
            'UpdateEndpoint': lambda store: (store.create_endpoint_config(EndpointConfigName='updep-config', ProductionVariants=[{'InstanceType': 'ml.m5.large', 'InitialVariantWeight': 1.0, 'ModelName': 'test-model', 'VariantName': 'test-variant'}]), store.create_endpoint(EndpointName='upd-ep', EndpointConfigName='updep-config'), {'EndpointName': 'upd-ep', 'EndpointConfigName': 'updep-config'})[2],  # noqa: E501
            'CreateDomain': {'domain': 'ca-test-domain'},
            'CreateRepository': lambda store: {'domain': 'ca-test-domain', 'repository': 'ca-test-repo'},  # noqa: E501
            'DescribeDomain': lambda store: (store.domains.setdefault('ca-desc-domain',  # noqa: E501
                type('_DR',(),{'name':'ca-desc-domain','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-desc-domain','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-desc-domain','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-desc-domain'})[1],
            'DescribeRepository': lambda store: (store.domains.setdefault('ca-desc-repo-d',  # noqa: E501
                type('_DR',(),{'name':'ca-desc-repo-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-desc-repo-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-desc-repo-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-desc-repo-d','ca-desc-repo'),
                type('_RR',(),{'name':'ca-desc-repo','domain_name':'ca-desc-repo-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-desc-repo-d/ca-desc-repo','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-desc-repo-d', 'repository': 'ca-desc-repo'})[2],
            'DescribePackageVersion': lambda store: (store.domains.setdefault('ca-desc-pv-d',  # noqa: E501
                type('_DR',(),{'name':'ca-desc-pv-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-desc-pv-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-desc-pv-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-desc-pv-d','ca-desc-pv-r'),
                type('_RR',(),{'name':'ca-desc-pv-r','domain_name':'ca-desc-pv-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-desc-pv-d/ca-desc-pv-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-desc-pv-d', 'repository': 'ca-desc-pv-r', 'format': 'npm', 'package': 'test-pkg', 'packageVersion': '1.0.0'})[2],  # noqa: E501
            'GetDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-gdpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-gdpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-gdpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-gdpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-gdpp-d'})[1],
            'GetPackageVersionReadme': lambda store: (store.domains.setdefault('ca-gpvr-d',  # noqa: E501
                type('_DR',(),{'name':'ca-gpvr-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-gpvr-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-gpvr-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-gpvr-d','ca-gpvr-r'),
                type('_RR',(),{'name':'ca-gpvr-r','domain_name':'ca-gpvr-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-gpvr-d/ca-gpvr-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-gpvr-d', 'repository': 'ca-gpvr-r', 'format': 'npm', 'package': 'test-pkg', 'packageVersion': '1.0.0'})[2],  # noqa: E501
            'GetRepositoryEndpoint': lambda store: (store.domains.setdefault('ca-gre-d',  # noqa: E501
                type('_DR',(),{'name':'ca-gre-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-gre-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-gre-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-gre-d','ca-gre-r'),
                type('_RR',(),{'name':'ca-gre-r','domain_name':'ca-gre-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-gre-d/ca-gre-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-gre-d', 'repository': 'ca-gre-r', 'format': 'npm'})[2],  # noqa: E501
            'ListDomains': {},
            'ListRepositories': {},
            'ListRepositoriesInDomain': lambda store: (store.domains.setdefault('ca-test-domain',  # noqa: E501
                type('_DR',(),{'name':'ca-test-domain','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-test-domain','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-test-domain','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-test-domain'})[1],
            'ListPackages': lambda store: (store.domains.setdefault('ca-test-domain',  # noqa: E501
                type('_DR',(),{'name':'ca-test-domain','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-test-domain','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-test-domain','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-test-domain','ca-test-repo'),
                type('_RR',(),{'name':'ca-test-repo','domain_name':'ca-test-domain','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-test-domain/ca-test-repo','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-test-domain', 'repository': 'ca-test-repo'})[2],
            'ListPackageVersions': lambda store: (store.domains.setdefault('ca-test-domain',  # noqa: E501
                type('_DR',(),{'name':'ca-test-domain','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-test-domain','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-test-domain','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-test-domain','ca-test-repo'),
                type('_RR',(),{'name':'ca-test-repo','domain_name':'ca-test-domain','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-test-domain/ca-test-repo','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-test-domain', 'repository': 'ca-test-repo', 'format': 'npm', 'package': 'test-pkg'})[2],  # noqa: E501
            'DeleteDomain': lambda store: (store.domains.setdefault('ca-del-domain',  # noqa: E501
                type('_DR',(),{'name':'ca-del-domain','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-del-domain','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-del-domain','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-del-domain'})[1],
            'DeleteRepository': lambda store: (store.domains.setdefault('ca-del-repo-d',  # noqa: E501
                type('_DR',(),{'name':'ca-del-repo-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-del-repo-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-del-repo-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-del-repo-d','ca-del-repo'),
                type('_RR',(),{'name':'ca-del-repo','domain_name':'ca-del-repo-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-del-repo-d/ca-del-repo','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-del-repo-d', 'repository': 'ca-del-repo'})[2],
            'DeleteDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-ddpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-ddpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-ddpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-ddpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-ddpp-d'})[1],
            'DeleteRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-drpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-drpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-drpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-drpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-drpp-d','ca-drpp-r'),
                type('_RR',(),{'name':'ca-drpp-r','domain_name':'ca-drpp-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-drpp-d/ca-drpp-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-drpp-d', 'repository': 'ca-drpp-r'})[2],
            'GetRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-grpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-grpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-grpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-grpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-grpp-d','ca-grpp-r'),
                type('_RR',(),{'name':'ca-grpp-r','domain_name':'ca-grpp-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-grpp-d/ca-grpp-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-grpp-d', 'repository': 'ca-grpp-r'})[2],
            'PutDomainPermissionsPolicy': lambda store: (store.domains.setdefault('ca-pdpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-pdpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-pdpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-pdpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'domain': 'ca-pdpp-d', 'policyDocument': '{"Version":"2012-10-17","Statement":[]}', 'policyRevision': 'rev-1'})[1],  # noqa: E501
            'PutRepositoryPermissionsPolicy': lambda store: (store.domains.setdefault('ca-prpp-d',  # noqa: E501
                type('_DR',(),{'name':'ca-prpp-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-prpp-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-prpp-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-prpp-d','ca-prpp-r'),
                type('_RR',(),{'name':'ca-prpp-r','domain_name':'ca-prpp-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-prpp-d/ca-prpp-r','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-prpp-d', 'repository': 'ca-prpp-r', 'policyDocument': '{"Version":"2012-10-17","Statement":[]}', 'policyRevision': 'rev-1'})[2],  # noqa: E501
            'UpdateRepository': lambda store: (store.domains.setdefault('ca-upd-repo-d',  # noqa: E501
                type('_DR',(),{'name':'ca-upd-repo-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-upd-repo-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-upd-repo-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            store.repositories.setdefault(('ca-upd-repo-d','ca-upd-repo'),
                type('_RR',(),{'name':'ca-upd-repo','domain_name':'ca-upd-repo-d','domain_owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:repository/ca-upd-repo-d/ca-upd-repo','description':'','created_time':0,'administrator_account':'123456789012','external_connections':[],'upstreams':[]})()),  # noqa: E501
            {'domain': 'ca-upd-repo-d', 'repository': 'ca-upd-repo'})[2],
            'codeartifact.TagResource': lambda store: (store.domains.setdefault('ca-tag-d',  # noqa: E501
                type('_DR',(),{'name':'ca-tag-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-tag-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-tag-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'resourceArn': 'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-tag-d', 'tags': [{'key': 'env', 'value': 'test'}]})[1],  # noqa: E501
            'codeartifact.UntagResource': lambda store: (store.domains.setdefault('ca-untag-d',  # noqa: E501
                type('_DR',(),{'name':'ca-untag-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-untag-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-untag-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'resourceArn': 'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-untag-d', 'tagKeys': ['env']})[1],  # noqa: E501
            'codeartifact.ListTagsForResource': lambda store: (store.domains.setdefault('ca-ltfr-d',  # noqa: E501
                type('_DR',(),{'name':'ca-ltfr-d','owner':'123456789012','arn':'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-ltfr-d','encryption_key':'AWS_OWNED_KEY','s3_bucket_arn':'arn:aws:s3:::codeartifact-ca-ltfr-d','repository_count':0,'asset_size_bytes':0,'status':'Active','created_time':0})()),  # noqa: E501
            {'resourceArn': 'arn:aws:codeartifact:us-east-1:123456789012:domain/ca-ltfr-d'})[1],  # noqa: E501
}
