# Test inputs for codepipeline
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreatePipeline': {
                'pipeline': {
                    'name': 'cp-create-test',
                    'roleArn': 'arn:aws:iam::000000000000:role/test-role',
                    'stages': [{'name': 'Source', 'actions': [{'name': 'Src', 'actionTypeId': {'category': 'Source', 'owner': 'AWS', 'provider': 'S3', 'version': '1'}, 'outputArtifacts': [{'name': 'Out'}]}]}],  # noqa: E501
                },
            },
            'GetPipeline': lambda store: (
                pipeline := store.create_pipeline(name='cp-get', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'name': pipeline.get('name', 'cp-get')}
            )[1],
            'UpdatePipeline': lambda store: (
                pipeline := store.create_pipeline(name='cp-upd', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'pipeline': {'name': pipeline.get('name', 'cp-upd'), 'roleArn': 'arn:aws:iam::000000000000:role/r', 'stages': [{'name': 'Source', 'actions': []}]}}  # noqa: E501
            )[1],
            'DeletePipeline': lambda store: (
                pipeline := store.create_pipeline(name='cp-del', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'name': pipeline.get('name', 'cp-del')}
            )[1],
            'ListPipelines': {},
            'StartPipelineExecution': lambda store: (
                pipeline := store.create_pipeline(name='cp-start', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'name': pipeline.get('name', 'cp-start')}
            )[1],
            'StopPipelineExecution': lambda store: (
                pipeline := store.create_pipeline(name='cp-stop', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                exec_result := store.start_pipeline_execution(name=pipeline.get('name', 'cp-stop')),  # noqa: E501
                {'pipelineName': pipeline.get('name', 'cp-stop'), 'pipelineExecutionId': exec_result.get('pipelineExecutionId', 'test-exec-id')}  # noqa: E501
            )[2],
            'GetPipelineExecution': lambda store: (
                pipeline := store.create_pipeline(name='cp-gpex', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                exec_result := store.start_pipeline_execution(name=pipeline.get('name', 'cp-gpex')),  # noqa: E501
                {'pipelineName': pipeline.get('name', 'cp-gpex'), 'pipelineExecutionId': exec_result.get('pipelineExecutionId', 'test-exec-id')}  # noqa: E501
            )[2],
            'ListPipelineExecutions': lambda store: (
                pipeline := store.create_pipeline(name='cp-lpex', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'pipelineName': pipeline.get('name', 'cp-lpex')}
            )[1],
            'GetPipelineState': lambda store: (
                pipeline := store.create_pipeline(name='cp-gps', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}]),  # noqa: E501
                {'name': pipeline.get('name', 'cp-gps')}
            )[1],
            'CreateCustomActionType': {
                'category': 'Test',
                'provider': 'cp-test-provider',
                'version': '1',
            },
            'DeleteCustomActionType': lambda store: (
                store.create_custom_action_type(category='Test', provider='cp-del-provider', version='1',  # noqa: E501
                    input_artifact_details={'minimumCount': 0, 'maximumCount': 5},  # noqa: E501
                    output_artifact_details={'minimumCount': 0, 'maximumCount': 5}),  # noqa: E501
                {'category': 'Test', 'provider': 'cp-del-provider', 'version': '1'}  # noqa: E501
            )[1],
            'GetActionType': {
                'category': 'Test',
                'owner': 'Custom',
                'provider': 'cp-test-provider',
                'version': '1',
            },
            'UpdateActionType': lambda store: (
                store.create_custom_action_type(category='Test', provider='cp-upd-provider', version='1',  # noqa: E501
                    input_artifact_details={'minimumCount': 0, 'maximumCount': 5},  # noqa: E501
                    output_artifact_details={'minimumCount': 0, 'maximumCount': 5}),  # noqa: E501
                {'actionType': {'id': {'category': 'Test', 'owner': 'Custom', 'provider': 'cp-upd-provider', 'version': '1'}}}  # noqa: E501
            )[1],
            'ListActionTypes': {},
            'EnableStageTransition': lambda store: (
                pipeline := store.create_pipeline(name='cp-enst', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'Source', 'actions': []}]),  # noqa: E501
                {'pipelineName': pipeline.get('name', 'cp-enst'), 'stageName': 'Source', 'transitionType': 'Inbound'}  # noqa: E501
            )[1],
            'DisableStageTransition': lambda store: (
                pipeline := store.create_pipeline(name='cp-dist', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'Source', 'actions': []}]),  # noqa: E501
                {'pipelineName': pipeline.get('name', 'cp-dist'), 'stageName': 'Source', 'transitionType': 'Inbound', 'reason': 'testing'}  # noqa: E501
            )[1],
            'codepipeline.TagResource': lambda store: (
                pipeline := store.create_pipeline(name='cp-tag', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}], tags=[{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                arn := f"arn:aws:codepipeline:us-east-1:000000000000:pipeline/{pipeline.get('name', 'cp-tag')}",  # noqa: E501
                {'resourceArn': arn, 'tags': [{'Key': 'env', 'Value': 'test'}]}
            )[2],
            'codepipeline.UntagResource': lambda store: (
                pipeline := store.create_pipeline(name='cp-utag', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}], tags=[{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                arn := f"arn:aws:codepipeline:us-east-1:000000000000:pipeline/{pipeline.get('name', 'cp-utag')}",  # noqa: E501
                {'resourceArn': arn, 'tagKeys': ['env']}
            )[2],
            'codepipeline.ListTagsForResource': lambda store: (
                pipeline := store.create_pipeline(name='cp-ltag', role_arn='arn:aws:iam::000000000000:role/r', stages=[{'name': 'S', 'actions': []}], tags=[{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                arn := f"arn:aws:codepipeline:us-east-1:000000000000:pipeline/{pipeline.get('name', 'cp-ltag')}",  # noqa: E501
                {'resourceArn': arn}
            )[2],
}
