# Test inputs for codebuild
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateProject': {
                'name': 'test-project',
                'source': {'type': 'NO_SOURCE'},
                'environment': {'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                    'type': 'LINUX_CONTAINER'},
                'artifacts': {'type': 'NO_ARTIFACTS'},
                'serviceRole': 'arn:aws:iam::000000000000:role/test'
            },
            'BatchGetProjects': lambda store: (
                store.projects.create_project(name='cb-bgp', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'names': ['cb-bgp']}
            )[1],
            'ListProjects': {},
            'DeleteProject': lambda store: (
                store.projects.create_project(name='cb-del', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'name': 'cb-del'}
            )[1],
            'StartBuild': lambda store: (
                store.projects.create_project(name='cb-sb', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'projectName': 'cb-sb'}
            )[1],
            'BatchGetBuilds': lambda store: (
                store.projects.create_project(name='cb-bgb', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                b := store.builds.start_build(project_name='cb-bgb'),
                {'ids': [b.id]}
            )[2],
            'StopBuild': lambda store: (
                store.projects.create_project(name='cb-stb', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                b := store.builds.start_build(project_name='cb-stb'),
                {'id': b.id}
            )[2],
            'RetryBuild': lambda store: (
                store.projects.create_project(name='cb-rb', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                b := store.builds.start_build(project_name='cb-rb'),
                {'id': b.id}
            )[2],
            'ListBuilds': {},
            'ListBuildsForProject': lambda store: (
                store.projects.create_project(name='cb-lbfp', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'projectName': 'cb-lbfp'}
            )[1],
            'BatchDeleteBuilds': lambda store: (
                store.projects.create_project(name='cb-bdb', source={'type': 'NO_SOURCE'},  # noqa: E501
                    environment={'computeType': 'BUILD_GENERAL1_SMALL', 'image': 'aws/codebuild/standard:5.0',  # noqa: E501
                        'type': 'LINUX_CONTAINER'},
                    artifacts={'type': 'NO_ARTIFACTS'}, service_role='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                b := store.builds.start_build(project_name='cb-bdb'),
                {'ids': [b.id]}
            )[2],
}
