# Test inputs for codedeploy
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'codedeploy.CreateApplication': {'applicationName': 'test-app', 'computePlatform': 'Server'},  # noqa: E501
            'codedeploy.GetApplication': lambda store: (
                store.applications.create_application(application_name='cd-get-app'),  # noqa: E501
                {'applicationName': 'cd-get-app'}
            )[1],
            'codedeploy.UpdateApplication': lambda store: (
                store.applications.create_application(application_name='cd-upd-app'),  # noqa: E501
                {'applicationName': 'cd-upd-app', 'newApplicationName': 'cd-upd-app-renamed'}  # noqa: E501
            )[1],
            'codedeploy.DeleteApplication': lambda store: (
                store.applications.create_application(application_name='cd-del-app'),  # noqa: E501
                {'applicationName': 'cd-del-app'}
            )[1],
            'codedeploy.ListApplications': {},
            'codedeploy.BatchGetApplications': lambda store: (
                store.applications.create_application(application_name='cd-bg-app'),  # noqa: E501
                {'applicationNames': ['cd-bg-app']}
            )[1],
            'codedeploy.CreateDeploymentConfig': {'deploymentConfigName': 'test-config',  # noqa: E501
                'minimumHealthyHosts': {'type': 'HOST_COUNT', 'value': 1}},
            'codedeploy.GetDeploymentConfig': {'deploymentConfigName': 'CodeDeployDefault.OneAtATime'},  # noqa: E501
            'codedeploy.DeleteDeploymentConfig': lambda store: (
                store.deployment_configs.create_deployment_config(deployment_config_name='cd-dc-del'),  # noqa: E501
                {'deploymentConfigName': 'cd-dc-del'}
            )[1],
            'codedeploy.ListDeploymentConfigs': {},
            'codedeploy.CreateDeploymentGroup': lambda store: (
                store.applications.create_application(application_name='cd-dg-app'),  # noqa: E501
                {'applicationName': 'cd-dg-app', 'deploymentGroupName': 'test-dg',  # noqa: E501
                 'serviceRoleArn': 'arn:aws:iam::000000000000:role/test'}
            )[1],
            'codedeploy.GetDeploymentGroup': lambda store: (
                store.applications.create_application(application_name='cd-gdg-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-gdg-app',  # noqa: E501
                    deployment_group_name='cd-gdg-group', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'applicationName': 'cd-gdg-app', 'deploymentGroupName': 'cd-gdg-group'}  # noqa: E501
            )[2],
            'codedeploy.UpdateDeploymentGroup': lambda store: (
                store.applications.create_application(application_name='cd-udg-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-udg-app',  # noqa: E501
                    deployment_group_name='cd-udg-group', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'applicationName': 'cd-udg-app', 'currentDeploymentGroupName': 'cd-udg-group',  # noqa: E501
                 'newDeploymentGroupName': 'cd-udg-renamed'}
            )[2],
            'codedeploy.DeleteDeploymentGroup': lambda store: (
                store.applications.create_application(application_name='cd-dd-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-dd-app',  # noqa: E501
                    deployment_group_name='cd-dd-group', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'applicationName': 'cd-dd-app', 'deploymentGroupName': 'cd-dd-group'}  # noqa: E501
            )[2],
            'codedeploy.ListDeploymentGroups': lambda store: (
                store.applications.create_application(application_name='cd-ldg-app'),  # noqa: E501
                {'applicationName': 'cd-ldg-app'}
            )[1],
            'codedeploy.CreateDeployment': lambda store: (
                store.applications.create_application(application_name='cd-cdep-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-cdep-app',  # noqa: E501
                    deployment_group_name='cd-cdep-dg', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                {'applicationName': 'cd-cdep-app', 'deploymentGroupName': 'cd-cdep-dg',  # noqa: E501
                 'revision': {'revisionType': 'S3', 's3Location': {'bucket': 'test', 'key': 'app.zip', 'bundleType': 'zip'}}}  # noqa: E501
            )[2],
            'codedeploy.GetDeployment': lambda store: (
                store.applications.create_application(application_name='cd-gdep-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-gdep-app',  # noqa: E501
                    deployment_group_name='cd-gdep-dg', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                dep := store.deployments.create_deployment(application_name='cd-gdep-app',  # noqa: E501
                    deployment_group_name='cd-gdep-dg'),
                {'deploymentId': dep.deploymentId}
            )[3],
            'codedeploy.StopDeployment': lambda store: (
                store.applications.create_application(application_name='cd-sdep-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-sdep-app',  # noqa: E501
                    deployment_group_name='cd-sdep-dg', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                dep := store.deployments.create_deployment(application_name='cd-sdep-app',  # noqa: E501
                    deployment_group_name='cd-sdep-dg'),
                {'deploymentId': dep.deploymentId}
            )[3],
            'codedeploy.ListDeployments': {},
            'codedeploy.BatchGetDeployments': lambda store: (
                store.applications.create_application(application_name='cd-bgdep-app'),  # noqa: E501
                store.deployment_groups.create_deployment_group(application_name='cd-bgdep-app',  # noqa: E501
                    deployment_group_name='cd-bgdep-dg', service_role_arn='arn:aws:iam::000000000000:role/r'),  # noqa: E501
                dep := store.deployments.create_deployment(application_name='cd-bgdep-app',  # noqa: E501
                    deployment_group_name='cd-bgdep-dg'),
                {'deploymentIds': [dep.deploymentId]}
            )[3],
}
