# Test inputs for comprehend
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDataset': {'DatasetArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/test-ds', 'DatasetName': 'test-ds'},  # noqa: E501
            'CreateDocumentClassifier': {'DocumentClassifierArn': 'arn:aws:comprehend:us-east-1:123456789012:document-classifier/test-clf', 'DocumentClassifierName': 'test-clf'},  # noqa: E501
            'CreateEndpoint': {'EndpointArn': 'arn:aws:comprehend:us-east-1:123456789012:endpoint/test-ep', 'EndpointName': 'test-ep'},  # noqa: E501
            'CreateEntityRecognizer': {'EntityRecognizerArn': 'arn:aws:comprehend:us-east-1:123456789012:entity-recognizer/test-er', 'EntityRecognizerName': 'test-er'},  # noqa: E501
            'CreateFlywheel': {'FlywheelArn': 'arn:aws:comprehend:us-east-1:123456789012:flywheel/test-fw', 'FlywheelName': 'test-fw'},  # noqa: E501
            'ListDatasets': {},
            'ListDocumentClassifiers': {},
            'ListEndpoints': {},
            'ListEntityRecognizers': {},
            'ListFlywheels': {},
            'DeleteDataset': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:dataset/s-del-ds', 's-del-ds', 'dataset'), {'DatasetArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/s-del-ds'})[1],  # noqa: E501
            'DeleteDocumentClassifier': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:document-classifier/s-del-clf', 's-del-clf', 'document-classifier'), {'DocumentClassifierArn': 'arn:aws:comprehend:us-east-1:123456789012:document-classifier/s-del-clf'})[1],  # noqa: E501
            'DeleteEndpoint': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:endpoint/s-del-ep', 's-del-ep', 'endpoint'), {'EndpointArn': 'arn:aws:comprehend:us-east-1:123456789012:endpoint/s-del-ep'})[1],  # noqa: E501
            'DeleteEntityRecognizer': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:entity-recognizer/s-del-er', 's-del-er', 'entity-recognizer'), {'EntityRecognizerArn': 'arn:aws:comprehend:us-east-1:123456789012:entity-recognizer/s-del-er'})[1],  # noqa: E501
            'DeleteFlywheel': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:flywheel/s-del-fw', 's-del-fw', 'flywheel'), {'FlywheelArn': 'arn:aws:comprehend:us-east-1:123456789012:flywheel/s-del-fw'})[1],  # noqa: E501
            'DescribeDataset': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:dataset/s-desc-ds', 's-desc-ds', 'dataset'), {'DatasetArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/s-desc-ds'})[1],  # noqa: E501
            'DescribeDocumentClassifier': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:document-classifier/s-desc-clf', 's-desc-clf', 'document-classifier'), {'DocumentClassifierArn': 'arn:aws:comprehend:us-east-1:123456789012:document-classifier/s-desc-clf'})[1],  # noqa: E501
            'DescribeEndpoint': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:endpoint/s-desc-ep', 's-desc-ep', 'endpoint'), {'EndpointArn': 'arn:aws:comprehend:us-east-1:123456789012:endpoint/s-desc-ep'})[1],  # noqa: E501
            'DescribeEntityRecognizer': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:entity-recognizer/s-desc-er', 's-desc-er', 'entity-recognizer'), {'EntityRecognizerArn': 'arn:aws:comprehend:us-east-1:123456789012:entity-recognizer/s-desc-er'})[1],  # noqa: E501
            'DescribeFlywheel': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:flywheel/s-desc-fw', 's-desc-fw', 'flywheel'), {'FlywheelArn': 'arn:aws:comprehend:us-east-1:123456789012:flywheel/s-desc-fw'})[1],  # noqa: E501
            'DetectDominantLanguage': {'Text': 'This is a test sentence for language detection.'},  # noqa: E501
            'DetectEntities': {'Text': 'Amazon is headquartered in Seattle. Jeff Bezos founded it.', 'LanguageCode': 'en'},  # noqa: E501
            'DetectKeyPhrases': {'Text': 'This is a test sentence for key phrase detection.', 'LanguageCode': 'en'},  # noqa: E501
            'DetectPiiEntities': {'Text': 'John Doe lives at 123 Main St. His email is john@example.com.', 'LanguageCode': 'en'},  # noqa: E501
            'DetectSentiment': {'Text': 'I love this product, it works great!', 'LanguageCode': 'en'},  # noqa: E501
            'DetectSyntax': {'Text': 'The quick brown fox jumps over the lazy dog.', 'LanguageCode': 'en'},  # noqa: E501
            'DetectTargetedSentiment': {'Text': 'I love Amazon and Microsoft but I hate their customer service.', 'LanguageCode': 'en'},  # noqa: E501
            'DetectToxicContent': {'TextSegments': [{'Text': 'This is a perfectly fine test sentence.'}]},  # noqa: E501
            'ClassifyDocument': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:endpoint/s-cls-ep', 's-cls-ep', 'endpoint'), {'Text': 'This is a test document for classification.', 'EndpointArn': 'arn:aws:comprehend:us-east-1:123456789012:endpoint/s-cls-ep'})[1],  # noqa: E501
            'ContainsPiiEntities': {'Text': 'John Doe lives at 123 Main St. His email is john@example.com.', 'LanguageCode': 'en'},  # noqa: E501
            'comprehend.TagResource': {'ResourceArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/test', 'Tags': [{'Key': 'env', 'Value': 'test'}]},  # noqa: E501
            'comprehend.UntagResource': {'ResourceArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/test', 'TagKeys': ['env']},  # noqa: E501
            'comprehend.ListTagsForResource': {'ResourceArn': 'arn:aws:comprehend:us-east-1:123456789012:dataset/test'},  # noqa: E501
            'UpdateEndpoint': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:endpoint/s-upd-ep', 's-upd-ep', 'endpoint'), {'EndpointArn': 'arn:aws:comprehend:us-east-1:123456789012:endpoint/s-upd-ep', 'DesiredInferenceUnits': 1})[1],  # noqa: E501
            'UpdateFlywheel': lambda store: (store.create_entity('arn:aws:comprehend:us-east-1:123456789012:flywheel/s-upd-fw', 's-upd-fw', 'flywheel'), {'FlywheelArn': 'arn:aws:comprehend:us-east-1:123456789012:flywheel/s-upd-fw', 'DataAccessRoleArn': 'arn:aws:iam::123456789012:role/test-data-role'})[1],  # noqa: E501
}
