# Test inputs for datasync
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateAgent': {'ActivationKey': 'ds-test-key'},
            'DescribeAgent': lambda store: (
                a := store.create_agent(ActivationKey='ds-da-key'),
                {'AgentArn': a['AgentArn']}
            )[1],
            'ListAgents': {},
            'DeleteAgent': lambda store: (
                a := store.create_agent(ActivationKey='ds-dela-key'),
                {'AgentArn': a['AgentArn']}
            )[1],
            'UpdateAgent': lambda store: (
                a := store.create_agent(ActivationKey='ds-ua-key'),
                {'AgentArn': a['AgentArn'], 'Name': 'updated-agent'}
            )[1],
            'CreateLocationS3': {'S3BucketArn': 'arn:aws:s3:::test-bucket',
                'S3Config': {'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}},  # noqa: E501
            'CreateLocationNfs': {'Subdirectory': '/test',
                'ServerHostname': 'test-host.example.com',
                'OnPremConfig': {'AgentArns': []}},
            'ListLocations': {},
            'DeleteLocation': lambda store: (
                loc := store.create_location_s3(S3BucketArn='arn:aws:s3:::del-test',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                {'LocationArn': loc['LocationArn']}
            )[1],
            'DescribeLocationS3': lambda store: (
                loc := store.create_location_s3(S3BucketArn='arn:aws:s3:::desc-test',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                {'LocationArn': loc['LocationArn']}
            )[1],
            'CreateTask': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::src-task',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::dst-task',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                {'SourceLocationArn': src['LocationArn'],
                 'DestinationLocationArn': dst['LocationArn']}
            )[2],
            'DescribeTask': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::s-dt',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::d-dt',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                t := store.create_task(SourceLocationArn=src['LocationArn'],
                    DestinationLocationArn=dst['LocationArn']),
                {'TaskArn': t['TaskArn']}
            )[3],
            'ListTasks': {},
            'DeleteTask': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::s-delt',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::d-delt',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                t := store.create_task(SourceLocationArn=src['LocationArn'],
                    DestinationLocationArn=dst['LocationArn']),
                {'TaskArn': t['TaskArn']}
            )[3],
            'UpdateTask': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::s-ut',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::d-ut',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                t := store.create_task(SourceLocationArn=src['LocationArn'],
                    DestinationLocationArn=dst['LocationArn']),
                {'TaskArn': t['TaskArn'], 'Name': 'updated-task'}
            )[3],
            'StartTaskExecution': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::s-ste',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::d-ste',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                t := store.create_task(SourceLocationArn=src['LocationArn'],
                    DestinationLocationArn=dst['LocationArn']),
                {'TaskArn': t['TaskArn']}
            )[3],
            'DescribeTaskExecution': lambda store: (
                src := store.create_location_s3(S3BucketArn='arn:aws:s3:::s-dte',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                dst := store.create_location_s3(S3BucketArn='arn:aws:s3:::d-dte',  # noqa: E501
                    S3Config={'BucketAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                t := store.create_task(SourceLocationArn=src['LocationArn'],
                    DestinationLocationArn=dst['LocationArn']),
                e := store.start_task_execution(TaskArn=t['TaskArn']),
                {'TaskExecutionArn': e['TaskExecutionArn']}
            )[4],
            'datasync.TagResource': lambda store: (
                a := store.create_agent(ActivationKey='ds-tr-key'),
                {'ResourceArn': a['AgentArn'],
                 'Tags': [{'Key': 'test', 'Value': 'val'}]}
            )[1],
            'datasync.ListTagsForResource': lambda store: (
                a := store.create_agent(ActivationKey='ds-ltr-key'),
                {'ResourceArn': a['AgentArn']}
            )[1],
}
