# Test inputs for dms
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'dms.CreateReplicationInstance': {'ReplicationInstanceIdentifier': 'dms-test-inst', 'ReplicationInstanceClass': 'dms.t2.micro'},  # noqa: E501
            'dms.CreateEndpoint': {'EndpointIdentifier': 'dms-test-ep', 'EndpointType': 'source', 'EngineName': 'mysql'},  # noqa: E501
            'dms.CreateReplicationTask': lambda store: (
                store.create_replication_instance(ReplicationInstanceIdentifier='dms-task-inst', ReplicationInstanceClass='dms.t2.micro'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-task-src', EndpointType='source', EngineName='mysql'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-task-tgt', EndpointType='target', EngineName='mysql'),  # noqa: E501
                {'ReplicationTaskIdentifier': 'dms-test-task', 'SourceEndpointArn': 'arn:aws:dms:us-east-1:123456789012:endpoint/dms-task-src',  # noqa: E501
                 'TargetEndpointArn': 'arn:aws:dms:us-east-1:123456789012:endpoint/dms-task-tgt',  # noqa: E501
                 'MigrationType': 'full-load',
                 'ReplicationInstanceArn': 'arn:aws:dms:us-east-1:123456789012:rep/dms-task-inst'}  # noqa: E501
            )[3],
            'dms.DescribeEndpoints': {},
            'dms.DescribeReplicationInstances': {},
            'dms.DescribeReplicationTasks': {},
            'dms.StartReplicationTask': lambda store: (
                store.create_replication_instance(ReplicationInstanceIdentifier='dms-start-inst', ReplicationInstanceClass='dms.t2.micro'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-start-src', EndpointType='source', EngineName='mysql'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-start-tgt', EndpointType='target', EngineName='mysql'),  # noqa: E501
                store.create_replication_task(ReplicationTaskIdentifier='dms-start-task',  # noqa: E501
                    SourceEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-start-src',  # noqa: E501
                    TargetEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-start-tgt',  # noqa: E501
                    MigrationType='full-load',
                    ReplicationInstanceArn='arn:aws:dms:us-east-1:123456789012:rep/dms-start-inst'),  # noqa: E501
                {'ReplicationTaskIdentifier': 'dms-start-task'}
            )[4],
            'dms.StopReplicationTask': lambda store: (
                store.create_replication_instance(ReplicationInstanceIdentifier='dms-stop-inst', ReplicationInstanceClass='dms.t2.micro'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-stop-src', EndpointType='source', EngineName='mysql'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-stop-tgt', EndpointType='target', EngineName='mysql'),  # noqa: E501
                store.create_replication_task(ReplicationTaskIdentifier='dms-stop-task',  # noqa: E501
                    SourceEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-stop-src',  # noqa: E501
                    TargetEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-stop-tgt',  # noqa: E501
                    MigrationType='full-load',
                    ReplicationInstanceArn='arn:aws:dms:us-east-1:123456789012:rep/dms-stop-inst'),  # noqa: E501
                {'ReplicationTaskIdentifier': 'dms-stop-task'}
            )[4],
            'dms.DeleteEndpoint': lambda store: (
                store.create_endpoint(EndpointIdentifier='dms-del-ep', EndpointType='source', EngineName='mysql'),  # noqa: E501
                {'EndpointIdentifier': 'dms-del-ep'}
            )[1],
            'dms.DeleteReplicationInstance': lambda store: (
                store.create_replication_instance(ReplicationInstanceIdentifier='dms-del-inst', ReplicationInstanceClass='dms.t2.micro'),  # noqa: E501
                {'ReplicationInstanceIdentifier': 'dms-del-inst'}
            )[1],
            'dms.DeleteReplicationTask': lambda store: (
                store.create_replication_instance(ReplicationInstanceIdentifier='dms-delt-inst', ReplicationInstanceClass='dms.t2.micro'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-delt-src', EndpointType='source', EngineName='mysql'),  # noqa: E501
                store.create_endpoint(EndpointIdentifier='dms-delt-tgt', EndpointType='target', EngineName='mysql'),  # noqa: E501
                store.create_replication_task(ReplicationTaskIdentifier='dms-delt-task',  # noqa: E501
                    SourceEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-delt-src',  # noqa: E501
                    TargetEndpointArn='arn:aws:dms:us-east-1:123456789012:endpoint/dms-delt-tgt',  # noqa: E501
                    MigrationType='full-load',
                    ReplicationInstanceArn='arn:aws:dms:us-east-1:123456789012:rep/dms-delt-inst'),  # noqa: E501
                {'ReplicationTaskIdentifier': 'dms-delt-task'}
            )[4],
}
