# Test inputs for docdb
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDBCluster': {'DBClusterIdentifier': 'test-cluster', 'Engine': 'docdb'},  # noqa: E501
            'CreateDBClusterParameterGroup': {'DBClusterParameterGroupName': 'test-pg', 'DBParameterGroupFamily': 'docdb4.0', 'Description': 'test parameter group'},  # noqa: E501
            'CreateDBClusterSnapshot': lambda store: (store.create_cluster('snapshot-cluster', 'docdb'), {'DBClusterSnapshotIdentifier': 'test-snapshot', 'DBClusterIdentifier': 'snapshot-cluster'})[1],  # noqa: E501
            'CreateDBInstance': lambda store: (store.create_cluster('inst-cluster', 'docdb'), {'DBInstanceIdentifier': 'test-instance', 'DBClusterIdentifier': 'inst-cluster', 'DBInstanceClass': 'db.r5.large', 'Engine': 'docdb'})[1],  # noqa: E501
            'CreateDBSubnetGroup': {'DBSubnetGroupName': 'test-subnet-group', 'DBSubnetGroupDescription': 'test subnet group', 'SubnetIds': ['subnet-12345678']},  # noqa: E501
            'DescribeDBClusters': {},
            'DescribeDBClusterParameterGroups': {},
            'DescribeDBClusterSnapshots': {},
            'DescribeDBInstances': {},
            'DescribeDBSubnetGroups': {},
            'DeleteDBCluster': lambda store: (store.create_cluster('del-cluster', 'docdb'), {'DBClusterIdentifier': 'del-cluster'})[1],  # noqa: E501
            'DeleteDBClusterParameterGroup': lambda store: (store.create_parameter_group('del-pg', 'docdb4.0', 'to delete'), {'DBClusterParameterGroupName': 'del-pg'})[1],  # noqa: E501
            'DeleteDBClusterSnapshot': lambda store: (store.create_cluster('delsnap-cluster', 'docdb'), store.create_snapshot('del-snapshot', 'delsnap-cluster'), {'DBClusterSnapshotIdentifier': 'del-snapshot'})[2],  # noqa: E501
            'DeleteDBInstance': lambda store: (store.create_cluster('delinst-cluster', 'docdb'), store.create_instance('del-instance', 'delinst-cluster', 'db.r5.large', 'docdb'), {'DBInstanceIdentifier': 'del-instance'})[2],  # noqa: E501
            'DeleteDBSubnetGroup': lambda store: (store.create_subnet_group('del-subnet', 'to delete', ['subnet-12345678']), {'DBSubnetGroupName': 'del-subnet'})[1],  # noqa: E501
            'ModifyDBCluster': lambda store: (store.create_cluster('mod-cluster', 'docdb'), {'DBClusterIdentifier': 'mod-cluster'})[1],  # noqa: E501
            'ModifyDBClusterParameterGroup': lambda store: (store.create_parameter_group('mod-pg', 'docdb4.0', 'to modify'), {'DBClusterParameterGroupName': 'mod-pg', 'Parameters': []})[1],  # noqa: E501
            'ModifyDBInstance': lambda store: (store.create_cluster('modinst-cluster', 'docdb'), store.create_instance('mod-instance', 'modinst-cluster', 'db.r5.large', 'docdb'), {'DBInstanceIdentifier': 'mod-instance'})[2],  # noqa: E501
            'ModifyDBSubnetGroup': lambda store: (store.create_subnet_group('mod-subnet', 'to modify', ['subnet-12345678']), {'DBSubnetGroupName': 'mod-subnet', 'SubnetIds': ['subnet-87654321']})[1],  # noqa: E501
            'RebootDBInstance': lambda store: (store.create_cluster('reboot-cluster', 'docdb'), store.create_instance('reboot-instance', 'reboot-cluster', 'db.r5.large', 'docdb'), {'DBInstanceIdentifier': 'reboot-instance'})[2],  # noqa: E501
            'ResetDBClusterParameterGroup': lambda store: (store.create_parameter_group('reset-pg', 'docdb4.0', 'to reset'), {'DBClusterParameterGroupName': 'reset-pg'})[1],  # noqa: E501
            'CopyDBClusterSnapshot': lambda store: (store.create_cluster('copy-cluster', 'docdb'), store.create_snapshot('source-snapshot', 'copy-cluster'), {'SourceDBClusterSnapshotIdentifier': 'source-snapshot', 'TargetDBClusterSnapshotIdentifier': 'target-snapshot'})[2],  # noqa: E501
            'RestoreDBClusterFromSnapshot': lambda store: (store.create_cluster('restore-cluster', 'docdb'), store.create_snapshot('restore-snapshot', 'restore-cluster'), {'DBClusterIdentifier': 'restored-cluster', 'DBClusterSnapshotIdentifier': 'restore-snapshot', 'Engine': 'docdb'})[2],  # noqa: E501
            'StartDBCluster': lambda store: (store.create_cluster('start-cluster', 'docdb'), {'DBClusterIdentifier': 'start-cluster'})[1],  # noqa: E501
            'StopDBCluster': lambda store: (store.create_cluster('stop-cluster', 'docdb'), {'DBClusterIdentifier': 'stop-cluster'})[1],  # noqa: E501
}
