# Test inputs for dynamodbstreams
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'dynamodbstreams.ListStreams': {},
            'dynamodbstreams.DescribeStream': lambda store: (
                store._add_stream('arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000', 'test-table'),  # noqa: E501
                {'StreamArn': 'arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000'}  # noqa: E501
            )[1],
            'dynamodbstreams.GetShardIterator': lambda store: (
                s := store._add_stream('arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000', 'test-table'),  # noqa: E501
                {'StreamArn': 'arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000',  # noqa: E501
                 'ShardId': s.shards[0].ShardId,
                 'ShardIteratorType': 'TRIM_HORIZON'}
            )[1],
            'dynamodbstreams.GetRecords': lambda store: (
                s := store._add_stream('arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000', 'test-table'),  # noqa: E501
                it := store.get_shard_iterator(
                    'arn:aws:dynamodb:us-east-1:123456789012:table/test-table/stream/2024-01-01T00:00:00.000',  # noqa: E501
                    s.shards[0].ShardId, 'TRIM_HORIZON'),
                {'ShardIterator': it['ShardIterator']}
            )[2],
}
