# Test inputs for efs
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'efs.CreateFileSystem': {'CreationToken': 'efs-test-token'},
            'efs.CreateMountTarget': lambda store: (
                store.create_filesystem('efs-mt-token'),
                {'FileSystemId': 'fs-00000001', 'SubnetId': 'subnet-12345678'}
            )[1],
            'efs.DescribeFileSystems': {},
            'efs.DescribeMountTargets': lambda store: (
                store.create_filesystem('efs-dmt-token'),
                {'FileSystemId': 'fs-00000001'}
            )[1],
            'efs.DeleteFileSystem': lambda store: (
                store.create_filesystem('efs-del-token'),
                {'FileSystemId': 'fs-00000001'}
            )[1],
            'efs.DeleteMountTarget': lambda store: (
                store.create_filesystem('efs-dmt-del-token'),
                {'FileSystemId': 'fs-00000001', 'MountTargetId': 'fsmt-00000001'}  # noqa: E501
            )[1],
            'efs.TagResource': lambda store: (
                store.create_filesystem('efs-tag-token'),
                {'ResourceId': 'fs-00000001', 'Tags': [{'Key': 'env', 'Value': 'test'}]}  # noqa: E501
            )[1],
            'efs.UntagResource': lambda store: (
                store.create_filesystem('efs-untag-token'),
                {'ResourceId': 'fs-00000001', 'TagKeys': ['test']}
            )[1],
            'efs.ListTagsForResource': lambda store: (
                store.create_filesystem('efs-lt-token'),
                {'ResourceId': 'fs-00000001'}
            )[1],
}
