# Test inputs for elasticache
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateCacheCluster': {'CacheClusterId': 'test-cluster'},
            'CreateCacheParameterGroup': {'CacheParameterGroupName': 'test-pg',
                                          'CacheParameterGroupFamily': 'redis7.0',  # noqa: E501
                                          'Description': 'test parameter group'},  # noqa: E501
            'CreateCacheSubnetGroup': {'CacheSubnetGroupName': 'test-sg',
                                       'CacheSubnetGroupDescription': 'test subnet group',  # noqa: E501
                                       'SubnetIds': ['subnet-12345678']},
            'CreateReplicationGroup': {'ReplicationGroupId': 'test-rg',
                                       'ReplicationGroupDescription': 'test replication group'},  # noqa: E501
            'CreateSnapshot': {'SnapshotName': 'test-snapshot'},
            'CreateUser': {'UserId': 'test-user', 'UserName': 'testuser',
                           'Engine': 'redis', 'AccessString': 'on ~* +@all'},
            'CreateUserGroup': {'UserGroupId': 'test-ug', 'Engine': 'redis'},
            'DescribeCacheClusters': {},
            'DescribeCacheEngineVersions': {},
            'DescribeCacheParameterGroups': {},
            'DescribeCacheSubnetGroups': {},
            'DescribeEvents': {},
            'DescribeReplicationGroups': {},
            'DescribeSnapshots': {},
            'DescribeUserGroups': {},
            'DescribeUsers': {},
            'DeleteCacheCluster': lambda store: (
                store.cache_clusters.setdefault('el-del-cc', {'CacheClusterId': 'el-del-cc', 'Status': 'available'}),  # noqa: E501
                {'CacheClusterId': 'el-del-cc'})[1],
            'DeleteCacheParameterGroup': lambda store: (
                store.parameter_groups.setdefault('el-del-pg',
                    {'CacheParameterGroupName': 'el-del-pg', 'CacheParameterGroupFamily': 'redis7.0',  # noqa: E501
                     'Description': 'test'}),
                {'CacheParameterGroupName': 'el-del-pg'})[1],
            'DeleteCacheSubnetGroup': lambda store: (
                store.subnet_groups.setdefault('el-del-sg',
                    {'CacheSubnetGroupName': 'el-del-sg', 'CacheSubnetGroupDescription': 'test',  # noqa: E501
                     'SubnetIds': ['subnet-12345678'], 'VpcId': 'vpc-12345'}),
                {'CacheSubnetGroupName': 'el-del-sg'})[1],
            'DeleteReplicationGroup': lambda store: (
                store.replication_groups.setdefault('el-del-rg',
                    {'ReplicationGroupId': 'el-del-rg', 'ReplicationGroupDescription': 'test',  # noqa: E501
                     'Status': 'available'}),
                {'ReplicationGroupId': 'el-del-rg'})[1],
            'DeleteSnapshot': lambda store: (
                store.snapshots.setdefault('el-del-snap', {'SnapshotName': 'el-del-snap', 'Status': 'available'}),  # noqa: E501
                {'SnapshotName': 'el-del-snap'})[1],
            'DeleteUser': lambda store: (
                store.users.setdefault('el-del-user', {'UserId': 'el-del-user', 'UserName': 'deluser',  # noqa: E501
                    'Engine': 'redis', 'AccessString': 'on', 'Status': 'available'}),  # noqa: E501
                {'UserId': 'el-del-user'})[1],
            'DeleteUserGroup': lambda store: (
                store.user_groups.setdefault('el-del-ug', {'UserGroupId': 'el-del-ug', 'Engine': 'redis',  # noqa: E501
                    'Status': 'available'}),
                {'UserGroupId': 'el-del-ug'})[1],
            'ModifyCacheCluster': lambda store: (
                store.cache_clusters.setdefault('el-mod-cc', {'CacheClusterId': 'el-mod-cc', 'Status': 'available'}),  # noqa: E501
                {'CacheClusterId': 'el-mod-cc'})[1],
            'ModifyCacheParameterGroup': lambda store: (
                store.parameter_groups.setdefault('el-mod-pg',
                    {'CacheParameterGroupName': 'el-mod-pg', 'CacheParameterGroupFamily': 'redis7.0',  # noqa: E501
                     'Description': 'test'}),
                {'CacheParameterGroupName': 'el-mod-pg',
                 'ParameterNameValues': [{'ParameterName': 'timeout', 'ParameterValue': '300'}]})[1],  # noqa: E501
            'ModifyCacheSubnetGroup': lambda store: (
                store.subnet_groups.setdefault('el-mod-sg',
                    {'CacheSubnetGroupName': 'el-mod-sg', 'CacheSubnetGroupDescription': 'test',  # noqa: E501
                     'SubnetIds': ['subnet-12345678'], 'VpcId': 'vpc-12345'}),
                {'CacheSubnetGroupName': 'el-mod-sg', 'SubnetIds': ['subnet-87654321']})[1],  # noqa: E501
            'ModifyReplicationGroup': lambda store: (
                store.replication_groups.setdefault('el-mod-rg',
                    {'ReplicationGroupId': 'el-mod-rg', 'ReplicationGroupDescription': 'test',  # noqa: E501
                     'Status': 'available'}),
                {'ReplicationGroupId': 'el-mod-rg'})[1],
            'ModifyUser': lambda store: (
                store.users.setdefault('el-mod-user', {'UserId': 'el-mod-user', 'UserName': 'moduser',  # noqa: E501
                    'Engine': 'redis', 'AccessString': 'on', 'Status': 'available'}),  # noqa: E501
                {'UserId': 'el-mod-user'})[1],
            'ModifyUserGroup': lambda store: (
                store.user_groups.setdefault('el-mod-ug', {'UserGroupId': 'el-mod-ug', 'Engine': 'redis',  # noqa: E501
                    'Status': 'available'}),
                {'UserGroupId': 'el-mod-ug'})[1],
            'CopySnapshot': lambda store: (
                store.snapshots.setdefault('el-copy-src', {'SnapshotName': 'el-copy-src', 'Status': 'available'}),  # noqa: E501
                {'SourceSnapshotName': 'el-copy-src', 'TargetSnapshotName': 'el-copy-dst'})[1],  # noqa: E501
            'RebootCacheCluster': lambda store: (
                store.cache_clusters.setdefault('el-reb-cc', {'CacheClusterId': 'el-reb-cc', 'Status': 'available',  # noqa: E501
                    'NumCacheNodes': 2}),
                {'CacheClusterId': 'el-reb-cc', 'CacheNodeIdsToReboot': ['0001']})[1],  # noqa: E501
            'elasticache.AddTagsToResource': lambda store: (
                store.tags.setdefault('el-tag-arn', []),
                {'ResourceName': 'el-tag-arn',
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'elasticache.RemoveTagsFromResource': lambda store: (
                store.tags.setdefault('el-untag-arn', [{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                {'ResourceName': 'el-untag-arn',
                 'TagKeys': ['env']})[1],
            'elasticache.ListTagsForResource': lambda store: (
                store.tags.setdefault('el-ltfr-arn', []),
                {'ResourceName': 'el-ltfr-arn'})[1],
}
