# Test inputs for emr
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateSecurityConfiguration': {'Name': 'emr-sec-config', 'SecurityConfiguration': '{"EncryptionConfiguration": {}}'},  # noqa: E501
            'ListSecurityConfigurations': {},
            'DescribeSecurityConfiguration': lambda store: (
                store.create_security_configuration(Name='emr-dsc', SecurityConfiguration='{}'),  # noqa: E501
                {'Name': 'emr-dsc'})[1],
            'DeleteSecurityConfiguration': lambda store: (
                store.create_security_configuration(Name='emr-del-sc', SecurityConfiguration='{}'),  # noqa: E501
                {'Name': 'emr-del-sc'})[1],
            'CreateStudio': {'Name': 'emr-studio'},
            'ListStudios': {},
            'DescribeStudio': lambda store: (
                studio := store.create_studio(Name='emr-ds'),
                {'StudioId': studio.StudioId})[1],
            'UpdateStudio': lambda store: (
                studio := store.create_studio(Name='emr-us'),
                {'StudioId': studio.StudioId, 'Description': 'Updated'})[1],
            'DeleteStudio': lambda store: (
                studio := store.create_studio(Name='emr-del-s'),
                {'StudioId': studio.StudioId})[1],
            'emr.TagResource': lambda store: (
                cluster := store.run_job_flow(Name='emr-tag'),
                {'ResourceId': cluster.Id, 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],  # noqa: E501
            'emr.UntagResource': lambda store: (
                cluster := store.run_job_flow(Name='emr-untag'),
                store.add_tags(cluster.Id, [{'Key': 'env', 'Value': 'test'}]),
                {'ResourceId': cluster.Id, 'TagKeys': ['env']})[2],
            'emr.ListTagsForResource': lambda store: (
                cluster := store.run_job_flow(Name='emr-ltr'),
                store.add_tags(cluster.Id, [{'Key': 'env', 'Value': 'test'}]),
                {'ResourceId': cluster.Id})[2],
}
