# Test inputs for fis
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateExperimentTemplate': {'description': 'test template', 'roleArn': 'arn:aws:iam::123456789012:role/test', 'stopConditions': [{'source': 'none'}], 'actions': {}, 'targets': {}},  # noqa: E501
            'ListExperimentTemplates': {},
            'DescribeExperimentTemplate': lambda store: (t := store.create_experiment_template(description='desc', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), {'id': t['id']})[1],  # noqa: E501
            'UpdateExperimentTemplate': lambda store: (t := store.create_experiment_template(description='upd', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), {'id': t['id'], 'description': 'updated'})[1],  # noqa: E501
            'DeleteExperimentTemplate': lambda store: (t := store.create_experiment_template(description='del', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), {'id': t['id']})[1],  # noqa: E501
            'StartExperiment': lambda store: (t := store.create_experiment_template(description='start', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), {'experimentTemplateId': t['id']})[1],  # noqa: E501
            'ListExperiments': {},
            'DescribeExperiment': lambda store: (t := store.create_experiment_template(description='de', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), e := store.start_experiment(experimentTemplateId=t['id']), {'id': e['id']})[2],  # noqa: E501
            'StopExperiment': lambda store: (t := store.create_experiment_template(description='stop', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), e := store.start_experiment(experimentTemplateId=t['id']), {'id': e['id']})[2],  # noqa: E501
            'DeleteExperiment': lambda store: (t := store.create_experiment_template(description='dele', roleArn='arn:aws:iam::123456789012:role/test', stopConditions=[{'source': 'none'}], actions={}, targets={}), e := store.start_experiment(experimentTemplateId=t['id']), {'id': e['id']})[2],  # noqa: E501
}
