# Test inputs for forecast
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'forecast.CreateDataset': {'DatasetName': 'fc-test-dataset', 'Domain': 'CUSTOM', 'DatasetType': 'TARGET_TIME_SERIES', 'Schema': {}},  # noqa: E501
            'forecast.CreateForecast': {'ForecastName': 'fc-test-forecast', 'PredictorArn': 'arn:aws:forecast:us-east-1:123456789012:predictor/fc-test-predictor'},  # noqa: E501
            'forecast.CreatePredictor': {'PredictorName': 'fc-test-predictor', 'InputDataConfig': {'DatasetGroupArn': 'arn:aws:forecast:us-east-1:123456789012:dataset-group/fc-test-dg'}, 'FeaturizationConfig': {'ForecastFrequency': 'D'}, 'ForecastHorizon': 7},  # noqa: E501
            'forecast.DeleteDataset': lambda store: (r := store.create_dataset('fc-del-ds', Domain='CUSTOM', DatasetType='TARGET_TIME_SERIES', Schema={}), {'DatasetArn': r.DatasetArn})[1],  # noqa: E501
            'forecast.DeleteForecast': lambda store: (r := store.create_forecast('fc-del-fc', PredictorArn='arn:aws:forecast:us-east-1:123456789012:predictor/fc-p'), {'ForecastArn': r.ForecastArn})[1],  # noqa: E501
            'forecast.DeletePredictor': lambda store: (r := store.create_predictor('fc-del-pr', InputDataConfig={'DatasetGroupArn': 'arn:test'}, FeaturizationConfig={'ForecastFrequency': 'D'}, ForecastHorizon=7), {'PredictorArn': r.PredictorArn})[1],  # noqa: E501
            'forecast.DescribeDataset': lambda store: (r := store.create_dataset('fc-desc-ds', Domain='CUSTOM', DatasetType='TARGET_TIME_SERIES', Schema={}), {'DatasetArn': r.DatasetArn})[1],  # noqa: E501
            'forecast.DescribeForecast': lambda store: (r := store.create_forecast('fc-desc-fc', PredictorArn='arn:aws:forecast:us-east-1:123456789012:predictor/fc-p'), {'ForecastArn': r.ForecastArn})[1],  # noqa: E501
            'forecast.DescribePredictor': lambda store: (r := store.create_predictor('fc-desc-pr', InputDataConfig={'DatasetGroupArn': 'arn:test'}, FeaturizationConfig={'ForecastFrequency': 'D'}, ForecastHorizon=7), {'PredictorArn': r.PredictorArn})[1],  # noqa: E501
            'forecast.ListDatasets': {},
            'forecast.ListForecasts': {},
            'forecast.ListPredictors': {},
            'forecast.TagResource': lambda store: (r := store.create_dataset('fc-tag-ds', Domain='CUSTOM', DatasetType='TARGET_TIME_SERIES', Schema={}), {'ResourceArn': r.DatasetArn, 'Tags': [{'Key': 'test', 'Value': 'val'}]})[1],  # noqa: E501
            'forecast.UntagResource': lambda store: (r := store.create_dataset('fc-untag-ds', Domain='CUSTOM', DatasetType='TARGET_TIME_SERIES', Schema={}), {'ResourceArn': r.DatasetArn, 'TagKeys': ['test']})[1],  # noqa: E501
            'forecast.ListTagsForResource': lambda store: (r := store.create_dataset('fc-ltfr-ds', Domain='CUSTOM', DatasetType='TARGET_TIME_SERIES', Schema={}), {'ResourceArn': r.DatasetArn})[1],  # noqa: E501
}
