# Test inputs for frauddetector
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateModel': {'modelId': 's-cm-model', 'modelType': 'ONLINE_FRAUD_INSIGHTS',  # noqa: E501
                            'eventTypeName': 's-cm-et'},
            'CreateRule': lambda store: (
                store.create_detector('s-cr-detector', eventTypeName='s-cr-et'),  # noqa: E501
                {'ruleId': 's-cr-rule', 'detectorId': 's-cr-detector',
                 'expression': 'true', 'language': 'DETECTORPL',
                 'outcomes': ['high_risk']})[1],
            'CreateVariable': {'name': 's-cv-var', 'dataType': 'FLOAT', 'dataSource': 'EXTERNAL_MODEL_SCORE',  # noqa: E501
                               'defaultValue': '0.0'},
            'PutDetector': {'detectorId': 's-pd-detector', 'eventTypeName': 's-pd-et'},  # noqa: E501
            'PutEventType': {'name': 's-pe-et',
                             'eventVariables': ['var1'], 'entityTypes': ['customer'],  # noqa: E501
                             'labels': ['fraud', 'legit']},
            'DescribeDetector': lambda store: (
                store.create_detector('s-desc-detector', eventTypeName='s-desc-et'),  # noqa: E501
                {'detectorId': 's-desc-detector'})[1],
            'DeleteDetector': lambda store: (
                store.create_detector('s-dd-detector', eventTypeName='s-dd-et'),  # noqa: E501
                {'detectorId': 's-dd-detector'})[1],
            'DeleteEventType': lambda store: (
                store.create_eventtype('s-det-et', eventVariables=['v1'],
                                       entityTypes=['customer']),
                {'name': 's-det-et'})[1],
            'DeleteModel': lambda store: (
                store.create_model('s-dm-model', 'ONLINE_FRAUD_INSIGHTS',
                                   eventTypeName='s-dm-et'),
                {'modelId': 's-dm-model', 'modelType': 'ONLINE_FRAUD_INSIGHTS'})[1],  # noqa: E501
            'DeleteRule': lambda store: (
                store.create_detector('s-dr-detector', eventTypeName='s-dr-et'),  # noqa: E501
                store.create_rule('s-dr-rule', 's-dr-detector',
                                  expression='true', language='DETECTORPL',
                                  outcomes=['high_risk']),
                {'rule': 's-dr-detector/s-dr-rule'})[2],
            'DeleteVariable': lambda store: (
                store.create_variable('s-dv-var', dataType='FLOAT',
                                      dataSource='EXTERNAL_MODEL_SCORE',
                                      defaultValue='0.0'),
                {'name': 's-dv-var'})[1],
            'UpdateModel': lambda store: (
                store.create_model('s-um-model', 'ONLINE_FRAUD_INSIGHTS',
                                   eventTypeName='s-um-et'),
                {'modelId': 's-um-model', 'modelType': 'ONLINE_FRAUD_INSIGHTS',
                 'description': 'updated'})[1],
            'UpdateVariable': lambda store: (
                store.create_variable('s-uv-var', dataType='FLOAT',
                                      dataSource='EXTERNAL_MODEL_SCORE',
                                      defaultValue='0.0'),
                {'name': 's-uv-var', 'dataType': 'FLOAT',
                 'dataSource': 'EXTERNAL_MODEL_SCORE',
                 'defaultValue': '0.5'})[1],
            'frauddetector.TagResource': lambda store: (
                store.create_detector('s-fd-tag', eventTypeName='s-fd-tag-et'),
                {'resourceARN': 'arn:aws:frauddetector:us-east-1:123456789012:detector/s-fd-tag',  # noqa: E501
                 'tags': [{'key': 'env', 'value': 'test'}]})[1],
            'frauddetector.UntagResource': lambda store: (
                store.create_detector('s-fd-untag', eventTypeName='s-fd-untag-et'),  # noqa: E501
                {'resourceARN': 'arn:aws:frauddetector:us-east-1:123456789012:detector/s-fd-untag',  # noqa: E501
                 'tagKeys': ['env']})[1],
            'frauddetector.ListTagsForResource': lambda store: (
                store.create_detector('s-fd-ltf', eventTypeName='s-fd-ltf-et'),
                {'resourceARN': 'arn:aws:frauddetector:us-east-1:123456789012:detector/s-fd-ltf'})[1],  # noqa: E501
}
