# Test inputs for fsx
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateFileCache': {'FileCacheType': 'LUSTRE', 'FileCacheTypeVersion': '2.12',  # noqa: E501
                                'StorageCapacity': 1200, 'SubnetIds': ['subnet-abc123']},  # noqa: E501
            'CreateFileSystem': {'FileSystemType': 'WINDOWS', 'SubnetIds': ['subnet-abc123']},  # noqa: E501
            'CreateVolume': {'VolumeType': 'ONTAP', 'Name': 'fsx-test-vol'},
            'CreateBackup': {},
            'CopyBackup': lambda store: (
                bk := store.create_backup(),
                {'SourceBackupId': bk.BackupId})[1],
            'CreateFileSystemFromBackup': lambda store: (
                bk := store.create_backup(),
                {'BackupId': bk.BackupId, 'SubnetIds': ['subnet-abc123']})[1],
            'CreateSnapshot': lambda store: (
                vol := store.create_volume('ONTAP', 'fsx-test-vol'),
                {'Name': 'fsx-test-snap', 'VolumeId': vol.VolumeId})[1],
            'CreateStorageVirtualMachine': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'FileSystemId': fs.FileSystemId, 'Name': 'fsx-test-svm'})[1],
            'CreateVolumeFromBackup': lambda store: (
                vol := store.create_volume('ONTAP', 'test-vol-bk'),
                bk := store.create_backup(VolumeId=vol.VolumeId),
                {'BackupId': bk.BackupId, 'Name': 'restored-vol', 'VolumeType': 'ONTAP'})[2],  # noqa: E501
            'DescribeFileCaches': {},
            'DescribeFileSystems': {},
            'DescribeVolumes': {},
            'DescribeBackups': {},
            'DescribeSnapshots': {},
            'DescribeStorageVirtualMachines': {},
            'DeleteFileCache': lambda store: (
                fc := store.create_file_cache('LUSTRE', '2.12', 1200, ['subnet-abc123']),  # noqa: E501
                {'FileCacheId': fc.FileCacheId})[1],
            'DeleteFileSystem': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'FileSystemId': fs.FileSystemId})[1],
            'DeleteVolume': lambda store: (
                vol := store.create_volume('ONTAP', 'fsx-del-vol'),
                {'VolumeId': vol.VolumeId})[1],
            'DeleteBackup': lambda store: (
                bk := store.create_backup(),
                {'BackupId': bk.BackupId})[1],
            'DeleteSnapshot': lambda store: (
                vol := store.create_volume('ONTAP', 'fsx-snap-vol'),
                snap := store.create_snapshot(Name='fsx-test-snap', VolumeId=vol.VolumeId),  # noqa: E501
                {'SnapshotId': snap.SnapshotId})[2],
            'DeleteStorageVirtualMachine': lambda store: (
                fs := store.create_file_system('ONTAP', ['subnet-abc123'], StorageCapacity=1200),  # noqa: E501
                svm := store.create_storage_virtual_machine(FileSystemId=fs.FileSystemId,  # noqa: E501
                                                            Name='fsx-del-svm'),  # noqa: E501
                {'StorageVirtualMachineId': svm.StorageVirtualMachineId})[2],
            'UpdateFileCache': lambda store: (
                fc := store.create_file_cache('LUSTRE', '2.12', 1200, ['subnet-abc123']),  # noqa: E501
                {'FileCacheId': fc.FileCacheId, 'ClientRequestToken': 'tok'})[1],  # noqa: E501
            'UpdateFileSystem': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'FileSystemId': fs.FileSystemId})[1],
            'UpdateVolume': lambda store: (
                vol := store.create_volume('ONTAP', 'fsx-upd-vol'),
                {'VolumeId': vol.VolumeId, 'Name': 'fsx-updated-vol'})[1],
            'UpdateSnapshot': lambda store: (
                vol := store.create_volume('ONTAP', 'fsx-upd-vol'),
                snap := store.create_snapshot(Name='fsx-upd-snap-old', VolumeId=vol.VolumeId),  # noqa: E501
                {'SnapshotId': snap.SnapshotId, 'Name': 'fsx-updated-snap'})[2],  # noqa: E501
            'UpdateStorageVirtualMachine': lambda store: (
                fs := store.create_file_system('ONTAP', ['subnet-abc123'], StorageCapacity=1200),  # noqa: E501
                svm := store.create_storage_virtual_machine(FileSystemId=fs.FileSystemId,  # noqa: E501
                                                            Name='fsx-upd-svm'),  # noqa: E501
                {'StorageVirtualMachineId': svm.StorageVirtualMachineId,
                 'ActiveDirectoryConfiguration': {'SelfManagedActiveDirectoryConfiguration': {  # noqa: E501
                     'DomainName': 'corp.example.com',
                     'OrganizationalUnitDistinguishedName': 'OU=FileSystems,DC=corp,DC=example,DC=com',  # noqa: E501
                     'FileSystemAdministratorsGroup': 'FSxAdmins',
                     'UserName': 'Admin',
                     'Password': 'Passw0rd!',
                     'DnsIps': ['10.0.1.4', '10.0.2.5']}}})[2],
            'fsx.ListTagsForResource': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'ResourceARN': f'arn:aws:fsx:us-east-1:000000000000:file-system/{fs.FileSystemId}'})[1],  # noqa: E501
            'fsx.TagResource': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'ResourceARN': f'arn:aws:fsx:us-east-1:000000000000:file-system/{fs.FileSystemId}',  # noqa: E501
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'fsx.UntagResource': lambda store: (
                fs := store.create_file_system('WINDOWS', ['subnet-abc123']),
                {'ResourceARN': f'arn:aws:fsx:us-east-1:000000000000:file-system/{fs.FileSystemId}',  # noqa: E501
                 'TagKeys': ['env']})[1],
}
