# Test inputs for glue
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDatabase': {'Name': 'glue-test-db'},
            'GetDatabase': lambda store: (store.databases(name='glue-get-db', catalog_id='default', record={'Name': 'glue-get-db'}), {'Name': 'glue-get-db'})[1],  # noqa: E501
            'CreateCrawler': {'Name': 'glue-test-crawler', 'Role': 'arn:aws:iam::123456789012:role/glue', 'Targets': {'JdbcTargets': []}},  # noqa: E501
            'codeartifact.ListTagsForResource': lambda store: (d := store.domains.setdefault('ca-ltfr-d', DomainRecord('ca-ltfr-d', '123456789012')), {'resourceArn': d.arn})[1],  # noqa: E501
}
