# Test inputs for greengrassv2
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateComponentVersion': {'componentName': 'test-component', 'componentVersion': '1.0.0'},  # noqa: E501
            'ListComponents': {},
            'DescribeComponent': lambda store: (store.create_component_version(componentName='desc-comp', componentVersion='1.0.0'), {'componentName': 'desc-comp', 'componentVersion': '1.0.0'})[1],  # noqa: E501
            'DeleteComponent': lambda store: (store.create_component_version(componentName='del-comp', componentVersion='1.0.0'), {'componentName': 'del-comp', 'componentVersion': '1.0.0'})[1],  # noqa: E501
            'CreateCoreDevice': {'coreDeviceThingName': 'test-thing'},
            'ListCoreDevices': {},
            'DescribeCoreDevice': lambda store: (store.create_core_device(coreDeviceThingName='desc-thing'), {'coreDeviceThingName': 'desc-thing'})[1],  # noqa: E501
            'DeleteCoreDevice': lambda store: (store.create_core_device(coreDeviceThingName='del-thing'), {'coreDeviceThingName': 'del-thing'})[1],  # noqa: E501
            'CreateDeployment': {'targetArn': 'arn:aws:iot:us-east-1:123456789012:thing/test-thing'},  # noqa: E501
            'ListDeployments': {},
            'DescribeDeployment': lambda store: (d := store.create_deployment(targetArn='arn:aws:iot:us-east-1:123456789012:thing/desc-thing'), {'deploymentId': d['deploymentId']})[1],  # noqa: E501
            'DeleteDeployment': lambda store: (d := store.create_deployment(targetArn='arn:aws:iot:us-east-1:123456789012:thing/del-thing'), {'deploymentId': d['deploymentId']})[1],  # noqa: E501
}
