# Test inputs for identitystore
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateUser': {'identityStoreId': 'd-12345', 'userName': 'test-user',  # noqa: E501
                 'displayName': 'Test User', 'emails': [{'value': 'test@example.com', 'primary': True}],  # noqa: E501
                 'name': {'givenName': 'Test', 'familyName': 'User'}},
            'DescribeUser': lambda store: (
                u := store.create_user(identityStoreId='d-is-desc', userName='desc-user'),  # noqa: E501
                {'identityStoreId': 'd-is-desc', 'userId': u['UserId']}
            )[1],
            'UpdateUser': lambda store: (
                u := store.create_user(identityStoreId='d-is-upd', userName='upd-user'),  # noqa: E501
                {'identityStoreId': 'd-is-upd', 'userId': u['UserId'],
                 'operations': [{'attributePath': 'userName', 'attributeValue': 'upd-user-renamed'}]}  # noqa: E501
            )[1],
            'DeleteUser': lambda store: (
                u := store.create_user(identityStoreId='d-is-del', userName='del-user'),  # noqa: E501
                {'identityStoreId': 'd-is-del', 'userId': u['UserId']}
            )[1],
            'ListUsers': {'identityStoreId': 'd-12345'},
            'GetUserId': lambda store: (
                store.create_user(identityStoreId='d-is-gid', userName='gid-user'),  # noqa: E501
                {'identityStoreId': 'd-is-gid',
                 'alternateIdentifier': {'UniqueAttribute': {'AttributePath': 'userName', 'AttributeValue': 'gid-user'}}}  # noqa: E501
            )[1],
            'CreateGroup': {'identityStoreId': 'd-12345', 'displayName': 'test-group',  # noqa: E501
                 'description': 'Test group'},
            'DescribeGroup': lambda store: (
                g := store.create_group(identityStoreId='d-is-dgrp', displayName='desc-group'),  # noqa: E501
                {'identityStoreId': 'd-is-dgrp', 'groupId': g['GroupId']}
            )[1],
            'UpdateGroup': lambda store: (
                g := store.create_group(identityStoreId='d-is-ugrp', displayName='upd-group'),  # noqa: E501
                {'identityStoreId': 'd-is-ugrp', 'groupId': g['GroupId'],
                 'operations': [{'attributePath': 'displayName', 'attributeValue': 'upd-group-renamed'}]}  # noqa: E501
            )[1],
            'DeleteGroup': lambda store: (
                g := store.create_group(identityStoreId='d-is-dgrp2', displayName='del-group'),  # noqa: E501
                {'identityStoreId': 'd-is-dgrp2', 'groupId': g['GroupId']}
            )[1],
            'ListGroups': {'identityStoreId': 'd-12345'},
            'GetGroupId': lambda store: (
                store.create_group(identityStoreId='d-is-ggid', displayName='ggid-group'),  # noqa: E501
                {'identityStoreId': 'd-is-ggid',
                 'alternateIdentifier': {'UniqueAttribute': {'AttributePath': 'displayName', 'AttributeValue': 'ggid-group'}}}  # noqa: E501
            )[1],
            'CreateGroupMembership': lambda store: (
                g := store.create_group(identityStoreId='d-is-cgm', displayName='cgm-group'),  # noqa: E501
                u := store.create_user(identityStoreId='d-is-cgm', userName='cgm-user'),  # noqa: E501
                {'identityStoreId': 'd-is-cgm', 'groupId': g['GroupId'],
                 'memberId': {'userId': u['UserId']}}
            )[2],
            'DescribeGroupMembership': lambda store: (
                g := store.create_group(identityStoreId='d-is-dgm', displayName='dgm-group'),  # noqa: E501
                u := store.create_user(identityStoreId='d-is-dgm', userName='dgm-user'),  # noqa: E501
                m := store.create_group_membership(identityStoreId='d-is-dgm', groupId=g['GroupId'],  # noqa: E501
                    memberId={'userId': u['UserId']}),
                {'identityStoreId': 'd-is-dgm', 'membershipId': m['MembershipId']}  # noqa: E501
            )[3],
            'DeleteGroupMembership': lambda store: (
                g := store.create_group(identityStoreId='d-is-lgm', displayName='lgm-group'),  # noqa: E501
                u := store.create_user(identityStoreId='d-is-lgm', userName='lgm-user'),  # noqa: E501
                m := store.create_group_membership(identityStoreId='d-is-lgm', groupId=g['GroupId'],  # noqa: E501
                    memberId={'userId': u['UserId']}),
                {'identityStoreId': 'd-is-lgm', 'membershipId': m['MembershipId']}  # noqa: E501
            )[3],
            'ListGroupMemberships': lambda store: (
                g := store.create_group(identityStoreId='d-is-lgm2', displayName='lgm2-group'),  # noqa: E501
                {'identityStoreId': 'd-is-lgm2', 'groupId': g['GroupId']}
            )[1],
            'ListGroupMembershipsForMember': lambda store: (
                u := store.create_user(identityStoreId='d-is-lgmm', userName='lgmm-user'),  # noqa: E501
                {'identityStoreId': 'd-is-lgmm', 'memberId': {'userId': u['UserId']}}  # noqa: E501
            )[1],
            'GetGroupMembershipId': lambda store: (
                g := store.create_group(identityStoreId='d-is-ggmi', displayName='ggmi-group'),  # noqa: E501
                u := store.create_user(identityStoreId='d-is-ggmi', userName='ggmi-user'),  # noqa: E501
                store.create_group_membership(identityStoreId='d-is-ggmi', groupId=g['GroupId'],  # noqa: E501
                    memberId={'userId': u['UserId']}),
                {'identityStoreId': 'd-is-ggmi', 'groupId': g['GroupId'],
                 'memberId': {'userId': u['UserId']}}
            )[3],
            'IsMemberInGroups': lambda store: (
                g := store.create_group(identityStoreId='d-is-img', displayName='img-group'),  # noqa: E501
                u := store.create_user(identityStoreId='d-is-img', userName='img-user'),  # noqa: E501
                store.create_group_membership(identityStoreId='d-is-img', groupId=g['GroupId'],  # noqa: E501
                    memberId={'userId': u['UserId']}),
                {'identityStoreId': 'd-is-img', 'memberId': {'userId': u['UserId']},  # noqa: E501
                 'groupIds': [g['GroupId']]}
            )[3],
}
