# Test inputs for iot
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'iot.CreateThing': {'thingName': 'iot-test-thing'},
            'iot.CreateThingGroup': {'thingGroupName': 'iot-test-group'},
            'iot.CreateThingType': {'thingTypeName': 'iot-test-type'},
            'iot.CreatePolicy': {'policyName': 'iot-test-policy', 'policyDocument': '{"Version":"2012-10-17","Statement":[]}'},  # noqa: E501
            'iot.CreateKeysAndCertificate': {},
            'iot.ListThings': {},
            'iot.ListThingGroups': {},
            'iot.ListThingTypes': {},
            'iot.ListCertificates': {},
            'iot.ListPolicies': {},
            'iot.DescribeThing': lambda store: (
                store.create_thing(thingName='iot-desc-thing'),
                {'thingName': 'iot-desc-thing'}
            )[1],
            'iot.DescribeThingGroup': lambda store: (
                store.create_thing_group(thingGroupName='iot-desc-group'),
                {'thingGroupName': 'iot-desc-group'}
            )[1],
            'iot.DescribeThingType': lambda store: (
                store.create_thing_type(thingTypeName='iot-desc-type'),
                {'thingTypeName': 'iot-desc-type'}
            )[1],
            'iot.DescribeCertificate': lambda store: (
                c := store.create_keys_and_certificate(),
                {'certificateId': c['certificateId']}
            )[1],
            'iot.DescribePolicy': lambda store: (
                store.create_policy(policyName='iot-desc-policy', policyDocument='{"Version":"2012-10-17","Statement":[]}'),  # noqa: E501
                {'policyName': 'iot-desc-policy'}
            )[1],
            'iot.UpdateThing': lambda store: (
                store.create_thing(thingName='iot-upd-thing'),
                {'thingName': 'iot-upd-thing', 'thingTypeName': 'iot-test-type'}  # noqa: E501
            )[1],
            'iot.UpdateThingGroup': lambda store: (
                store.create_thing_group(thingGroupName='iot-upd-group'),
                {'thingGroupName': 'iot-upd-group', 'thingGroupProperties': {}}
            )[1],
            'iot.DeleteThing': lambda store: (
                store.create_thing(thingName='iot-del-thing'),
                {'thingName': 'iot-del-thing'}
            )[1],
            'iot.DeleteThingGroup': lambda store: (
                store.create_thing_group(thingGroupName='iot-del-group'),
                {'thingGroupName': 'iot-del-group'}
            )[1],
            'iot.DeleteThingType': lambda store: (
                store.create_thing_type(thingTypeName='iot-del-type'),
                {'thingTypeName': 'iot-del-type'}
            )[1],
            'iot.DeleteCertificate': lambda store: (
                c := store.create_keys_and_certificate(),
                {'certificateId': c['certificateId']}
            )[1],
            'iot.DeletePolicy': lambda store: (
                store.create_policy(policyName='iot-del-policy', policyDocument='{"Version":"2012-10-17","Statement":[]}'),  # noqa: E501
                {'policyName': 'iot-del-policy'}
            )[1],
}
