# Test inputs for iot-data
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'iot-data.GetThingShadow': lambda store: (store.update_thing_shadow('iot-test-thing', b'{"state":{}}'), {'thingName': 'iot-test-thing'})[1],  # noqa: E501
            'iot-data.UpdateThingShadow': {'thingName': 'iot-test-thing', 'payload': b'{"state":{"desired":{"color":"green"}}}'},  # noqa: E501
            'iot-data.DeleteThingShadow': lambda store: (store.update_thing_shadow('iot-test-del', b'{"state":{}}'), {'thingName': 'iot-test-del'})[1],  # noqa: E501
            'iot-data.ListNamedShadowsForThing': {'thingName': 'iot-test-thing'},  # noqa: E501
            'iot-data.GetRetainedMessage': lambda store: (store.__class__._retained.__setitem__('test/topic', {'topic': 'test/topic', 'payload': b'hello', 'qos': 1}), {'topic': 'test/topic'})[1],  # noqa: E501
            'iot-data.ListRetainedMessages': {},
            'iot-data.Publish': {'topic': 'test/topic', 'payload': b'hello', 'qos': 1},  # noqa: E501
            'iot-data.DeleteRetainedMessage': lambda store: (store.__class__._retained.__setitem__('test/del-topic', {'topic': 'test/del-topic', 'payload': b'hello', 'qos': 1}), {'topic': 'test/del-topic'})[1],  # noqa: E501
}
