# Test inputs for kafka
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateCluster': {'ClusterName': 'kafka-shape-test', 'NumberOfBrokerNodes': 1},  # noqa: E501
            'CreateClusterV2': {'ClusterName': 'kafka-shape-v2', 'NumberOfBrokerNodes': 1},  # noqa: E501
            'DescribeCluster': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-desc', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn']})[1],
            'DescribeClusterV2': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-descv2', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn']})[1],
            'ListClusters': {},
            'ListClustersV2': {},
            'DeleteCluster': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-del', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn']})[1],
            'GetBootstrapBrokers': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-bb', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn']})[1],
            'CreateTopic': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-topic', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn'], 'TopicName': 'shape-test-topic'})[1],  # noqa: E501
            'DescribeTopic': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-dtop', NumberOfBrokerNodes=1),  # noqa: E501
                store.create_topic(cluster['ClusterArn'], TopicName='desc-topic'),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn'], 'TopicName': 'desc-topic'})[2],  # noqa: E501
            'ListTopics': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-ltop', NumberOfBrokerNodes=1),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn']})[1],
            'DeleteTopic': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-deltop', NumberOfBrokerNodes=1),  # noqa: E501
                store.create_topic(cluster['ClusterArn'], TopicName='del-topic'),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn'], 'TopicName': 'del-topic'})[2],  # noqa: E501
            'UpdateTopic': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-updtop', NumberOfBrokerNodes=1),  # noqa: E501
                store.create_topic(cluster['ClusterArn'], TopicName='upd-topic'),  # noqa: E501
                {'ClusterArn': cluster['ClusterArn'], 'TopicName': 'upd-topic', 'NumPartitions': 3})[2],  # noqa: E501
            'CreateConfiguration': {'Name': 'kafka-shape-config', 'ServerProperties': 'test.prop=1'},  # noqa: E501
            'DescribeConfiguration': lambda store: (
                cfg := store.create_configuration(Name='kafka-desc-cfg', ServerProperties='sp'),  # noqa: E501
                {'Arn': cfg['Arn']})[1],
            'ListConfigurations': {},
            'DeleteConfiguration': lambda store: (
                cfg := store.create_configuration(Name='kafka-del-cfg', ServerProperties='sp'),  # noqa: E501
                {'Arn': cfg['Arn']})[1],
            'UpdateConfiguration': lambda store: (
                cfg := store.create_configuration(Name='kafka-upd-cfg', ServerProperties='sp'),  # noqa: E501
                {'Arn': cfg['Arn'], 'ServerProperties': 'updated.prop=2', 'Description': 'Updated config'})[1],  # noqa: E501
            'kafka.TagResource': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-tag', NumberOfBrokerNodes=1, Tags={'env': 'test'}),  # noqa: E501
                {'ResourceArn': cluster['ClusterArn'], 'Tags': {'env': 'test'}})[1],  # noqa: E501
            'kafka.UntagResource': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-utag', NumberOfBrokerNodes=1, Tags={'env': 'test'}),  # noqa: E501
                {'ResourceArn': cluster['ClusterArn'], 'TagKeys': ['env']})[1],
            'kafka.ListTagsForResource': lambda store: (
                cluster := store.create_cluster(ClusterName='kafka-ltag', NumberOfBrokerNodes=1, Tags={'env': 'test'}),  # noqa: E501
                {'ResourceArn': cluster['ClusterArn']})[1],
}
