# Test inputs for kendra
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateIndex': {'Name': 'test-idx', 'RoleArn': 'arn:aws:iam::000000000000:role/test'},  # noqa: E501
            'DescribeIndex': lambda store: (
                idx := store.create_index(Name='idx-desc', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'Id': idx['Id']}
            )[1],
            'ListIndices': {},
            'DeleteIndex': lambda store: (
                idx := store.create_index(Name='idx-del', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'Id': idx['Id']}
            )[1],
            'UpdateIndex': lambda store: (
                idx := store.create_index(Name='idx-upd', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'Id': idx['Id']}
            )[1],
            'CreateDataSource': lambda store: (
                idx := store.create_index(Name='idx-ds', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id'], 'Name': 'test-ds', 'Type': 'S3'}
            )[1],
            'DescribeDataSource': lambda store: (
                idx := store.create_index(Name='idx-dds', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                ds := store.create_data_source(IndexId=idx['Id'], Name='ds-desc', Type='S3'),  # noqa: E501
                {'Id': ds['Id'], 'IndexId': idx['Id']}
            )[2],
            'ListDataSources': lambda store: (
                idx := store.create_index(Name='idx-lds', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id']}
            )[1],
            'DeleteDataSource': lambda store: (
                idx := store.create_index(Name='idx-dds2', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                ds := store.create_data_source(IndexId=idx['Id'], Name='ds-del', Type='S3'),  # noqa: E501
                {'Id': ds['Id'], 'IndexId': idx['Id']}
            )[2],
            'UpdateDataSource': lambda store: (
                idx := store.create_index(Name='idx-uds', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                ds := store.create_data_source(IndexId=idx['Id'], Name='ds-upd', Type='S3'),  # noqa: E501
                {'Id': ds['Id'], 'IndexId': idx['Id']}
            )[2],
            'CreateFaq': lambda store: (
                idx := store.create_index(Name='idx-faq', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id'], 'Name': 'test-faq', 'S3Path': 's3://test/faq.csv',  # noqa: E501
                 'RoleArn': 'arn:aws:iam::000000000000:role/test'}
            )[1],
            'DescribeFaq': lambda store: (
                idx := store.create_index(Name='idx-dfq', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                faq := store.create_faq(IndexId=idx['Id'], Name='faq-desc', S3Path='s3://test/faq.csv',  # noqa: E501
                    RoleArn='arn:aws:iam::000000000000:role/test'),
                {'Id': faq['Id'], 'IndexId': idx['Id']}
            )[2],
            'ListFaqs': lambda store: (
                idx := store.create_index(Name='idx-lfq', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id']}
            )[1],
            'DeleteFaq': lambda store: (
                idx := store.create_index(Name='idx-dfq2', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                faq := store.create_faq(IndexId=idx['Id'], Name='faq-del', S3Path='s3://test/faq.csv',  # noqa: E501
                    RoleArn='arn:aws:iam::000000000000:role/test'),
                {'Id': faq['Id'], 'IndexId': idx['Id']}
            )[2],
            'CreateThesaurus': lambda store: (
                idx := store.create_index(Name='idx-ths', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id'], 'Name': 'test-thes', 'RoleArn': 'arn:aws:iam::000000000000:role/test',  # noqa: E501
                 'SourceS3Path': 's3://test/thesaurus.txt'}
            )[1],
            'DescribeThesaurus': lambda store: (
                idx := store.create_index(Name='idx-dth', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                ths := store.create_thesaurus(IndexId=idx['Id'], Name='ths-desc',  # noqa: E501
                    RoleArn='arn:aws:iam::000000000000:role/test', SourceS3Path='s3://test/thesaurus.txt'),  # noqa: E501
                {'Id': ths['Id'], 'IndexId': idx['Id']}
            )[2],
            'ListThesauri': lambda store: (
                idx := store.create_index(Name='idx-lth', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id']}
            )[1],
            'DeleteThesaurus': lambda store: (
                idx := store.create_index(Name='idx-dth2', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                ths := store.create_thesaurus(IndexId=idx['Id'], Name='ths-del',  # noqa: E501
                    RoleArn='arn:aws:iam::000000000000:role/test', SourceS3Path='s3://test/thesaurus.txt'),  # noqa: E501
                {'Id': ths['Id'], 'IndexId': idx['Id']}
            )[2],
            'CreateExperience': lambda store: (
                idx := store.create_index(Name='idx-exp', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id'], 'Name': 'test-exp'}
            )[1],
            'DescribeExperience': lambda store: (
                idx := store.create_index(Name='idx-dex', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                exp := store.create_experience(IndexId=idx['Id'], Name='exp-desc'),  # noqa: E501
                {'Id': exp['Id'], 'IndexId': idx['Id']}
            )[2],
            'ListExperiences': lambda store: (
                idx := store.create_index(Name='idx-lex', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id']}
            )[1],
            'DeleteExperience': lambda store: (
                idx := store.create_index(Name='idx-dex2', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                exp := store.create_experience(IndexId=idx['Id'], Name='exp-del'),  # noqa: E501
                {'Id': exp['Id'], 'IndexId': idx['Id']}
            )[2],
            'Query': lambda store: (
                idx := store.create_index(Name='idx-query', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'IndexId': idx['Id'], 'QueryText': 'test query'}
            )[1],
            'kendra.TagResource': lambda store: (
                idx := store.create_index(Name='idx-tag', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'ResourceARN': 'arn:aws:kendra:us-east-1:000000000000:index/' + idx['Id'],  # noqa: E501
                 'Tags': [{'Key': 'env', 'Value': 'test'}]}
            )[1],
            'kendra.UntagResource': lambda store: (
                idx := store.create_index(Name='idx-utag', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'ResourceARN': 'arn:aws:kendra:us-east-1:000000000000:index/' + idx['Id'],  # noqa: E501
                 'TagKeys': ['env']}
            )[1],
            'kendra.ListTagsForResource': lambda store: (
                idx := store.create_index(Name='idx-ltags', RoleArn='arn:aws:iam::000000000000:role/test'),  # noqa: E501
                {'ResourceARN': 'arn:aws:kendra:us-east-1:000000000000:index/' + idx['Id']}  # noqa: E501
            )[1],
}
