# Test inputs for keyspaces
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateKeyspace': {'keyspaceName': 'ks-create'},
            'GetKeyspace': lambda store: (
                store.create_keyspace('ks-get'),
                {'keyspaceName': 'ks-get'}
            )[1],
            'ListKeyspaces': {},
            'DeleteKeyspace': lambda store: (
                store.create_keyspace('ks-del'),
                {'keyspaceName': 'ks-del'}
            )[1],
            'UpdateKeyspace': lambda store: (
                store.create_keyspace('ks-upd'),
                {'keyspaceName': 'ks-upd'}
            )[1],
            'CreateTable': lambda store: (
                store.create_keyspace('ks-ctbl'),
                {'keyspaceName': 'ks-ctbl', 'tableName': 'test-table',
                 'schemaDefinition': {'allColumns': [{'name': 'id', 'type': 'int'}, {'name': 'val', 'type': 'text'}], 'partitionKeys': [{'name': 'id'}]}}  # noqa: E501
            )[1],
            'GetTable': lambda store: (
                store.create_keyspace('ks-gtbl'),
                store.create_table('ks-gtbl', 'test-table', schemaDefinition={'allColumns': [{'name': 'id', 'type': 'int'}], 'partitionKeys': [{'name': 'id'}]}),  # noqa: E501
                {'keyspaceName': 'ks-gtbl', 'tableName': 'test-table'}
            )[2],
            'ListTables': lambda store: (
                store.create_keyspace('ks-ltbl'),
                {'keyspaceName': 'ks-ltbl'}
            )[1],
            'DeleteTable': lambda store: (
                store.create_keyspace('ks-dtbl'),
                store.create_table('ks-dtbl', 'test-table', schemaDefinition={'allColumns': [{'name': 'id', 'type': 'int'}], 'partitionKeys': [{'name': 'id'}]}),  # noqa: E501
                {'keyspaceName': 'ks-dtbl', 'tableName': 'test-table'}
            )[2],
            'UpdateTable': lambda store: (
                store.create_keyspace('ks-utbl'),
                store.create_table('ks-utbl', 'test-table', schemaDefinition={'allColumns': [{'name': 'id', 'type': 'int'}], 'partitionKeys': [{'name': 'id'}]}),  # noqa: E501
                {'keyspaceName': 'ks-utbl', 'tableName': 'test-table'}
            )[2],
            'CreateType': lambda store: (
                store.create_keyspace('ks-ctyp'),
                {'keyspaceName': 'ks-ctyp', 'typeName': 'address',
                 'fieldDefinitions': [{'name': 'street', 'type': 'text'}, {'name': 'city', 'type': 'text'}]}  # noqa: E501
            )[1],
            'GetType': lambda store: (
                store.create_keyspace('ks-gtyp'),
                store.create_type('ks-gtyp', 'address', fieldDefinitions=[{'name': 'street', 'type': 'text'}]),  # noqa: E501
                {'keyspaceName': 'ks-gtyp', 'typeName': 'address'}
            )[2],
            'ListTypes': lambda store: (
                store.create_keyspace('ks-ltyp'),
                {'keyspaceName': 'ks-ltyp'}
            )[1],
            'DeleteType': lambda store: (
                store.create_keyspace('ks-dtyp'),
                store.create_type('ks-dtyp', 'address', fieldDefinitions=[{'name': 'street', 'type': 'text'}]),  # noqa: E501
                {'keyspaceName': 'ks-dtyp', 'typeName': 'address'}
            )[2],
            'GetTableAutoScalingSettings': lambda store: (
                store.create_keyspace('ks-as'),
                store.create_table('ks-as', 'test-table', schemaDefinition={'allColumns': [{'name': 'id', 'type': 'int'}], 'partitionKeys': [{'name': 'id'}]}),  # noqa: E501
                {'keyspaceName': 'ks-as', 'tableName': 'test-table'}
            )[2],
            'keyspaces.TagResource': lambda store: (
                ks := store.create_keyspace('ks-tag'),
                {'resourceArn': ks['resourceArn'], 'tags': [{'key': 'env', 'value': 'test'}]}  # noqa: E501
            )[1],
            'keyspaces.UntagResource': lambda store: (
                ks := store.create_keyspace('ks-utag'),
                {'resourceArn': ks['resourceArn'], 'tags': [{'key': 'env', 'value': 'test'}]}  # noqa: E501
            )[1],
            'keyspaces.ListTagsForResource': lambda store: (
                ks := store.create_keyspace('ks-ltag'),
                {'resourceArn': ks['resourceArn']}
            )[1],
}
