# Test inputs for kinesis
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'kinesis.CreateStream': {'StreamName': 'kin-test-stream', 'ShardCount': 1},  # noqa: E501
            'kinesis.TagStream': lambda store: (
                store.create_stream('kin-tag-stream'),
                {'StreamName': 'kin-tag-stream', 'Tags': {'env': 'test'}}
            )[1],
            'kinesis.PutRecord': lambda store: (
                store.create_stream('kin-pr-stream'),
                {'StreamName': 'kin-pr-stream', 'Data': 'test-data', 'PartitionKey': 'pk-1'}  # noqa: E501
            )[1],
            'kinesis.PutRecords': lambda store: (
                store.create_stream('kin-prs-stream'),
                {'StreamName': 'kin-prs-stream', 'Records': [{'Data': 'd1', 'PartitionKey': 'pk-1'}, {'Data': 'd2', 'PartitionKey': 'pk-2'}]}  # noqa: E501
            )[1],
            'kinesis.ListStreams': {},
            'kinesis.ListTagsForStream': lambda store: (
                store.create_stream('kin-lt-stream'),
                {'StreamName': 'kin-lt-stream'}
            )[1],
            'kinesis.DescribeStream': lambda store: (
                store.create_stream('kin-desc-stream'),
                {'StreamName': 'kin-desc-stream'}
            )[1],
            'kinesis.GetRecords': lambda store: (
                store.create_stream('kin-gr-stream'),
                si := store.get_shard_iterator('kin-gr-stream', 'shardId-0', 'TRIM_HORIZON'),  # noqa: E501
                {'ShardIterator': si['ShardIterator']}
            )[2],
            'kinesis.GetShardIterator': lambda store: (
                store.create_stream('kin-gsi-stream'),
                {'StreamName': 'kin-gsi-stream', 'ShardId': 'shardId-0', 'ShardIteratorType': 'TRIM_HORIZON'}  # noqa: E501
            )[1],
            'kinesis.DeleteStream': lambda store: (
                store.create_stream('kin-del-stream'),
                {'StreamName': 'kin-del-stream'}
            )[1],
            'kinesis.RemoveTagsFromStream': lambda store: (
                store.create_stream('kin-rt-stream'),
                {'StreamName': 'kin-rt-stream', 'TagKeys': ['test']}
            )[1],
}
