# Test inputs for lexv2-runtime
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'PutSession': {'botId': 'test-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                'sessionId': 'test-session', 'sessionState': {'dialogAction': {'type': 'Close'}}},  # noqa: E501
            'GetSession': lambda store: (
                store.put_session(botId='l2-gs-bot', botAliasId='TSTALIAS', localeId='en_US',  # noqa: E501
                    sessionId='gs-sess'),
                {'botId': 'l2-gs-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                 'sessionId': 'gs-sess'}
            )[1],
            'DeleteSession': lambda store: (
                store.put_session(botId='l2-ds-bot', botAliasId='TSTALIAS', localeId='en_US',  # noqa: E501
                    sessionId='ds-sess'),
                {'botId': 'l2-ds-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                 'sessionId': 'ds-sess'}
            )[1],
            'RecognizeText': {'botId': 'test-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                'sessionId': 'rt-sess', 'text': 'hello'},
            'RecognizeUtterance': {'botId': 'test-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                'sessionId': 'ru-sess'},
            'StartConversation': {'botId': 'test-bot', 'botAliasId': 'TSTALIAS', 'localeId': 'en_US',  # noqa: E501
                'sessionId': 'sc-sess'},
}
