# Test inputs for lexv2-models
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateBot': {'botName': 'test-bot', 'roleArn': 'arn:aws:iam::123456789012:role/test',  # noqa: E501
                          'dataPrivacy': {'childDirected': False}, 'idleSessionTTLInSeconds': 300},  # noqa: E501
            'CreateBotAlias': lambda store: (
                store.create_bot(botName='balias-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'botAliasName': 'test-alias', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT'})[2],
            'CreateIntent': lambda store: (
                store.create_bot(botName='intent-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'intentName': 'TestIntent', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US',
                 'sampleUtterances': [{'utterance': 'hello'}]})[2],
            'CreateSlotType': lambda store: (
                store.create_bot(botName='slot-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'slotTypeName': 'TestSlotType', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[2],
            'ListBots': {},
            'ListBotAliases': lambda store: (
                store.create_bot(botName='lba-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_bot_alias(botAliasName='lba-alias', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT'),
                {'botId': store.list_bots()[0]['botId']})[3],
            'ListIntents': lambda store: (
                store.create_bot(botName='li-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_intent(intentName='li-intent', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                    botVersion='DRAFT', localeId='en_US',
                                    sampleUtterances=[{'utterance': 'hello'}]),
                {'botId': store.list_bots()[0]['botId'], 'botVersion': 'DRAFT',
                 'localeId': 'en_US'})[3],
            'ListSlotTypes': lambda store: (
                store.create_bot(botName='ls-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_slot_type(slotTypeName='ls-slot', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT', localeId='en_US'),
                {'botId': store.list_bots()[0]['botId'], 'botVersion': 'DRAFT',
                 'localeId': 'en_US'})[3],
            'DescribeBot': lambda store: (
                store.create_bot(botName='desc-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'botId': store.list_bots()[0]['botId']})[2],
            'DescribeBotAlias': lambda store: (
                store.create_bot(botName='dba-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_bot_alias(botAliasName='dba-alias', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT'),
                {'botId': store.list_bots()[0]['botId'],
                 'botAliasName': 'dba-alias'})[3],
            'DescribeIntent': lambda store: (
                store.create_bot(botName='di-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_intent(intentName='di-intent', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                    botVersion='DRAFT', localeId='en_US',
                                    sampleUtterances=[{'utterance': 'hello'}]),
                {'intentName': 'di-intent', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[3],
            'DescribeSlotType': lambda store: (
                store.create_bot(botName='ds-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_slot_type(slotTypeName='ds-slot', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT', localeId='en_US'),
                {'slotTypeName': 'ds-slot', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[3],
            'DeleteBot': lambda store: (
                store.create_bot(botName='del-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'botId': store.list_bots()[0]['botId']})[2],
            'DeleteBotAlias': lambda store: (
                store.create_bot(botName='delba-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_bot_alias(botAliasName='delba-alias', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT'),
                {'botId': store.list_bots()[0]['botId'],
                 'botAliasName': 'delba-alias'})[3],
            'DeleteIntent': lambda store: (
                store.create_bot(botName='deli-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_intent(intentName='deli-intent', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                    botVersion='DRAFT', localeId='en_US',
                                    sampleUtterances=[{'utterance': 'hello'}]),
                {'intentName': 'deli-intent', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[3],
            'DeleteSlotType': lambda store: (
                store.create_bot(botName='dels-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_slot_type(slotTypeName='dels-slot', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT', localeId='en_US'),
                {'slotTypeName': 'dels-slot', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[3],
            'UpdateBot': lambda store: (
                store.create_bot(botName='upd-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                {'botId': store.list_bots()[0]['botId'], 'botName': 'upd-bot',
                 'roleArn': 'arn:aws:iam::123456789012:role/test',
                 'dataPrivacy': {'childDirected': False},
                 'idleSessionTTLInSeconds': 600})[2],
            'UpdateBotAlias': lambda store: (
                store.create_bot(botName='uba-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_bot_alias(botAliasName='uba-alias', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT'),
                {'botAliasName': 'uba-alias', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT'})[3],
            'UpdateIntent': lambda store: (
                store.create_bot(botName='ui-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_intent(intentName='ui-intent', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                    botVersion='DRAFT', localeId='en_US',
                                    sampleUtterances=[{'utterance': 'hello'}]),
                {'intentName': 'ui-intent', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US',
                 'sampleUtterances': [{'utterance': 'hi there'}]})[3],
            'UpdateSlotType': lambda store: (
                store.create_bot(botName='us-bot', roleArn='arn:aws:iam::123456789012:role/test',  # noqa: E501
                                 dataPrivacy={'childDirected': False}, idleSessionTTLInSeconds=300),  # noqa: E501
                store.list_bots(),
                store.create_slot_type(slotTypeName='us-slot', botId=store.list_bots()[0]['botId'],  # noqa: E501
                                       botVersion='DRAFT', localeId='en_US'),
                {'slotTypeName': 'us-slot', 'botId': store.list_bots()[0]['botId'],  # noqa: E501
                 'botVersion': 'DRAFT', 'localeId': 'en_US'})[3],
}
