# Test inputs for mediaconvert
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'mediaconvert.CreateJob': {'Role': 'arn:aws:iam::000000000000:role/mc-test', 'Settings': {'OutputGroups': []}},  # noqa: E501
            'mediaconvert.CreateJobTemplate': {'Name': 'mc-test-template', 'Settings': {'OutputGroups': []}},  # noqa: E501
            'mediaconvert.CreatePreset': {'Name': 'mc-test-preset', 'Settings': {'ContainerSettings': {'Container': 'MP4'}}},  # noqa: E501
            'mediaconvert.CreateQueue': {'Name': 'mc-test-queue'},
            'mediaconvert.ListJobs': {},
            'mediaconvert.ListJobTemplates': {},
            'mediaconvert.ListPresets': {},
            'mediaconvert.ListQueues': {},
            'mediaconvert.GetJob': lambda store: (
                job := JobRecord(id='mc-get-job', role='arn:aws:iam::000000000000:role/mc-test', settings={'OutputGroups': []}),  # noqa: E501
                store.jobs.__setitem__(job.id, job),
                {'Id': job.id}
            )[2],
            'mediaconvert.GetJobTemplate': lambda store: (
                tmpl := JobTemplateRecord(name='mc-get-template', settings={'OutputGroups': []}),  # noqa: E501
                store.job_templates.__setitem__(tmpl.name, tmpl),
                {'Name': tmpl.name}
            )[2],
            'mediaconvert.GetPreset': lambda store: (
                preset := PresetRecord(name='mc-get-preset', settings={}),
                store.presets.__setitem__(preset.name, preset),
                {'Name': preset.name}
            )[2],
            'mediaconvert.GetQueue': lambda store: (
                q := QueueRecord(name='mc-get-queue'),
                store.queues.__setitem__(q.name, q),
                {'Name': q.name}
            )[2],
            'mediaconvert.DeleteJobTemplate': lambda store: (
                tmpl := JobTemplateRecord(name='mc-del-template', settings={'OutputGroups': []}),  # noqa: E501
                store.job_templates.__setitem__(tmpl.name, tmpl),
                {'Name': tmpl.name}
            )[2],
            'mediaconvert.DeletePreset': lambda store: (
                preset := PresetRecord(name='mc-del-preset', settings={}),
                store.presets.__setitem__(preset.name, preset),
                {'Name': preset.name}
            )[2],
            'mediaconvert.DeleteQueue': lambda store: (
                q := QueueRecord(name='mc-del-queue'),
                store.queues.__setitem__(q.name, q),
                {'Name': q.name}
            )[2],
            'mediaconvert.CancelJob': lambda store: (
                job := JobRecord(id='mc-cancel-job', role='arn:aws:iam::000000000000:role/mc-test', settings={'OutputGroups': []}),  # noqa: E501
                store.jobs.__setitem__(job.id, job),
                {'Id': job.id}
            )[2],
            'mediaconvert.UpdateJobTemplate': lambda store: (
                tmpl := JobTemplateRecord(name='mc-upd-template', settings={'OutputGroups': []}),  # noqa: E501
                store.job_templates.__setitem__(tmpl.name, tmpl),
                {'Name': tmpl.name, 'Settings': {'OutputGroups': []}, 'Description': 'updated'}  # noqa: E501
            )[2],
            'mediaconvert.UpdatePreset': lambda store: (
                preset := PresetRecord(name='mc-upd-preset', settings={}),
                store.presets.__setitem__(preset.name, preset),
                {'Name': preset.name, 'Settings': {}}
            )[2],
            'mediaconvert.UpdateQueue': lambda store: (
                q := QueueRecord(name='mc-upd-queue'),
                store.queues.__setitem__(q.name, q),
                {'Name': q.name, 'Description': 'updated'}
            )[2],
            'mediaconvert.TagResource': lambda store: (
                q := QueueRecord(name='mc-tag-queue'),
                store.queues.__setitem__(q.name, q),
                {'Arn': 'arn:aws:mediaconvert:us-east-1:000000000000:queue/mc-tag-queue', 'Tags': {'test': 'val'}}  # noqa: E501
            )[2],
}
