# Test inputs for memorydb
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateCluster': {'ClusterName': 'test-cluster', 'NodeType': 'db.r6gd.xlarge',  # noqa: E501
                               'ACLName': 'open-access'},
            'CreateACL': {'ACLName': 'test-acl'},
            'CreateUser': {'UserName': 'test-user',
                            'AuthenticationMode': {'Type': 'password', 'Passwords': ['Test1234!']}},  # noqa: E501
            'CreateParameterGroup': {'ParameterGroupName': 'test-pg', 'Family': 'memorydb_redis7'},  # noqa: E501
            'CreateSubnetGroup': {'SubnetGroupName': 'test-sg', 'SubnetIds': ['subnet-abc123']},  # noqa: E501
            'CreateSnapshot': lambda store: (
                store.create_cluster(ClusterName='mem-snap-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                {'SnapshotName': 'test-snap', 'ClusterName': 'mem-snap-cluster'})[1],  # noqa: E501
            'DescribeClusters': {},
            'DescribeACLs': {},
            'DescribeUsers': {},
            'DescribeParameterGroups': {},
            'DescribeSubnetGroups': {},
            'DescribeSnapshots': {},
            'DeleteCluster': lambda store: (
                store.create_cluster(ClusterName='mem-del-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                {'ClusterName': 'mem-del-cluster'})[1],
            'DeleteACL': lambda store: (
                store.create_acl(ACLName='mem-del-acl'),
                {'ACLName': 'mem-del-acl'})[1],
            'DeleteUser': lambda store: (
                store.create_user(UserName='mem-del-user',
                                  AuthenticationMode={'Type': 'password', 'Passwords': ['Test1234!']}),  # noqa: E501
                {'UserName': 'mem-del-user'})[1],
            'DeleteParameterGroup': lambda store: (
                store.create_parameter_group(ParameterGroupName='mem-del-pg', Family='memorydb_redis7'),  # noqa: E501
                {'ParameterGroupName': 'mem-del-pg'})[1],
            'DeleteSubnetGroup': lambda store: (
                store.create_subnet_group(SubnetGroupName='mem-del-sg', SubnetIds=['subnet-abc123']),  # noqa: E501
                {'SubnetGroupName': 'mem-del-sg'})[1],
            'DeleteSnapshot': lambda store: (
                store.create_cluster(ClusterName='mem-ds-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                store.create_snapshot(SnapshotName='mem-del-snap', ClusterName='mem-ds-cluster'),  # noqa: E501
                {'SnapshotName': 'mem-del-snap'})[2],
            'UpdateCluster': lambda store: (
                store.create_cluster(ClusterName='mem-upd-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                {'ClusterName': 'mem-upd-cluster', 'Description': 'Updated cluster'})[1],  # noqa: E501
            'UpdateACL': lambda store: (
                store.create_acl(ACLName='mem-upd-acl'),
                {'ACLName': 'mem-upd-acl', 'UserNames': ['test-user']})[1],
            'UpdateUser': lambda store: (
                store.create_user(UserName='mem-upd-user',
                                  AuthenticationMode={'Type': 'password', 'Passwords': ['Test1234!']}),  # noqa: E501
                {'UserName': 'mem-upd-user', 'AccessString': 'off ~*'})[1],
            'UpdateParameterGroup': lambda store: (
                store.create_parameter_group(ParameterGroupName='mem-upd-pg', Family='memorydb_redis7'),  # noqa: E501
                {'ParameterGroupName': 'mem-upd-pg', 'Description': 'Updated PG'})[1],  # noqa: E501
            'UpdateSubnetGroup': lambda store: (
                store.create_subnet_group(SubnetGroupName='mem-upd-sg', SubnetIds=['subnet-abc123']),  # noqa: E501
                {'SubnetGroupName': 'mem-upd-sg', 'Description': 'Updated SG'})[1],  # noqa: E501
            'ResetParameterGroup': lambda store: (
                store.create_parameter_group(ParameterGroupName='mem-rst-pg', Family='memorydb_redis7'),  # noqa: E501
                {'ParameterGroupName': 'mem-rst-pg'})[1],
            'ListTags': lambda store: (
                store.create_cluster(ClusterName='mem-lt-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                cl := store.describe_clusters('mem-lt-cluster'),
                {'ResourceArn': cl['Clusters'][0]['ARN']})[2],
            'memorydb.TagResource': lambda store: (
                store.create_cluster(ClusterName='mem-tr-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                cl := store.describe_clusters('mem-tr-cluster'),
                {'ResourceArn': cl['Clusters'][0]['ARN'],
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[2],
            'memorydb.UntagResource': lambda store: (
                store.create_cluster(ClusterName='mem-utr-cluster', NodeType='db.r6gd.xlarge',  # noqa: E501
                                     ACLName='open-access'),
                cl := store.describe_clusters('mem-utr-cluster'),
                {'ResourceArn': cl['Clusters'][0]['ARN'],
                 'TagKeys': ['env']})[2],
}
