# Test inputs for mq
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateBroker': {'BrokerName': 'mq-shape-test', 'EngineType': 'ACTIVEMQ'},  # noqa: E501
            'ListBrokers': {},
            'DescribeBroker': lambda store: (
                broker := store.create_broker(BrokerName='mq-desc', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId']})[1],
            'DeleteBroker': lambda store: (
                broker := store.create_broker(BrokerName='mq-del', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId']})[1],
            'UpdateBroker': lambda store: (
                broker := store.create_broker(BrokerName='mq-upd', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId'], 'AutoMinorVersionUpgrade': False})[1],  # noqa: E501
            'RebootBroker': lambda store: (
                broker := store.create_broker(BrokerName='mq-reboot', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId']})[1],
            'CreateConfiguration': {'Name': 'mq-shape-config', 'EngineType': 'ACTIVEMQ', 'EngineVersion': '5.17.6'},  # noqa: E501
            'ListConfigurations': {},
            'DescribeConfiguration': lambda store: (
                cfg := store.create_configuration(Name='mq-desc-cfg', EngineType='ACTIVEMQ', EngineVersion='5.17.6'),  # noqa: E501
                {'ConfigurationId': cfg['Id']})[1],
            'DeleteConfiguration': lambda store: (
                cfg := store.create_configuration(Name='mq-del-cfg', EngineType='ACTIVEMQ', EngineVersion='5.17.6'),  # noqa: E501
                {'ConfigurationId': cfg['Id']})[1],
            'UpdateConfiguration': lambda store: (
                cfg := store.create_configuration(Name='mq-upd-cfg', EngineType='ACTIVEMQ', EngineVersion='5.17.6'),  # noqa: E501
                {'ConfigurationId': cfg['Id'], 'Data': 'updated', 'Description': 'Updated'})[1],  # noqa: E501
            'DescribeConfigurationRevision': lambda store: (
                cfg := store.create_configuration(Name='mq-rev-cfg', EngineType='ACTIVEMQ', EngineVersion='5.17.6'),  # noqa: E501
                {'ConfigurationId': cfg['Id'], 'ConfigurationRevision': 1})[1],
            'CreateUser': lambda store: (
                broker := store.create_broker(BrokerName='mq-user-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId'], 'Username': 'test-user'})[1],
            'ListUsers': lambda store: (
                broker := store.create_broker(BrokerName='mq-lu-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                {'BrokerId': broker['BrokerId']})[1],
            'DescribeUser': lambda store: (
                broker := store.create_broker(BrokerName='mq-du-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                store.create_user(broker['BrokerId'], 'desc-user'),
                {'BrokerId': broker['BrokerId'], 'Username': 'desc-user'})[2],
            'DeleteUser': lambda store: (
                broker := store.create_broker(BrokerName='mq-delusr-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                store.create_user(broker['BrokerId'], 'del-user'),
                {'BrokerId': broker['BrokerId'], 'Username': 'del-user'})[2],
            'UpdateUser': lambda store: (
                broker := store.create_broker(BrokerName='mq-updusr-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                store.create_user(broker['BrokerId'], 'upd-user'),
                {'BrokerId': broker['BrokerId'], 'Username': 'upd-user', 'Groups': ['admin']})[2],  # noqa: E501
            'mq.CreateTags': lambda store: (
                broker := store.create_broker(BrokerName='mq-tag-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                {'ResourceArn': broker['BrokerArn'], 'Tags': {'env': 'test'}})[1],  # noqa: E501
            'mq.DeleteTags': lambda store: (
                broker := store.create_broker(BrokerName='mq-dtag-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                store.create_tags(broker['BrokerArn'], {'env': 'test'}),
                {'ResourceArn': broker['BrokerArn'], 'TagKeys': ['env']})[2],
            'mq.ListTags': lambda store: (
                broker := store.create_broker(BrokerName='mq-ltag-broker', EngineType='ACTIVEMQ'),  # noqa: E501
                store.create_tags(broker['BrokerArn'], {'env': 'test'}),
                {'ResourceArn': broker['BrokerArn']})[2],
}
