# Test inputs for neptune
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDBCluster': {'DBClusterIdentifier': 'neptune-test-cluster', 'Engine': 'neptune'},  # noqa: E501
            'CreateDBClusterParameterGroup': {'DBClusterParameterGroupName': 'neptune-test-cpg',  # noqa: E501
                                              'DBParameterGroupFamily': 'neptune1', 'Description': 'test'},  # noqa: E501
            'CreateDBClusterSnapshot': lambda store: (
                store.create_cluster('s-snap-cluster', 'neptune'),
                {'DBClusterSnapshotIdentifier': 's-test-snapshot',
                 'DBClusterIdentifier': 's-snap-cluster'})[1],
            'CreateDBInstance': {'DBInstanceIdentifier': 'neptune-test-instance',  # noqa: E501
                                 'DBInstanceClass': 'db.r5.large', 'Engine': 'neptune',  # noqa: E501
                                 'DBClusterIdentifier': 'neptune-test-cluster'},  # noqa: E501
            'CreateDBParameterGroup': {'DBParameterGroupName': 'neptune-test-pg',  # noqa: E501
                                       'DBParameterGroupFamily': 'neptune1', 'Description': 'test'},  # noqa: E501
            'CreateDBSubnetGroup': {'DBSubnetGroupName': 'neptune-test-sg',
                                    'DBSubnetGroupDescription': 'test subnet group',  # noqa: E501
                                    'SubnetIds': ['subnet-a', 'subnet-b']},
            'DescribeDBClusters': {},
            'DescribeDBInstances': {},
            'DescribeDBClusterParameterGroups': {},
            'DescribeDBClusterSnapshots': {},
            'DescribeDBEngineVersions': {},
            'DescribeDBParameterGroups': {},
            'DescribeDBSubnetGroups': {},
            'DescribeDBClusterParameters': lambda store: (
                store.create_cluster_param_group('s-desc-cpgp', 'neptune1', 'test'),  # noqa: E501
                {'DBClusterParameterGroupName': 's-desc-cpgp'})[1],
            'DescribeDBParameters': lambda store: (
                store.create_param_group('s-desc-pgp', 'neptune1', 'test'),
                {'DBParameterGroupName': 's-desc-pgp'})[1],
            'DeleteDBCluster': lambda store: (
                store.create_cluster('s-del-cluster', 'neptune', status='available'),  # noqa: E501
                {'DBClusterIdentifier': 's-del-cluster', 'SkipFinalSnapshot': True})[1],  # noqa: E501
            'DeleteDBClusterParameterGroup': lambda store: (
                store.create_cluster_param_group('s-del-cpg', 'neptune1', 'test'),  # noqa: E501
                {'DBClusterParameterGroupName': 's-del-cpg'})[1],
            'DeleteDBClusterSnapshot': lambda store: (
                store.create_cluster('s-del-snap-cluster', 'neptune', status='available'),  # noqa: E501
                store.create_snapshot('s-del-snapshot', 's-del-snap-cluster'),
                {'DBClusterSnapshotIdentifier': 's-del-snapshot'})[2],
            'DeleteDBInstance': lambda store: (
                store.create_cluster('s-del-inst-cluster', 'neptune', status='available'),  # noqa: E501
                store.create_instance('s-del-instance', 'db.r5.large', 'neptune', 's-del-inst-cluster', status='available'),  # noqa: E501
                {'DBInstanceIdentifier': 's-del-instance', 'SkipFinalSnapshot': True})[2],  # noqa: E501
            'DeleteDBParameterGroup': lambda store: (
                store.create_param_group('s-del-pg', 'neptune1', 'test'),
                {'DBParameterGroupName': 's-del-pg'})[1],
            'DeleteDBSubnetGroup': lambda store: (
                store.create_subnet_group('s-del-sg', 'test', ['subnet-a']),
                {'DBSubnetGroupName': 's-del-sg'})[1],
            'ModifyDBCluster': lambda store: (
                store.create_cluster('s-mod-cluster', 'neptune', status='available'),  # noqa: E501
                {'DBClusterIdentifier': 's-mod-cluster', 'Port': 8182})[1],
            'ModifyDBClusterParameterGroup': lambda store: (
                store.create_cluster_param_group('s-mod-cpg', 'neptune1', 'test'),  # noqa: E501
                {'DBClusterParameterGroupName': 's-mod-cpg'})[1],
            'ModifyDBInstance': lambda store: (
                store.create_cluster('s-mod-inst-cluster', 'neptune', status='available'),  # noqa: E501
                store.create_instance('s-mod-instance', 'db.r5.large', 'neptune', 's-mod-inst-cluster'),  # noqa: E501
                {'DBInstanceIdentifier': 's-mod-instance', 'DBInstanceClass': 'db.r5.large'})[2],  # noqa: E501
            'ModifyDBParameterGroup': lambda store: (
                store.create_param_group('s-mod-pg', 'neptune1', 'test'),
                {'DBParameterGroupName': 's-mod-pg'})[1],
            'RebootDBInstance': lambda store: (
                store.create_cluster('s-reboot-cluster', 'neptune', status='available'),  # noqa: E501
                store.create_instance('s-reboot-instance', 'db.r5.large', 'neptune', 's-reboot-cluster'),  # noqa: E501
                {'DBInstanceIdentifier': 's-reboot-instance'})[2],
            'neptune.AddTagsToResource': lambda store: (
                store.create_cluster('s-tag-cluster', 'neptune', status='available'),  # noqa: E501
                {'ResourceName': 's-tag-cluster',
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'neptune.RemoveTagsFromResource': lambda store: (
                store.create_cluster('s-untag-cluster', 'neptune', status='available'),  # noqa: E501
                {'ResourceName': 's-untag-cluster',
                 'TagKeys': ['env']})[1],
            'neptune.ListTagsForResource': lambda store: (
                store.create_cluster('s-ltf-cluster', 'neptune', status='available'),  # noqa: E501
                {'ResourceName': 's-ltf-cluster'})[1],
}
