# Test inputs for network-firewall
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateFirewallPolicy': {'FirewallPolicyName': 'test-fw-policy', 'FirewallPolicy': {'StatelessDefaultActions': ['aws:forward_to_sfe'], 'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}},  # noqa: E501
            'CreateFirewall': lambda store: (
                fp := store.create_firewall_policy(FirewallPolicyName='test-fw', FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'], 'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                {'FirewallName': 'test-fw', 'FirewallPolicyArn': fp['FirewallPolicyResponse']['FirewallPolicyArn'], 'VpcId': 'vpc-12345', 'SubnetMappings': [{'SubnetId': 'subnet-123'}]})[1],  # noqa: E501
            'CreateRuleGroup': {'RuleGroupName': 'test-rg', 'Type': 'STATELESS', 'Capacity': 100},  # noqa: E501
            'ListFirewalls': {},
            'ListFirewallPolicies': {},
            'ListRuleGroups': {},
            'DescribeFirewall': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-desc-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-desc-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn})[2],
            'DescribeFirewallPolicy': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-desc-pol',
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                {'FirewallPolicyArn': store.policies()[-1].FirewallPolicyArn})[1],  # noqa: E501
            'DescribeFirewallMetadata': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-meta-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-meta-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn})[2],
            'DescribeRuleGroup': lambda store: (
                store.create_rule_group(RuleGroupName='nfw-desc-rg', Type='STATELESS',  # noqa: E501
                    Capacity=100, RuleGroup={'RulesSource': {}}),
                {'RuleGroupArn': store.rule_groups()[-1].RuleGroupArn})[1],
            'DeleteFirewall': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-del-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-del-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn})[2],
            'DeleteFirewallPolicy': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-del-pol',
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                {'FirewallPolicyArn': store.policies()[-1].FirewallPolicyArn})[1],  # noqa: E501
            'DeleteRuleGroup': lambda store: (
                store.create_rule_group(RuleGroupName='nfw-del-rg', Type='STATELESS',  # noqa: E501
                    Capacity=100, RuleGroup={'RulesSource': {}}),
                {'RuleGroupArn': store.rule_groups()[-1].RuleGroupArn})[1],
            'network-firewall.TagResource': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-tag-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-tag-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'ResourceArn': store.firewalls()[-1].FirewallArn,
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[2],
            'network-firewall.UntagResource': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-untag-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-untag-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                store.tag_resource(ResourceArn=store.firewalls()[-1].FirewallArn,  # noqa: E501
                    Tags=[{'Key': 'env', 'Value': 'test'}]),
                {'ResourceArn': store.firewalls()[-1].FirewallArn,
                 'TagKeys': ['env']})[3],
            'network-firewall.ListTagsForResource': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-ltr-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-ltr-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                store.tag_resource(ResourceArn=store.firewalls()[-1].FirewallArn,  # noqa: E501
                    Tags=[{'Key': 'env', 'Value': 'test'}]),
                {'ResourceArn': store.firewalls()[-1].FirewallArn})[3],
            'AssociateFirewallPolicy': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-asc-pol1',
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall_policy(FirewallPolicyName='nfw-asc-pol2',
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-asc-fw',
                    FirewallPolicyArn=store.policies()[-2].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn,
                 'FirewallPolicyArn': store.policies()[-1].FirewallPolicyArn})[3],  # noqa: E501
            'UpdateFirewallDeleteProtection': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-udp-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-udp-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn,
                 'DeleteProtection': True})[2],
            'UpdateFirewallDescription': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-udesc-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-udesc-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn,
                 'Description': 'Updated description'})[2],
            'UpdateFirewallPolicyChangeProtection': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-upcp-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-upcp-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn,
                 'FirewallPolicyChangeProtection': True})[2],
            'UpdateSubnetChangeProtection': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-usc-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                store.create_firewall(FirewallName='nfw-usc-fw',
                    FirewallPolicyArn=store.policies()[-1].FirewallPolicyArn),
                {'FirewallArn': store.firewalls()[-1].FirewallArn,
                 'SubnetChangeProtection': True})[2],
            'UpdateFirewallPolicy': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-up-pol',
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                {'UpdateToken': 'update-token',
                 'FirewallPolicyArn': store.policies()[-1].FirewallPolicyArn,
                 'FirewallPolicy': {'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatefulDefaultActions': ['aws:drop_strict']}})[1],  # noqa: E501
            'UpdateRuleGroup': lambda store: (
                store.create_rule_group(RuleGroupName='nfw-urg-rg', Type='STATELESS',  # noqa: E501
                    Capacity=100, RuleGroup={'RulesSource': {}}),
                {'UpdateToken': 'update-token',
                 'RuleGroupArn': store.rule_groups()[-1].RuleGroupArn,
                 'RuleGroup': {'RulesSource': {'StatelessRulesAndCustomActions': {'StatelessRules': []}}}})[1],  # noqa: E501
}
