# Test inputs for opensearchserverless
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'ListAccessPolicies': {'type': 'data'},
            'ListLifecyclePolicies': {'type': 'retention'},
            'ListSecurityPolicies': {'type': 'encryption'},
            'GetAccessPolicy': lambda store: (
                store.create_access_policy(type='data', name='s-get-ap',
                                           policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'data', 'name': 's-get-ap'})[1],
            'GetSecurityPolicy': lambda store: (
                store.create_security_policy(type='encryption', name='s-get-sp',  # noqa: E501
                                             policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'encryption', 'name': 's-get-sp'})[1],
            'DeleteAccessPolicy': lambda store: (
                store.create_access_policy(type='data', name='s-del-ap',
                                           policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'data', 'name': 's-del-ap'})[1],
            'DeleteLifecyclePolicy': lambda store: (
                store.create_lifecycle_policy(type='retention', name='s-del-lp',  # noqa: E501
                                              policy='{"Rules":[{"ResourceType":"index"}]}'),  # noqa: E501
                {'type': 'retention', 'name': 's-del-lp'})[1],
            'DeleteSecurityPolicy': lambda store: (
                store.create_security_policy(type='encryption', name='s-del-sp',  # noqa: E501
                                             policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'encryption', 'name': 's-del-sp'})[1],
            'UpdateAccessPolicy': lambda store: (
                store.create_access_policy(type='data', name='s-upd-ap',
                                           policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'data', 'name': 's-upd-ap', 'policyVersion': '1',
                 'policy': '{"Rules":[{"ResourceType":"collection"}],"Description":"updated"}'})[1],  # noqa: E501
            'UpdateLifecyclePolicy': lambda store: (
                store.create_lifecycle_policy(type='retention', name='s-upd-lp',  # noqa: E501
                                              policy='{"Rules":[{"ResourceType":"index"}]}'),  # noqa: E501
                {'type': 'retention', 'name': 's-upd-lp', 'policyVersion': '1',
                 'policy': '{"Rules":[{"ResourceType":"index"}],"Description":"updated"}'})[1],  # noqa: E501
            'UpdateSecurityPolicy': lambda store: (
                store.create_security_policy(type='encryption', name='s-upd-sp',  # noqa: E501
                                             policy='{"Rules":[{"ResourceType":"collection"}]}'),  # noqa: E501
                {'type': 'encryption', 'name': 's-upd-sp', 'policyVersion': '1',  # noqa: E501
                 'policy': '{"Rules":[{"ResourceType":"collection"}],"Description":"updated"}'})[1],  # noqa: E501
            'DeleteCollection': lambda store: (
                store.create_collection(name='s-del-col', id='s-del-col', type='SEARCH'),  # noqa: E501
                {'id': 's-del-col'})[1],
            'UpdateCollection': lambda store: (
                store.create_collection(name='s-upd-col', id='s-upd-col', type='SEARCH'),  # noqa: E501
                {'id': 's-upd-col', 'description': 'updated description'})[1],
            'TagResource': lambda store: (
                store.create_collection(name='s-tag-col', id='s-tag-col', type='SEARCH'),  # noqa: E501
                {'resourceArn': 'arn:aws:aoss:us-east-1:000000000000:collection/s-tag-col',  # noqa: E501
                 'tags': [{'key': 'env', 'value': 'test'}]})[1],
            'UntagResource': lambda store: (
                store.create_collection(name='s-untag-col', id='s-untag-col', type='SEARCH'),  # noqa: E501
                {'resourceArn': 'arn:aws:aoss:us-east-1:000000000000:collection/s-untag-col',  # noqa: E501
                 'tagKeys': ['env']})[1],
            'ListTagsForResource': lambda store: (
                store.create_collection(name='s-ltf-col', id='s-ltf-col', type='SEARCH'),  # noqa: E501
                {'resourceArn': 'arn:aws:aoss:us-east-1:000000000000:collection/s-ltf-col'})[1],  # noqa: E501
}
