# Test inputs for organizations
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateOrganization': lambda store: (
                setattr(store, 'organization', None) if store.organization else None,
                {'FeatureSet': 'ALL'})[1],
            'CreateAccount': lambda store: (
                store.create_organization(),
                {'Email': 'test-acc@test.com', 'AccountName': 'TestAccount'})[1],  # noqa: E501
            'CreateOrganizationalUnit': lambda store: (
                store.create_organization(),
                {'ParentId': store.roots[0], 'Name': 'TestOU'})[1],
            'organizations.CreatePolicy': lambda store: (
                store.create_organization(),
                {'Name': 'TestPolicy', 'Description': 'Test description',
                 'Type': 'SERVICE_CONTROL_POLICY',
                 'Content': '{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}'})[1],  # noqa: E501
            'DescribeOrganization': lambda store: (
                store.create_organization(),
                {})[1],
            'ListAccounts': lambda store: (
                store.create_organization(),
                {})[1],
            'ListRoots': lambda store: (
                store.create_organization(),
                {})[1],
            'ListAccountsForParent': lambda store: (
                store.create_organization(),
                {'ParentId': store.roots[0]})[1],
            'ListOrganizationalUnitsForParent': lambda store: (
                store.create_organization(),
                {'ParentId': store.roots[0]})[1],
            'organizations.ListPolicies': lambda store: (
                store.create_organization(),
                {'Filter': 'SERVICE_CONTROL_POLICY'})[1],
            'organizations.ListPoliciesForTarget': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='LPFT-Policy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                store.attach_policy(p.id, store.roots[0]),
                {'TargetId': store.roots[0], 'Filter': 'SERVICE_CONTROL_POLICY'})[3],  # noqa: E501
            'DescribeAccount': lambda store: (
                org := store.create_organization(),
                acc := store.create_account(email='desc-acc@test.com', name='DescAccount'),  # noqa: E501
                {'AccountId': acc['CreateAccountStatus']['AccountId']})[2],
            'DescribeOrganizationalUnit': lambda store: (
                org := store.create_organization(),
                ou := store.create_organizational_unit(store.roots[0], 'DescOU'),  # noqa: E501
                {'OrganizationalUnitId': ou.id})[2],
            'DescribePolicy': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='DescPolicy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                {'PolicyId': p.id})[2],
            'DeleteOrganization': lambda store: (
                store.create_organization(),
                [store.accounts.pop(aid) for aid in list(store.accounts.keys())
                 if aid != store.organization.master_account_id],
                {})[1],
            'DeleteOrganizationalUnit': lambda store: (
                org := store.create_organization(),
                ou := store.create_organizational_unit(store.roots[0], 'DelOU'),  # noqa: E501
                {'OrganizationalUnitId': ou.id})[2],
            'organizations.DeletePolicy': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='DelPolicy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                {'PolicyId': p.id})[2],
            'CloseAccount': lambda store: (
                org := store.create_organization(),
                acc := store.create_account(email='close-acc@test.com', name='CloseAccount'),  # noqa: E501
                {'AccountId': acc['CreateAccountStatus']['AccountId']})[2],
            'RemoveAccountFromOrganization': lambda store: (
                org := store.create_organization(),
                acc := store.create_account(email='remove-acc@test.com', name='RemoveAccount'),  # noqa: E501
                {'AccountId': acc['CreateAccountStatus']['AccountId']})[2],
            'UpdateOrganizationalUnit': lambda store: (
                org := store.create_organization(),
                ou := store.create_organizational_unit(store.roots[0], 'UpdOU'),  # noqa: E501
                {'OrganizationalUnitId': ou.id, 'Name': 'UpdatedOU'})[2],
            'UpdatePolicy': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='UpdPolicy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                {'PolicyId': p.id, 'Name': 'UpdatedPolicy'})[2],
            'EnableAllFeatures': lambda store: (
                store.create_organization(),
                {})[1],
            'MoveAccount': lambda store: (
                org := store.create_organization(),
                acc := store.create_account(email='move-acc@test.com', name='MoveAccount'),  # noqa: E501
                dest_ou := store.create_organizational_unit(store.roots[0], 'DestOU'),  # noqa: E501
                {'AccountId': acc['CreateAccountStatus']['AccountId'],
                 'SourceParentId': store.roots[0],
                 'DestinationParentId': dest_ou.id})[3],
            'AttachPolicy': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='AttPolicy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                {'PolicyId': p.id, 'TargetId': store.roots[0]})[2],
            'DetachPolicy': lambda store: (
                org := store.create_organization(),
                p := store.create_policy(
                    content='{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Action":"*","Resource":"*"}]}',  # noqa: E501
                    description='Test', name='DetPolicy', type='SERVICE_CONTROL_POLICY'),  # noqa: E501
                store.attach_policy(p.id, store.roots[0]),
                {'PolicyId': p.id, 'TargetId': store.roots[0]})[3],
}
