# Test inputs for personalize
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'personalize.CreateDataset': {'name': 'pers-test-ds', 'schemaArn': 'arn:aws:personalize:us-east-1:123456789012:schema/test', 'datasetGroupArn': 'arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', 'datasetType': 'Interactions'},  # noqa: E501
            'personalize.DescribeDataset': lambda store: (r := store.create_dataset('pers-desc-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'datasetArn': r.datasetArn})[1],  # noqa: E501
            'personalize.ListDatasets': {},
            'personalize.UpdateDataset': lambda store: (r := store.create_dataset('pers-upd-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'datasetArn': r.datasetArn, 'schemaArn': 'arn:aws:personalize:us-east-1:123456789012:schema/test2'})[1],  # noqa: E501
            'personalize.DeleteDataset': lambda store: (r := store.create_dataset('pers-del-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'datasetArn': r.datasetArn})[1],  # noqa: E501
            'personalize.CreateSolution': {'name': 'pers-test-sol', 'datasetGroupArn': 'arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', 'recipeArn': 'arn:aws:personalize:::recipe/aws-hrnn'},  # noqa: E501
            'personalize.DescribeSolution': lambda store: (r := store.create_solution('pers-desc-sol', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', recipeArn='arn:aws:personalize:::recipe/aws-hrnn'), {'solutionArn': r.solutionArn})[1],  # noqa: E501
            'personalize.ListSolutions': {},
            'personalize.DeleteSolution': lambda store: (r := store.create_solution('pers-del-sol', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', recipeArn='arn:aws:personalize:::recipe/aws-hrnn'), {'solutionArn': r.solutionArn})[1],  # noqa: E501
            'personalize.CreateCampaign': {'name': 'pers-test-camp', 'solutionVersionArn': 'arn:aws:personalize:us-east-1:123456789012:solution-version/test-sv'},  # noqa: E501
            'personalize.DescribeCampaign': lambda store: (r := store.create_campaign('pers-desc-camp', solutionVersionArn='arn:aws:personalize:us-east-1:123456789012:solution-version/test-sv'), {'campaignArn': r.campaignArn})[1],  # noqa: E501
            'personalize.ListCampaigns': {},
            'personalize.UpdateCampaign': lambda store: (r := store.create_campaign('pers-upd-camp', solutionVersionArn='arn:aws:personalize:us-east-1:123456789012:solution-version/test-sv'), {'campaignArn': r.campaignArn, 'minProvisionedTPS': 5})[1],  # noqa: E501
            'personalize.DeleteCampaign': lambda store: (r := store.create_campaign('pers-del-camp', solutionVersionArn='arn:aws:personalize:us-east-1:123456789012:solution-version/test-sv'), {'campaignArn': r.campaignArn})[1],  # noqa: E501
            'personalize.TagResource': lambda store: (r := store.create_dataset('pers-tag-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'resourceArn': r.datasetArn, 'tags': [{'tagKey': 'env', 'tagValue': 'test'}]})[1],  # noqa: E501
            'personalize.UntagResource': lambda store: (r := store.create_dataset('pers-untag-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'resourceArn': r.datasetArn, 'tagKeys': ['env']})[1],  # noqa: E501
            'personalize.ListTagsForResource': lambda store: (r := store.create_dataset('pers-ltfr-ds', schemaArn='arn:aws:personalize:us-east-1:123456789012:schema/test', datasetGroupArn='arn:aws:personalize:us-east-1:123456789012:dataset-group/test-dg', datasetType='Interactions'), {'resourceArn': r.datasetArn})[1],  # noqa: E501
}
