# Test inputs for polly
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'PutLexicon': {'Name': 'test-lexicon', 'Content': '<?xml version="1.0"?><lexicon version="1.0" xmlns="http://www.w3.org/2005/01/pronunciation-lexicon" alphabet="ipa" xml:lang="en-US"><lexeme><grapheme>test</grapheme><alias>test</alias></lexeme></lexicon>'},  # noqa: E501
            'GetLexicon': lambda store: (store.put_lexicon('test-gl', '<?xml version="1.0"?><lexicon version="1.0" xmlns="http://www.w3.org/2005/01/pronunciation-lexicon" alphabet="ipa" xml:lang="en-US"><lexeme><grapheme>test</grapheme><alias>test</alias></lexeme></lexicon>'), {'Name': 'test-gl'})[1],  # noqa: E501
            'ListLexicons': {},
            'DeleteLexicon': lambda store: (store.put_lexicon('test-dl', '<?xml version="1.0"?><lexicon version="1.0" xmlns="http://www.w3.org/2005/01/pronunciation-lexicon" alphabet="ipa" xml:lang="en-US"><lexeme><grapheme>test</grapheme><alias>test</alias></lexeme></lexicon>'), {'Name': 'test-dl'})[1],  # noqa: E501
            'DescribeVoices': {},
            'SynthesizeSpeech': {'OutputFormat': 'mp3', 'Text': 'Hello world', 'VoiceId': 'Joanna'},  # noqa: E501
            'StartSpeechSynthesisTask': {'OutputFormat': 'mp3', 'OutputS3BucketName': 'test-bucket', 'Text': 'Hello world', 'VoiceId': 'Joanna'},  # noqa: E501
            'GetSpeechSynthesisTask': lambda store: (t := store.start_speech_synthesis_task(OutputFormat='mp3', OutputS3BucketName='test-bucket', Text='Hello', VoiceId='Joanna'), {'TaskId': t['SynthesisTask']['TaskId']})[1],  # noqa: E501
            'ListSpeechSynthesisTasks': {},
}
