# Test inputs for quicksight
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateAnalysis': {'AwsAccountId': '123456789012', 'AnalysisId': 'test-analysis', 'Name': 'Test Analysis'},  # noqa: E501
            'CreateDashboard': {'AwsAccountId': '123456789012', 'DashboardId': 'test-dashboard', 'Name': 'Test Dashboard'},  # noqa: E501
            'CreateDataSet': {'AwsAccountId': '123456789012', 'DataSetId': 'test-dataset', 'Name': 'Test Dataset',  # noqa: E501
                              'PhysicalTableMap': {}, 'ImportMode': 'DIRECT_QUERY'},  # noqa: E501
            'quicksight.CreateDataSource': {'AwsAccountId': '123456789012', 'DataSourceId': 'test-ds', 'Name': 'Test DS', 'Type': 'S3'},  # noqa: E501
            'ListAnalyses': {'AwsAccountId': '123456789012'},
            'ListDashboards': {'AwsAccountId': '123456789012'},
            'ListDataSets': {'AwsAccountId': '123456789012'},
            'quicksight.ListDataSources': {'AwsAccountId': '123456789012'},
            'DescribeAnalysis': lambda store: (
                store.create_analysis('123456789012', 's-desc-analysis', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'AnalysisId': 's-desc-analysis'})[1],  # noqa: E501
            'DescribeDashboard': lambda store: (
                store.create_dashboard('123456789012', 's-desc-dashboard', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DashboardId': 's-desc-dashboard'})[1],  # noqa: E501
            'DescribeDataSet': lambda store: (
                store.create_dataset('123456789012', 's-desc-dataset', Name='Test',  # noqa: E501
                                     PhysicalTableMap={}, ImportMode='DIRECT_QUERY'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSetId': 's-desc-dataset'})[1],  # noqa: E501
            'quicksight.DescribeDataSource': lambda store: (
                store.create_datasource('123456789012', 's-desc-ds', Name='Test', Type='S3'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSourceId': 's-desc-ds'})[1],  # noqa: E501
            'DeleteAnalysis': lambda store: (
                store.create_analysis('123456789012', 's-del-analysis', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'AnalysisId': 's-del-analysis'})[1],  # noqa: E501
            'DeleteDashboard': lambda store: (
                store.create_dashboard('123456789012', 's-del-dashboard', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DashboardId': 's-del-dashboard'})[1],  # noqa: E501
            'DeleteDataSet': lambda store: (
                store.create_dataset('123456789012', 's-del-dataset', Name='Test',  # noqa: E501
                                     PhysicalTableMap={}, ImportMode='DIRECT_QUERY'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSetId': 's-del-dataset'})[1],  # noqa: E501
            'quicksight.DeleteDataSource': lambda store: (
                store.create_datasource('123456789012', 's-del-ds', Name='Test', Type='S3'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSourceId': 's-del-ds'})[1],  # noqa: E501
            'UpdateAnalysis': lambda store: (
                store.create_analysis('123456789012', 's-upd-analysis', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'AnalysisId': 's-upd-analysis', 'Name': 'Updated Analysis'})[1],  # noqa: E501
            'UpdateDashboard': lambda store: (
                store.create_dashboard('123456789012', 's-upd-dashboard', Name='Test'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DashboardId': 's-upd-dashboard', 'Name': 'Updated Dashboard'})[1],  # noqa: E501
            'UpdateDataSet': lambda store: (
                store.create_dataset('123456789012', 's-upd-dataset', Name='Test',  # noqa: E501
                                     PhysicalTableMap={}, ImportMode='DIRECT_QUERY'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSetId': 's-upd-dataset', 'Name': 'Updated Dataset',  # noqa: E501
                 'PhysicalTableMap': {}, 'ImportMode': 'DIRECT_QUERY'})[1],
            'quicksight.UpdateDataSource': lambda store: (
                store.create_datasource('123456789012', 's-upd-ds', Name='Test', Type='S3'),  # noqa: E501
                {'AwsAccountId': '123456789012', 'DataSourceId': 's-upd-ds', 'Name': 'Updated DS'})[1],  # noqa: E501
            'quicksight.TagResource': lambda store: (
                store.create_analysis('123456789012', 's-tag-analysis', Name='Test'),  # noqa: E501
                {'ResourceArn': store.analyses('123456789012')[-1].Arn,
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'quicksight.UntagResource': lambda store: (
                store.create_analysis('123456789012', 's-untag-analysis', Name='Test'),  # noqa: E501
                {'ResourceArn': store.analyses('123456789012')[-1].Arn,
                 'TagKeys': ['env']})[1],
            'quicksight.ListTagsForResource': lambda store: (
                store.create_analysis('123456789012', 's-ltfr-analysis', Name='Test'),  # noqa: E501
                {'ResourceArn': store.analyses('123456789012')[-1].Arn})[1],
}
