# Test inputs for ram
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateResourceShare': {'name': 'test-ram-share'},
            'CreatePermission': {'name': 'test-ram-perm', 'resourceType': 'ec2:Instance',  # noqa: E501
                                  'policyTemplate': '{"Effect":"Allow"}'},
            'CreatePermissionVersion': lambda store: (
                store.create_permission(name='ram-cpv-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                {'permissionArn': store.permissions()[0].permissionArn,
                 'policyTemplate': '{"Effect":"AllowV2"}'})[1],
            'ListPermissions': {},
            'ListResourceTypes': {},
            'ListResources': {},
            'ListPrincipals': {},
            'GetResourceShares': {},
            'GetResourceShareInvitations': {},
            'GetResourceShareAssociations': {'associationType': 'PRINCIPAL'},
            'EnableSharingWithAwsOrganization': {},
            'GetPermission': lambda store: (
                store.create_permission(name='ram-get-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                {'permissionArn': store.permissions()[0].permissionArn})[1],
            'ListPermissionVersions': lambda store: (
                store.create_permission(name='ram-lpv-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                {'permissionArn': store.permissions()[0].permissionArn})[1],
            'ListResourceSharePermissions': lambda store: (
                store.create_resource_share(name='ram-lrsp-share'),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn})[1],  # noqa: E501
            'DeleteResourceShare': lambda store: (
                store.create_resource_share(name='ram-del-share'),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn})[1],  # noqa: E501
            'DeletePermission': lambda store: (
                store.create_permission(name='ram-del-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                {'permissionArn': store.permissions()[0].permissionArn})[1],
            'DeletePermissionVersion': lambda store: (
                store.create_permission(name='ram-dpv-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                store.create_permission_version(store.permissions()[0].permissionArn,  # noqa: E501
                                                '{"Effect":"AllowV2"}'),
                {'permissionArn': store.permissions()[0].permissionArn,
                 'permissionVersion': 2})[2],
            'UpdateResourceShare': lambda store: (
                store.create_resource_share(name='ram-upd-share'),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn,  # noqa: E501
                 'name': 'ram-updated-share'})[1],
            'SetDefaultPermissionVersion': lambda store: (
                store.create_permission(name='ram-sdpv-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                store.create_permission_version(store.permissions()[0].permissionArn,  # noqa: E501
                                                '{"Effect":"AllowV2"}'),
                {'permissionArn': store.permissions()[0].permissionArn,
                 'permissionVersion': 2})[2],
            'AssociateResourceSharePermission': lambda store: (
                store.create_resource_share(name='ram-asp-share'),
                store.create_permission(name='ram-asp-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn,  # noqa: E501
                 'permissionArn': store.permissions()[0].permissionArn})[2],
            'AssociateResourceShare': lambda store: (
                store.create_resource_share(name='ram-as-share'),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn,  # noqa: E501
                 'resourceArns': ['arn:aws:ec2:us-east-1:000000000000:instance/i-test'],  # noqa: E501
                 'principals': ['000000000000']})[1],
            'DisassociateResourceSharePermission': lambda store: (
                store.create_resource_share(name='ram-dsp-share'),
                store.create_permission(name='ram-dsp-perm', resourceType='ec2:Instance',  # noqa: E501
                                        policyTemplate='{"Effect":"Allow"}'),
                store.associate_resource_share_permission(
                    store.resource_shares()[0].resourceShareArn,
                    store.permissions()[0].permissionArn),
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn,  # noqa: E501
                 'permissionArn': store.permissions()[0].permissionArn})[3],
            'DisassociateResourceShare': lambda store: (
                store.create_resource_share(name='ram-ds-share'),
                store.associate_resource_share(store.resource_shares()[0].resourceShareArn,  # noqa: E501
                                               resourceArns=['arn:aws:ec2:us-east-1:000000000000:instance/i-test']),  # noqa: E501
                {'resourceShareArn': store.resource_shares()[0].resourceShareArn,  # noqa: E501
                 'resourceArns': ['arn:aws:ec2:us-east-1:000000000000:instance/i-test']})[2],  # noqa: E501
            'ram.TagResource': lambda store: (
                store.create_resource_share(name='ram-tag-share'),
                {'resourceShareArn': store.resource_shares()[-1].resourceShareArn,  # noqa: E501
                 'tags': [{'key': 'env', 'value': 'test'}]})[1],
            'ram.UntagResource': lambda store: (
                store.create_resource_share(name='ram-untag-share'),
                store.tag_resource(resourceShareArn=store.resource_shares()[-1].resourceShareArn,  # noqa: E501
                                   tags=[{'key': 'env', 'value': 'test'}]),
                {'resourceShareArn': store.resource_shares()[-1].resourceShareArn,  # noqa: E501
                 'tagKeys': ['env']})[2],
            'AcceptResourceShareInvitation': lambda store: (
                store.create_resource_share(name='ram-acc-share'),
                store.create_invitation(store.resource_shares()[-1].resourceShareArn),  # noqa: E501
                {'resourceShareInvitationArn': store.invitations()[-1].resourceShareInvitationArn})[2],  # noqa: E501
            'RejectResourceShareInvitation': lambda store: (
                store.create_resource_share(name='ram-rej-share'),
                store.create_invitation(store.resource_shares()[-1].resourceShareArn),  # noqa: E501
                {'resourceShareInvitationArn': store.invitations()[-1].resourceShareInvitationArn})[2],  # noqa: E501
}
