# Test inputs for rds
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDBInstance': {'DBInstanceIdentifier': 'rds-test-db', 'DBInstanceClass': 'db.t3.micro', 'Engine': 'mysql', 'MasterUsername': 'admin', 'MasterUserPassword': 'Password123!'},  # noqa: E501
            'DescribeDBInstances': {},
            'ModifyDBInstance': lambda store: (store.create_db_instance('rds-mod-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'), {'DBInstanceIdentifier': 'rds-mod-db', 'DBInstanceClass': 'db.t3.small'})[1],  # noqa: E501
            'DeleteDBInstance': lambda store: (store.create_db_instance('rds-del-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'), {'DBInstanceIdentifier': 'rds-del-db', 'SkipFinalSnapshot': True})[1],  # noqa: E501
            'RebootDBInstance': lambda store: (store.create_db_instance('rds-reboot-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'), {'DBInstanceIdentifier': 'rds-reboot-db'})[1],  # noqa: E501
            'CreateDBCluster': {'DBClusterIdentifier': 'rds-test-cluster', 'Engine': 'aurora-mysql', 'MasterUsername': 'admin', 'MasterUserPassword': 'Password123!'},  # noqa: E501
            'DescribeDBClusters': {},
            'ModifyDBCluster': lambda store: (store.create_db_cluster('rds-mod-cl', 'aurora-mysql', master_username='admin', master_user_password='Password123!'), {'DBClusterIdentifier': 'rds-mod-cl', 'MasterUserPassword': 'NewPassword123!'})[1],  # noqa: E501
            'DeleteDBCluster': lambda store: (store.create_db_cluster('rds-del-cl', 'aurora-mysql', master_username='admin', master_user_password='Password123!'), {'DBClusterIdentifier': 'rds-del-cl', 'SkipFinalSnapshot': True})[1],  # noqa: E501
            'CreateDBSnapshot': lambda store: (store.create_db_instance('rds-snap-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'), {'DBSnapshotIdentifier': 'rds-test-snap', 'DBInstanceIdentifier': 'rds-snap-db'})[1],  # noqa: E501
            'DescribeDBSnapshots': {},
            'DeleteDBSnapshot': lambda store: (store.create_db_instance('rds-dsnap-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'), store.create_db_snapshot('rds-del-snap', 'rds-dsnap-db'), {'DBSnapshotIdentifier': 'rds-del-snap'})[2],  # noqa: E501
            'CreateDBParameterGroup': {'DBParameterGroupName': 'rds-test-pg', 'DBParameterGroupFamily': 'mysql8.0', 'Description': 'Test parameter group'},  # noqa: E501
            'DescribeDBParameterGroups': {},
            'ModifyDBParameterGroup': lambda store: (store.create_db_parameter_group('rds-mod-pg', 'mysql8.0', 'Test'), {'DBParameterGroupName': 'rds-mod-pg', 'Parameters': [{'ParameterName': 'max_connections', 'ParameterValue': '100'}]})[1],  # noqa: E501
            'DeleteDBParameterGroup': lambda store: (store.create_db_parameter_group('rds-del-pg', 'mysql8.0', 'Test'), {'DBParameterGroupName': 'rds-del-pg'})[1],  # noqa: E501
            'CreateDBClusterParameterGroup': {'DBClusterParameterGroupName': 'rds-test-cpg', 'DBParameterGroupFamily': 'aurora-mysql8.0', 'Description': 'Test cluster parameter group'},  # noqa: E501
            'DescribeDBClusterParameterGroups': {},
            'DeleteDBClusterParameterGroup': lambda store: (store.create_db_cluster_parameter_group('rds-del-cpg', 'aurora-mysql8.0', 'Test'), {'DBClusterParameterGroupName': 'rds-del-cpg'})[1],  # noqa: E501
            'CreateDBSubnetGroup': {'DBSubnetGroupName': 'rds-test-sng', 'DBSubnetGroupDescription': 'Test subnet group', 'SubnetIds': ['subnet-123']},  # noqa: E501
            'DescribeDBSubnetGroups': {},
            'DeleteDBSubnetGroup': lambda store: (store.create_db_subnet_group('rds-del-sng', 'Test subnet group', ['subnet-123']), {'DBSubnetGroupName': 'rds-del-sng'})[1],  # noqa: E501
            'rds.AddTagsToResource': lambda store: (
                store.create_db_instance('rds-tag-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'),  # noqa: E501
                {'ResourceName': 'rds-tag-db', 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],  # noqa: E501
            'rds.RemoveTagsFromResource': lambda store: (
                store.create_db_instance('rds-untag-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'),  # noqa: E501
                {'ResourceName': 'rds-untag-db', 'TagKeys': ['env']})[1],  # noqa: E501
            'rds.ListTagsForResource': lambda store: (
                store.create_db_instance('rds-ltfr-db', 'db.t3.micro', 'mysql', master_username='admin', master_user_password='Password123!'),  # noqa: E501
                {'ResourceName': 'rds-ltfr-db'})[1],  # noqa: E501
}
