# Test inputs for redshift
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateCluster': {'ClusterIdentifier': 'test-cluster', 'NodeType': 'dc2.large',  # noqa: E501
                               'MasterUsername': 'admin'},
            'CreateClusterParameterGroup': {'ParameterGroupName': 'test-pg',
                                             'ParameterGroupFamily': 'redshift-1.0',  # noqa: E501
                                             'Description': 'Test parameter group'},  # noqa: E501
            'CreateClusterSnapshot': lambda store: (
                store.create_cluster(ClusterIdentifier='red-snap-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'SnapshotIdentifier': 'test-snap',
                 'ClusterIdentifier': 'red-snap-cluster'})[1],
            'CreateClusterSubnetGroup': {'ClusterSubnetGroupName': 'test-sg',
                                          'Description': 'Test subnet group',
                                          'SubnetIds': ['subnet-abc123']},
            'CreateEventSubscription': {'SubscriptionName': 'test-sub',
                                         'SnsTopicArn': 'arn:aws:sns:us-east-1:000000000000:test'},  # noqa: E501
            'DescribeClusters': {},
            'DescribeClusterParameterGroups': {},
            'DescribeClusterSnapshots': {},
            'DescribeClusterSubnetGroups': {},
            'DescribeEventSubscriptions': {},
            'DeleteCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-del-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-del-cluster',
                 'SkipFinalClusterSnapshot': True})[1],
            'DeleteClusterParameterGroup': lambda store: (
                store.create_cluster_parameter_group(ParameterGroupName='red-del-pg',  # noqa: E501
                                                      ParameterGroupFamily='redshift-1.0',  # noqa: E501
                                                      Description='Delete me'),
                {'ParameterGroupName': 'red-del-pg'})[1],
            'DeleteClusterSnapshot': lambda store: (
                store.create_cluster(ClusterIdentifier='red-ds-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                store.create_cluster_snapshot(SnapshotIdentifier='red-del-snap',  # noqa: E501
                                              ClusterIdentifier='red-ds-cluster'),  # noqa: E501
                {'SnapshotIdentifier': 'red-del-snap'})[2],
            'DeleteClusterSubnetGroup': lambda store: (
                store.create_cluster_subnet_group(ClusterSubnetGroupName='red-del-sg',  # noqa: E501
                                                   Description='Delete me',
                                                   SubnetIds=['subnet-abc123']),  # noqa: E501
                {'ClusterSubnetGroupName': 'red-del-sg'})[1],
            'DeleteEventSubscription': lambda store: (
                store.create_event_subscription(SubscriptionName='red-del-sub',
                                                 SnsTopicArn='arn:aws:sns:us-east-1:000000000000:test'),  # noqa: E501
                {'SubscriptionName': 'red-del-sub'})[1],
            'ModifyCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-mod-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-mod-cluster',
                 'MasterUserPassword': 'NewPass123!'})[1],
            'ModifyClusterParameterGroup': lambda store: (
                store.create_cluster_parameter_group(ParameterGroupName='red-mod-pg',  # noqa: E501
                                                      ParameterGroupFamily='redshift-1.0',  # noqa: E501
                                                      Description='Modify me'),
                {'ParameterGroupName': 'red-mod-pg',
                 'Parameters': [{'ParameterName': 'max_connections', 'ParameterValue': '100'}]})[1],  # noqa: E501
            'ModifyClusterSubnetGroup': lambda store: (
                store.create_cluster_subnet_group(ClusterSubnetGroupName='red-mod-sg',  # noqa: E501
                                                   Description='Modify me',
                                                   SubnetIds=['subnet-abc123']),  # noqa: E501
                {'ClusterSubnetGroupName': 'red-mod-sg',
                 'SubnetIds': ['subnet-xyz789']})[1],
            'ModifyEventSubscription': lambda store: (
                store.create_event_subscription(SubscriptionName='red-mod-sub',
                                                 SnsTopicArn='arn:aws:sns:us-east-1:000000000000:test'),  # noqa: E501
                {'SubscriptionName': 'red-mod-sub',
                 'Enabled': False})[1],
            'PauseCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-pause-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-pause-cluster'})[1],
            'ResumeCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-resume-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-resume-cluster'})[1],
            'RebootCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-reboot-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-reboot-cluster'})[1],
            'ResizeCluster': lambda store: (
                store.create_cluster(ClusterIdentifier='red-resize-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                {'ClusterIdentifier': 'red-resize-cluster', 'NodeType': 'dc2.8xlarge',  # noqa: E501
                 'NumberOfNodes': 4})[1],
            'CopyClusterSnapshot': lambda store: (
                store.create_cluster(ClusterIdentifier='red-copy-cluster', NodeType='dc2.large',  # noqa: E501
                                     MasterUsername='admin'),
                store.create_cluster_snapshot(SnapshotIdentifier='red-src-snap',  # noqa: E501
                                              ClusterIdentifier='red-copy-cluster'),  # noqa: E501
                {'SourceSnapshotIdentifier': 'red-src-snap',
                 'TargetSnapshotIdentifier': 'red-tgt-snap'})[2],
            'ResetClusterParameterGroup': lambda store: (
                store.create_cluster_parameter_group(ParameterGroupName='red-rst-pg',  # noqa: E501
                                                      ParameterGroupFamily='redshift-1.0',  # noqa: E501
                                                      Description='Reset me'),
                {'ParameterGroupName': 'red-rst-pg',
                 'ResetAllParameters': True})[1],
            'CreateFirewallPolicy': {
                'FirewallPolicyName': 'nfw-test-policy',
                'FirewallPolicy': {'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                   'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']},  # noqa: E501
            },
            'CreateFirewall': lambda store: (
                store.create_firewall_policy(FirewallPolicyName='nfw-fw-policy',  # noqa: E501
                    FirewallPolicy={'StatelessDefaultActions': ['aws:forward_to_sfe'],  # noqa: E501
                                    'StatelessFragmentDefaultActions': ['aws:forward_to_sfe']}),  # noqa: E501
                {'FirewallName': 'nfw-test-fw',
                 'FirewallPolicyArn': store.policies()[-1].FirewallPolicyArn})[1],  # noqa: E501
            'CreateRuleGroup': {
                'RuleGroupName': 'nfw-test-rg',
                'Type': 'STATELESS',
                'Capacity': 100,
                'RuleGroup': {'RulesSource': {}},
            },
}
