# Test inputs for rekognition
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateCollection': {'CollectionId': 'test-collection'},
            'ListCollections': {},
            'ListFaces': lambda store: (
                store.collections.__setitem__('s-list-faces-col', {'CollectionId': 's-list-faces-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-list-faces-col', set()),
                {'CollectionId': 's-list-faces-col'})[2],
            'DescribeCollection': lambda store: (
                store.collections.__setitem__('s-desc-col', {'CollectionId': 's-desc-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-desc-col', set()),
                {'CollectionId': 's-desc-col'})[2],
            'DeleteCollection': lambda store: (
                store.collections.__setitem__('s-del-col', {'CollectionId': 's-del-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-del-col', set()),
                {'CollectionId': 's-del-col'})[2],
            'IndexFaces': lambda store: (
                store.collections.__setitem__('s-idx-col', {'CollectionId': 's-idx-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-idx-col', set()),
                {'CollectionId': 's-idx-col', 'Image': {'Bytes': 'dGVzdA=='}})[2],  # noqa: E501
            'SearchFaces': lambda store: (
                store.collections.__setitem__('s-search-col', {'CollectionId': 's-search-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-search-col', set()),
                {'CollectionId': 's-search-col', 'FaceId': 'test-face-id'})[2],
            'SearchFacesByImage': lambda store: (
                store.collections.__setitem__('s-sfbi-col', {'CollectionId': 's-sfbi-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-sfbi-col', set()),
                {'CollectionId': 's-sfbi-col', 'Image': {'Bytes': 'dGVzdA=='}})[2],  # noqa: E501
            'DeleteFaces': lambda store: (
                store.collections.__setitem__('s-delf-col', {'CollectionId': 's-delf-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-delf-col', set()),
                store.faces.__setitem__('test-face-1', {}),
                store.collection_faces['s-delf-col'].add('test-face-1'),
                {'CollectionId': 's-delf-col', 'FaceIds': ['test-face-1']})[4],
            'DetectFaces': {'Image': {'Bytes': 'dGVzdA=='}},
            'DetectLabels': {'Image': {'Bytes': 'dGVzdA=='}},
            'DetectModerationLabels': {'Image': {'Bytes': 'dGVzdA=='}},
            'DetectProtectiveEquipment': {'Image': {'Bytes': 'dGVzdA=='}},
            'DetectText': {'Image': {'Bytes': 'dGVzdA=='}},
            'CompareFaces': {'SourceImage': {'Bytes': 'dGVzdA=='}, 'TargetImage': {'Bytes': 'dGVzdA=='}},  # noqa: E501
            'RecognizeCelebrities': {'Image': {'Bytes': 'dGVzdA=='}},
            'StartCelebrityRecognition': {'Video': {'S3Object': {'Bucket': 'test-bucket', 'Name': 'test.mp4'}}},  # noqa: E501
            'StartContentModeration': {'Video': {'S3Object': {'Bucket': 'test-bucket', 'Name': 'test.mp4'}}},  # noqa: E501
            'StartFaceDetection': {'Video': {'S3Object': {'Bucket': 'test-bucket', 'Name': 'test.mp4'}}},  # noqa: E501
            'StartLabelDetection': {'Video': {'S3Object': {'Bucket': 'test-bucket', 'Name': 'test.mp4'}}},  # noqa: E501
            'StartTextDetection': {'Video': {'S3Object': {'Bucket': 'test-bucket', 'Name': 'test.mp4'}}},  # noqa: E501
            'GetCelebrityRecognition': lambda store: (
                store.video_jobs.__setitem__('s-gcr-job', {'JobId': 's-gcr-job', 'Status': 'SUCCEEDED', 'API': 'StartCelebrityRecognition', 'Video': {}, 'CreatedTimestamp': 0.0, 'Results': []}),  # noqa: E501
                {'JobId': 's-gcr-job'})[1],
            'GetContentModeration': lambda store: (
                store.video_jobs.__setitem__('s-gcm-job', {'JobId': 's-gcm-job', 'Status': 'SUCCEEDED', 'API': 'StartContentModeration', 'Video': {}, 'CreatedTimestamp': 0.0, 'Results': []}),  # noqa: E501
                {'JobId': 's-gcm-job'})[1],
            'GetFaceDetection': lambda store: (
                store.video_jobs.__setitem__('s-gfd-job', {'JobId': 's-gfd-job', 'Status': 'SUCCEEDED', 'API': 'StartFaceDetection', 'Video': {}, 'CreatedTimestamp': 0.0, 'Results': []}),  # noqa: E501
                {'JobId': 's-gfd-job'})[1],
            'GetLabelDetection': lambda store: (
                store.video_jobs.__setitem__('s-gld-job', {'JobId': 's-gld-job', 'Status': 'SUCCEEDED', 'API': 'StartLabelDetection', 'Video': {}, 'CreatedTimestamp': 0.0, 'Results': []}),  # noqa: E501
                {'JobId': 's-gld-job'})[1],
            'GetTextDetection': lambda store: (
                store.video_jobs.__setitem__('s-gtd-job', {'JobId': 's-gtd-job', 'Status': 'SUCCEEDED', 'API': 'StartTextDetection', 'Video': {}, 'CreatedTimestamp': 0.0, 'Results': []}),  # noqa: E501
                {'JobId': 's-gtd-job'})[1],
            'GetCelebrityInfo': {'Id': 'celebrity-1'},
            'rekognition.TagResource': lambda store: (
                store.collections.__setitem__('s-tag-col', {'CollectionId': 's-tag-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-tag-col', set()),
                {'ResourceArn': 'arn:aws:rekognition:us-east-1:123456789012:collection/s-tag-col',  # noqa: E501
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[2],
            'rekognition.UntagResource': lambda store: (
                store.collections.__setitem__('s-untag-col', {'CollectionId': 's-untag-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-untag-col', set()),
                store.tags.__setitem__('arn:aws:rekognition:us-east-1:123456789012:collection/s-untag-col', {'env': 'test'}),  # noqa: E501
                {'ResourceArn': 'arn:aws:rekognition:us-east-1:123456789012:collection/s-untag-col',  # noqa: E501
                 'TagKeys': ['env']})[3],
            'rekognition.ListTagsForResource': lambda store: (
                store.collections.__setitem__('s-ltfr-col', {'CollectionId': 's-ltfr-col', 'FaceCount': 0, 'CreatedTimestamp': 0.0}),  # noqa: E501
                store.collection_faces.__setitem__('s-ltfr-col', set()),
                {'ResourceArn': 'arn:aws:rekognition:us-east-1:123456789012:collection/s-ltfr-col'})[2],  # noqa: E501
}
