# Test inputs for rolesanywhere
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'rolesanywhere.CreateProfile': {'name': 'ra-test-profile', 'roleArns': ['arn:aws:iam::123456789012:role/test']},  # noqa: E501
            'rolesanywhere.GetProfile': lambda store: (r := store.create_profile('ra-get-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'profileId': r.profileId})[1],  # noqa: E501
            'rolesanywhere.ListProfiles': {},
            'rolesanywhere.UpdateProfile': lambda store: (r := store.create_profile('ra-upd-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'profileId': r.profileId, 'name': 'updated-name'})[1],  # noqa: E501
            'rolesanywhere.DeleteProfile': lambda store: (r := store.create_profile('ra-del-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'profileId': r.profileId})[1],  # noqa: E501
            'rolesanywhere.EnableProfile': lambda store: (r := store.create_profile('ra-en-prof', roleArns=['arn:aws:iam::123456789012:role/test'], enabled=False), {'profileId': r.profileId})[1],  # noqa: E501
            'rolesanywhere.DisableProfile': lambda store: (r := store.create_profile('ra-dis-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'profileId': r.profileId})[1],  # noqa: E501
            'rolesanywhere.CreateTrustAnchor': {'name': 'ra-test-ta', 'source': {'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}},  # noqa: E501
            'rolesanywhere.GetTrustAnchor': lambda store: (r := store.create_trust_anchor('ra-get-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId})[1],  # noqa: E501
            'rolesanywhere.ListTrustAnchors': {},
            'rolesanywhere.UpdateTrustAnchor': lambda store: (r := store.create_trust_anchor('ra-upd-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId, 'name': 'updated-ta'})[1],  # noqa: E501
            'rolesanywhere.DeleteTrustAnchor': lambda store: (r := store.create_trust_anchor('ra-del-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId})[1],  # noqa: E501
            'rolesanywhere.EnableTrustAnchor': lambda store: (r := store.create_trust_anchor('ra-en-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}, enabled=False), {'trustAnchorId': r.trustAnchorId})[1],  # noqa: E501
            'rolesanywhere.DisableTrustAnchor': lambda store: (r := store.create_trust_anchor('ra-dis-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId})[1],  # noqa: E501
            'rolesanywhere.ImportCrl': {'name': 'ra-test-crl', 'crlData': 'base64-crl-data', 'trustAnchorArn': 'arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta'},  # noqa: E501
            'rolesanywhere.GetCrl': lambda store: (r := store.import_crl('ra-get-crl', 'base64-crl-data', trustAnchorArn='arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta'), {'crlId': r.crlId})[1],  # noqa: E501
            'rolesanywhere.ListCrls': {},
            'rolesanywhere.UpdateCrl': lambda store: (r := store.import_crl('ra-upd-crl', 'base64-crl-data', trustAnchorArn='arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta'), {'crlId': r.crlId, 'name': 'updated-crl'})[1],  # noqa: E501
            'rolesanywhere.DeleteCrl': lambda store: (r := store.import_crl('ra-del-crl', 'base64-crl-data', trustAnchorArn='arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta'), {'crlId': r.crlId})[1],  # noqa: E501
            'rolesanywhere.EnableCrl': lambda store: (r := store.import_crl('ra-en-crl', 'base64-crl-data', trustAnchorArn='arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta', enabled=False), {'crlId': r.crlId})[1],  # noqa: E501
            'rolesanywhere.DisableCrl': lambda store: (r := store.import_crl('ra-dis-crl', 'base64-crl-data', trustAnchorArn='arn:aws:rolesanywhere:us-east-1:123456789012:trust-anchor/test-ta'), {'crlId': r.crlId})[1],  # noqa: E501
            'rolesanywhere.GetSubject': lambda store: (r := store.create_trust_anchor('ra-subj-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'subjectId': 'test-subject'})[1],  # noqa: E501
            'rolesanywhere.ListSubjects': {},
            'rolesanywhere.TagResource': lambda store: (r := store.create_profile('ra-tag-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'resourceArn': r.profileArn, 'tags': [{'key': 'env', 'value': 'test'}]})[1],  # noqa: E501
            'rolesanywhere.UntagResource': lambda store: (r := store.create_profile('ra-untag-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'resourceArn': r.profileArn, 'tagKeys': ['env']})[1],  # noqa: E501
            'rolesanywhere.ListTagsForResource': lambda store: (r := store.create_profile('ra-ltfr-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'resourceArn': r.profileArn})[1],  # noqa: E501
            'rolesanywhere.PutAttributeMapping': lambda store: (r := store.create_profile('ra-pam-prof', roleArns=['arn:aws:iam::123456789012:role/test']), {'profileId': r.profileId, 'certificateField': 'x509Subject', 'mappingRules': [{'field': 'x509Subject/CN'}]})[1],  # noqa: E501
            'rolesanywhere.DeleteAttributeMapping': lambda store: (r := store.create_profile('ra-dam-prof', roleArns=['arn:aws:iam::123456789012:role/test']), r2 := store.put_attribute_mapping(r.profileId, 'x509Subject', [{'field': 'x509Subject/CN'}]), {'profileId': r.profileId, 'certificateField': 'x509Subject'})[2],  # noqa: E501
            'rolesanywhere.PutNotificationSettings': lambda store: (r := store.create_trust_anchor('ra-pns-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId, 'notificationSettings': {'enabled': True, 'channelArn': 'arn:aws:sns:us-east-1:123456789012:test-topic'}})[1],  # noqa: E501
            'rolesanywhere.ResetNotificationSettings': lambda store: (r := store.create_trust_anchor('ra-rns-ta', source={'sourceType': 'AWS_ACM_PCA', 'sourceData': {'acmPcaArn': 'arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/test-ca'}}), {'trustAnchorId': r.trustAnchorId})[1],  # noqa: E501
}
