# Test inputs for s3
# Auto-generated by shape-validator cron (2026-08-03) — expanded coverage
# ruff: noqa  # generated file — runtime-injected Record classes, long lambdas
TEST_INPUTS = {
    'CreateBucket': {'Bucket': 'shape-test-bucket'},
    'PutObject': lambda store: ((store.create_bucket('shape-test-bucket', {}) if not store.buckets('shape-test-bucket') else None), {'Bucket': 'shape-test-bucket', 'Key': 'shape-key', 'Body': b'data'})[1],  # noqa: E501
    'GetObject': lambda store: ((store.create_bucket('shape-test-bucket', {}) if not store.buckets('shape-test-bucket') else None), store.put_object('shape-test-bucket', 'shape-key', b'data'), {'Bucket': 'shape-test-bucket', 'Key': 'shape-key'})[2],  # noqa: E501
    'ListBuckets': {},
}
