# Test inputs for s3tables
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateTableBucket': {'name': 's3t-shape-test'},
            'ListTableBuckets': {},
            'ListNamespaces': lambda store: (
                bucket := store.create_table_bucket(name='s3t-lns-bucket'),
                {'tableBucketARN': bucket['arn']})[1],
            's3tables.ListTables': lambda store: (
                bucket := store.create_table_bucket(name='s3t-ltb-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                {'tableBucketARN': bucket['arn'], 'namespace': 'default'})[2],
            'GetTableBucket': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gtb-bucket'),
                {'tableBucketARN': bucket['arn']})[1],
            'GetNamespace': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gn-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                {'tableBucketARN': bucket['arn'], 'namespace': 'default'})[2],
            's3tables.GetTable': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gt-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                store.create_table(bucket['arn'], 'default', 'test-table', format='ICEBERG'),  # noqa: E501
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'test-table'})[3],  # noqa: E501
            'GetTableBucketEncryption': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gtbe-bucket'),
                {'tableBucketARN': bucket['arn']})[1],
            'GetTableEncryption': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gte-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                store.create_table(bucket['arn'], 'default', 'test-table', format='ICEBERG'),  # noqa: E501
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'test-table'})[3],  # noqa: E501
            'GetTableMaintenanceConfiguration': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gtmc-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                store.create_table(bucket['arn'], 'default', 'test-table', format='ICEBERG'),  # noqa: E501
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'test-table'})[3],  # noqa: E501
            'GetTableBucketMaintenanceConfiguration': lambda store: (
                bucket := store.create_table_bucket(name='s3t-gtbmc-bucket'),
                {'tableBucketARN': bucket['arn']})[1],
            'CreateNamespace': lambda store: (
                bucket := store.create_table_bucket(name='s3t-cn-bucket'),
                {'tableBucketARN': bucket['arn'], 'namespace': ['default']})[1],  # noqa: E501
            's3tables.CreateTable': lambda store: (
                bucket := store.create_table_bucket(name='s3t-ct-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'test-table', 'format': 'ICEBERG'})[2],  # noqa: E501
            'DeleteTableBucket': lambda store: (
                bucket := store.create_table_bucket(name='s3t-dtb-bucket'),
                {'tableBucketARN': bucket['arn']})[1],
            'DeleteNamespace': lambda store: (
                bucket := store.create_table_bucket(name='s3t-dn-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                {'tableBucketARN': bucket['arn'], 'namespace': 'default'})[2],
            's3tables.DeleteTable': lambda store: (
                bucket := store.create_table_bucket(name='s3t-dt-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                store.create_table(bucket['arn'], 'default', 'del-table', format='ICEBERG'),  # noqa: E501
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'del-table'})[3],  # noqa: E501
            'RenameTable': lambda store: (
                bucket := store.create_table_bucket(name='s3t-rt-bucket'),
                store.create_namespace(bucket['arn'], ['default']),
                store.create_table(bucket['arn'], 'default', 'old-table', format='ICEBERG'),  # noqa: E501
                {'tableBucketARN': bucket['arn'], 'namespace': 'default', 'name': 'old-table', 'newNamespaceName': 'default', 'newName': 'new-table'})[3],  # noqa: E501
            's3tables.TagResource': lambda store: (
                bucket := store.create_table_bucket(name='s3t-tr-bucket'),
                {'resourceArn': bucket['arn'], 'tags': {'env': 'test'}})[1],
            's3tables.UntagResource': lambda store: (
                bucket := store.create_table_bucket(name='s3t-utr-bucket'),
                store.tag_resource(bucket['arn'], {'env': 'test'}),
                {'resourceArn': bucket['arn'], 'tagKeys': ['env']})[2],
            's3tables.ListTagsForResource': lambda store: (
                bucket := store.create_table_bucket(name='s3t-ltr-bucket'),
                store.tag_resource(bucket['arn'], {'env': 'test'}),
                {'resourceArn': bucket['arn']})[2],
            'RunJobFlow': {'Name': 'emr-shape-test'},
            'ListClusters': {},
            'DescribeCluster': lambda store: (
                cluster := store.run_job_flow(Name='emr-desc'),
                {'ClusterId': cluster.Id})[1],
            'TerminateJobFlows': lambda store: (
                cluster := store.run_job_flow(Name='emr-term'),
                {'JobFlowIds': [cluster.Id]})[1],
            'ListInstanceFleets': lambda store: (
                cluster := store.run_job_flow(Name='emr-lif'),
                {'ClusterId': cluster.Id})[1],
            'ListInstanceGroups': lambda store: (
                cluster := store.run_job_flow(Name='emr-lig'),
                {'ClusterId': cluster.Id})[1],
            'ListSteps': lambda store: (
                cluster := store.run_job_flow(Name='emr-ls'),
                {'ClusterId': cluster.Id})[1],
            'AddInstanceFleet': lambda store: (
                cluster := store.run_job_flow(Name='emr-aif'),
                {'ClusterId': cluster.Id, 'InstanceFleet': {'Name': 'core', 'InstanceFleetType': 'CORE', 'TargetOnDemandCapacity': 1, 'InstanceTypeConfigs': [{'InstanceType': 'm5.xlarge'}]}})[1],  # noqa: E501
            'AddInstanceGroups': lambda store: (
                cluster := store.run_job_flow(Name='emr-aig'),
                {'JobFlowId': cluster.Id, 'InstanceGroups': [{'Name': 'master', 'InstanceRole': 'MASTER', 'InstanceType': 'm5.xlarge', 'InstanceCount': 1}]})[1],  # noqa: E501
            'AddJobFlowSteps': lambda store: (
                cluster := store.run_job_flow(Name='emr-ajfs'),
                {'JobFlowId': cluster.Id, 'Steps': [{'Name': 'test-step', 'ActionOnFailure': 'CONTINUE', 'HadoopJarStep': {'Jar': 'command-runner.jar', 'Args': ['echo', 'test']}}]})[1],  # noqa: E501
            'CancelSteps': lambda store: (
                cluster := store.run_job_flow(Name='emr-cancel'),
                step := store.add_job_flow_steps(cluster.Id, [{'Name': 'cancel-step', 'ActionOnFailure': 'CONTINUE', 'HadoopJarStep': {'Jar': 'command-runner.jar', 'Args': ['echo', 'test']}}]),  # noqa: E501
                {'ClusterId': cluster.Id, 'StepIds': [step[0].Id]})[2],
            'DescribeStep': lambda store: (
                cluster := store.run_job_flow(Name='emr-dstep'),
                steps := store.add_job_flow_steps(cluster.Id, [{'Name': 'desc-step', 'ActionOnFailure': 'CONTINUE', 'HadoopJarStep': {'Jar': 'command-runner.jar', 'Args': ['echo', 'test']}}]),  # noqa: E501
                {'ClusterId': cluster.Id, 'StepId': steps[0].Id})[2],
            'ModifyInstanceFleet': lambda store: (
                cluster := store.run_job_flow(Name='emr-mif'),
                fleet := store.add_instance_fleet(cluster.Id, {'Name': 'core', 'InstanceFleetType': 'CORE', 'TargetOnDemandCapacity': 1, 'InstanceTypeConfigs': [{'InstanceType': 'm5.xlarge'}]}),  # noqa: E501
                {'ClusterId': cluster.Id, 'InstanceFleet': {'InstanceFleetId': fleet.Id, 'TargetOnDemandCapacity': 2}})[2],  # noqa: E501
            'ModifyInstanceGroups': lambda store: (
                cluster := store.run_job_flow(Name='emr-mig'),
                groups := store.add_instance_groups(cluster.Id, [{'Name': 'master', 'InstanceRole': 'MASTER', 'InstanceType': 'm5.xlarge', 'InstanceCount': 1}]),  # noqa: E501
                {'ClusterId': cluster.Id, 'InstanceGroups': [{'InstanceGroupId': groups[0].Id, 'InstanceCount': 2}]})[2],  # noqa: E501
}
