# Test inputs for servicecatalog
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreatePortfolio': {'DisplayName': 'TestPortfolio', 'ProviderName': 'TestProvider'},  # noqa: E501
            'CreateProduct': {'Name': 'TestProduct', 'Owner': 'TestOwner', 'ProductType': 'CLOUD_FORMATION_TEMPLATE'},  # noqa: E501
            'CreateTagOption': {'Key': 'env', 'Value': 'test'},
            'CreateConstraint': lambda store: (
                pf := store.create_portfolio('sc-cs-pf', 'sc-cs-prov'),
                pd := store.create_product('sc-cs-pd', 'sc-cs-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'PortfolioId': pf['Id'], 'ProductId': pd['Id'],
                 'Type': 'TEMPLATE', 'Parameters': '{}'})[2],
            'CreateProvisioningArtifact': lambda store: (
                pd := store.create_product('sc-cpa-pd', 'sc-cpa-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'ProductId': pd['Id'], 'Parameters': {'Name': 'v1', 'Info': {'LoadTemplateFromURL': 'https://example.com/template'}}})[1],  # noqa: E501
            'AssociateProductWithPortfolio': lambda store: (
                pf := store.create_portfolio('sc-as-pf', 'sc-as-prov'),
                pd := store.create_product('sc-as-pd', 'sc-as-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'PortfolioId': pf['Id'], 'ProductId': pd['Id']})[2],
            'ProvisionProduct': lambda store: (
                pd := store.create_product('sc-prov-pd', 'sc-prov-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                {'ProductId': pd['Id'], 'ProvisionedProductName': 'TestPP',
                 'ProvisioningArtifactId': pa['Id']})[2],
            'ListPortfolios': {},
            'SearchProducts': {},
            'SearchProductsAsAdmin': {},
            'ListTagOptions': {},
            'ListProvisioningArtifacts': lambda store: (
                pd := store.create_product('sc-lpa-pd', 'sc-lpa-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                store.create_provisioning_artifact(pd['Id'], 'v1'),
                {'ProductId': pd['Id']})[2],
            'DescribePortfolio': lambda store: (
                pf := store.create_portfolio('sc-dp-pf', 'sc-dp-prov'),
                {'Id': pf['Id']})[1],
            'DescribeProduct': lambda store: (
                pd := store.create_product('sc-dpd-pd', 'sc-dpd-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'Id': pd['Id']})[1],
            'DescribeConstraint': lambda store: (
                pf := store.create_portfolio('sc-dc-pf', 'sc-dc-prov'),
                pd := store.create_product('sc-dc-pd', 'sc-dc-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                ct := store.create_constraint(pf['Id'], pd['Id'], 'TEMPLATE', '{}'),  # noqa: E501
                {'Id': ct['ConstraintId']})[3],
            'DescribeProvisioningArtifact': lambda store: (
                pd := store.create_product('sc-dpa-pd', 'sc-dpa-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                {'ProductId': pd['Id'], 'ProvisioningArtifactId': pa['Id']})[2],  # noqa: E501
            'DescribeProvisionedProduct': lambda store: (
                pd := store.create_product('sc-dpp-pd', 'sc-dpp-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                pp := store.provision_product(pd['Id'], 'TestPP', pa['Id']),
                {'Id': pp['Id']})[3],
            'DeletePortfolio': lambda store: (
                pf := store.create_portfolio('sc-del-pf', 'sc-del-prov'),
                {'Id': pf['Id']})[1],
            'DeleteProduct': lambda store: (
                pd := store.create_product('sc-del-pd', 'sc-del-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'Id': pd['Id']})[1],
            'DeleteConstraint': lambda store: (
                pf := store.create_portfolio('sc-del-ct-pf', 'sc-del-ct-prov'),
                pd := store.create_product('sc-del-ct-pd', 'sc-del-ct-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                ct := store.create_constraint(pf['Id'], pd['Id'], 'TEMPLATE', '{}'),  # noqa: E501
                {'Id': ct['ConstraintId']})[3],
            'DeleteProvisioningArtifact': lambda store: (
                pd := store.create_product('sc-del-pa-pd', 'sc-del-pa-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                {'ProductId': pd['Id'], 'ProvisioningArtifactId': pa['Id']})[2],  # noqa: E501
            'DisassociateProductFromPortfolio': lambda store: (
                pf := store.create_portfolio('sc-dis-pf', 'sc-dis-prov'),
                pd := store.create_product('sc-dis-pd', 'sc-dis-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                store.associate_product_with_portfolio(pf['Id'], pd['Id']),
                {'PortfolioId': pf['Id'], 'ProductId': pd['Id']})[3],
            'TerminateProvisionedProduct': lambda store: (
                pd := store.create_product('sc-term-pd', 'sc-term-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                pp := store.provision_product(pd['Id'], 'TestPP', pa['Id']),
                {'ProvisionedProductId': pp['Id']})[3],
            'UpdatePortfolio': lambda store: (
                pf := store.create_portfolio('sc-upd-pf', 'sc-upd-prov'),
                {'Id': pf['Id'], 'DisplayName': 'UpdatedPortfolio', 'ProviderName': 'UpdatedProvider'})[1],  # noqa: E501
            'UpdateProduct': lambda store: (
                pd := store.create_product('sc-upd-pd', 'sc-upd-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                {'Id': pd['Id'], 'Name': 'UpdatedProduct', 'Owner': 'UpdatedOwner'})[1],  # noqa: E501
            'UpdateProvisionedProduct': lambda store: (
                pd := store.create_product('sc-upp-pd', 'sc-upp-owner', 'CLOUD_FORMATION_TEMPLATE'),  # noqa: E501
                pa := store.create_provisioning_artifact(pd['Id'], 'v1'),
                pp := store.provision_product(pd['Id'], 'TestPP', pa['Id']),
                {'ProvisionedProductId': pp['Id']})[3],
}
