# Test inputs for sesv2
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateContactList': {'ContactListName': 'sesv2-shape-cl'},
            'ListContactLists': {},
            'GetContactList': lambda store: (
                store.create_contact_list(ContactListName='sesv2-gcl'),
                {'ContactListName': 'sesv2-gcl'})[1],
            'DeleteContactList': lambda store: (
                store.create_contact_list(ContactListName='sesv2-dcl'),
                {'ContactListName': 'sesv2-dcl'})[1],
            'CreateContact': lambda store: (
                store.create_contact_list(ContactListName='sesv2-contacts'),
                {'ContactListName': 'sesv2-contacts', 'EmailAddress': 'test@example.com'})[1],  # noqa: E501
            'ListContacts': lambda store: (
                store.create_contact_list(ContactListName='sesv2-lc'),
                {'ContactListName': 'sesv2-lc'})[1],
            'GetContact': lambda store: (
                store.create_contact_list(ContactListName='sesv2-gc'),
                store.create_contact(ContactListName='sesv2-gc', EmailAddress='get@example.com'),  # noqa: E501
                {'ContactListName': 'sesv2-gc', 'EmailAddress': 'get@example.com'})[2],  # noqa: E501
            'UpdateContact': lambda store: (
                store.create_contact_list(ContactListName='sesv2-uc'),
                store.create_contact(ContactListName='sesv2-uc', EmailAddress='upd@example.com'),  # noqa: E501
                {'ContactListName': 'sesv2-uc', 'EmailAddress': 'upd@example.com', 'UnsubscribeAll': True})[2],  # noqa: E501
            'DeleteContact': lambda store: (
                store.create_contact_list(ContactListName='sesv2-dc'),
                store.create_contact(ContactListName='sesv2-dc', EmailAddress='del@example.com'),  # noqa: E501
                {'ContactListName': 'sesv2-dc', 'EmailAddress': 'del@example.com'})[2],  # noqa: E501
            'CreateEmailIdentity': {'EmailIdentity': 'test@sesv2-shape.example.com'},  # noqa: E501
            'ListEmailIdentities': {},
            'GetEmailIdentity': lambda store: (
                store.create_email_identity(EmailIdentity='get@sesv2-shape.example.com'),  # noqa: E501
                {'EmailIdentity': 'get@sesv2-shape.example.com'})[1],
            'DeleteEmailIdentity': lambda store: (
                store.create_email_identity(EmailIdentity='del@sesv2-shape.example.com'),  # noqa: E501
                {'EmailIdentity': 'del@sesv2-shape.example.com'})[1],
            'CreateEmailTemplate': {
                'TemplateName': 'sesv2-shape-template',
                'TemplateContent': {'Subject': 'Test', 'Text': 'Hello', 'Html': '<p>Hello</p>'},  # noqa: E501
            },
            'ListEmailTemplates': {},
            'GetEmailTemplate': lambda store: (
                store.create_email_template(TemplateName='sesv2-get', TemplateContent={'Subject': 'T', 'Text': 'B', 'Html': 'B'}),  # noqa: E501
                {'TemplateName': 'sesv2-get'})[1],
            'UpdateEmailTemplate': lambda store: (
                store.create_email_template(TemplateName='sesv2-upd', TemplateContent={'Subject': 'Old', 'Text': 'Old', 'Html': 'Old'}),  # noqa: E501
                {'TemplateName': 'sesv2-upd', 'TemplateContent': {'Subject': 'New', 'Text': 'New', 'Html': 'New'}})[1],  # noqa: E501
            'DeleteEmailTemplate': lambda store: (
                store.create_email_template(TemplateName='sesv2-del', TemplateContent={'Subject': 'D', 'Text': 'D', 'Html': 'D'}),  # noqa: E501
                {'TemplateName': 'sesv2-del'})[1],
            'CreateConfigurationSet': {'ConfigurationSetName': 'sesv2-shape-cs'},  # noqa: E501
            'ListConfigurationSets': {},
            'GetConfigurationSet': lambda store: (
                store.create_configuration_set(ConfigurationSetName='sesv2-gcs'),  # noqa: E501
                {'ConfigurationSetName': 'sesv2-gcs'})[1],
            'DeleteConfigurationSet': lambda store: (
                store.create_configuration_set(ConfigurationSetName='sesv2-dcs'),  # noqa: E501
                {'ConfigurationSetName': 'sesv2-dcs'})[1],
            'SendEmail': {
                'FromEmailAddress': 'sender@example.com',
                'Destination': {'ToAddresses': ['recipient@example.com']},
                'Content': {'Simple': {'Subject': {'Data': 'Test'}, 'Body': {'Text': {'Data': 'Hello'}}}},  # noqa: E501
            },
}
