# Test inputs for shield
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateProtection': {'Name': 's-test-protection',
                                 'ResourceArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-test/abc'},  # noqa: E501
            'CreateProtectionGroup': {'ProtectionGroupId': 's-test-pg',
                                      'Aggregation': 'SUM', 'Pattern': 'ARBITRARY'},  # noqa: E501
            'CreateSubscription': {},
            'DescribeDRTAccess': {},
            'DescribeEmergencyContactSettings': {},
            'GetSubscriptionState': {},
            'ListProtectionGroups': {},
            'ListProtections': {},
            'AssociateDRTRole': {'RoleArn': 'arn:aws:iam::123456789012:role/DRTAccess'},  # noqa: E501
            'DisassociateDRTRole': {},
            'AssociateProactiveEngagementDetails': {'EmergencyContactList': [{'EmailAddress': 'test@example.com'}]},  # noqa: E501
            'UpdateEmergencyContactSettings': {'EmergencyContactList': [{'EmailAddress': 'updated@example.com'}]},  # noqa: E501
            'EnableApplicationLayerAutomaticResponse': {'ResourceArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-test-app/abc',  # noqa: E501
                                                          'Action': 'COUNT'},
            'DescribeProtection': lambda store: (
                store.create_protection(name='s-desc-prot', resource_arn='arn:aws:shield::123456789012:resource/s-desc-prot'),  # noqa: E501
                {'ResourceArn': 'arn:aws:shield::123456789012:resource/s-desc-prot'})[1],  # noqa: E501
            'DescribeProtectionGroup': lambda store: (
                store.create_protection_group('s-desc-pg', aggregation='SUM', pattern='ARBITRARY'),  # noqa: E501
                {'ProtectionGroupId': 's-desc-pg'})[1],
            'DescribeSubscription': lambda store: (
                (store.create_subscription() if store.subscription is None else None),  # noqa: E501
                {})[1],
            'DeleteProtection': lambda store: (
                store.create_protection(name='s-del-prot', resource_arn='arn:aws:shield::123456789012:resource/s-del-prot'),  # noqa: E501
                {'ProtectionId': [p.id for p in store.protections.values()
                                  if p.resource_arn == 'arn:aws:shield::123456789012:resource/s-del-prot'][0]})[1],  # noqa: E501
            'DeleteProtectionGroup': lambda store: (
                store.create_protection_group('s-del-pg', aggregation='SUM', pattern='ARBITRARY'),  # noqa: E501
                {'ProtectionGroupId': 's-del-pg'})[1],
            'DeleteSubscription': lambda store: (
                (store.create_subscription() if store.subscription is None else None),  # noqa: E501
                {})[1],
            'UpdateProtectionGroup': lambda store: (
                store.create_protection_group('s-upd-pg', aggregation='SUM', pattern='ARBITRARY'),  # noqa: E501
                {'ProtectionGroupId': 's-upd-pg', 'Aggregation': 'SUM', 'Pattern': 'ARBITRARY'})[1],  # noqa: E501
            'UpdateSubscription': lambda store: (
                (store.create_subscription() if store.subscription is None else None),  # noqa: E501
                {'AutoRenew': 'ENABLED'})[1],
            'AssociateDRTLogBucket': lambda store: (
                store.associate_drt_role('arn:aws:iam::123456789012:role/DRTAccess'),  # noqa: E501
                {'LogBucket': 's-test-log-bucket-123'})[1],
            'DisassociateDRTLogBucket': lambda store: (
                store.associate_drt_role('arn:aws:iam::123456789012:role/DRTAccess'),  # noqa: E501
                store.associate_drt_log_bucket('s-disassoc-bucket'),
                {'LogBucket': 's-disassoc-bucket'})[2],
            'AssociateHealthCheck': lambda store: (
                store.create_protection(name='s-hc-prot', resource_arn='arn:aws:shield::123456789012:resource/s-hc-prot'),  # noqa: E501
                {'ProtectionId': [p.id for p in store.protections.values()
                                  if p.resource_arn == 'arn:aws:shield::123456789012:resource/s-hc-prot'][0],  # noqa: E501
                 'HealthCheckArn': 'arn:aws:route53:::healthcheck/s-test-hc'})[1],  # noqa: E501
            'DisassociateHealthCheck': lambda store: (
                store.create_protection(name='s-dhc-prot', resource_arn='arn:aws:shield::123456789012:resource/s-dhc-prot'),  # noqa: E501
                store.associate_health_check(
                    [p.id for p in store.protections.values()
                     if p.resource_arn == 'arn:aws:shield::123456789012:resource/s-dhc-prot'][0],  # noqa: E501
                    'arn:aws:route53:::healthcheck/s-dhc'),
                {'ProtectionId': [p.id for p in store.protections.values()
                                  if p.resource_arn == 'arn:aws:shield::123456789012:resource/s-dhc-prot'][0],  # noqa: E501
                 'HealthCheckArn': 'arn:aws:route53:::healthcheck/s-dhc'})[2],
            'EnableProactiveEngagement': lambda store: (
                (store.create_subscription() if store.subscription is None else None),  # noqa: E501
                {})[1],
            'DisableProactiveEngagement': lambda store: (
                (store.create_subscription() if store.subscription is None else None),  # noqa: E501
                {})[1],
            'DisableApplicationLayerAutomaticResponse': lambda store: (
                store.enable_application_layer_automatic_response(
                    'arn:aws:shield::123456789012:resource/s-disable-app', 'COUNT'),  # noqa: E501
                {'ResourceArn': 'arn:aws:shield::123456789012:resource/s-disable-app'})[1],  # noqa: E501
            'UpdateApplicationLayerAutomaticResponse': lambda store: (
                store.enable_application_layer_automatic_response(
                    'arn:aws:shield::123456789012:resource/s-update-app', 'COUNT'),  # noqa: E501
                {'ResourceArn': 'arn:aws:shield::123456789012:resource/s-update-app',  # noqa: E501
                 'Action': 'BLOCK'})[1],
            'ListResourcesInProtectionGroup': lambda store: (
                store.create_protection_group('s-listr-pg', aggregation='SUM', pattern='ARBITRARY',  # noqa: E501
                                               members=['arn:aws:shield::123456789012:resource/member1']),  # noqa: E501
                {'ProtectionGroupId': 's-listr-pg'})[1],
            'shield.TagResource': lambda store: (
                store.create_protection(name='s-tag-prot', resource_arn='arn:aws:shield::123456789012:resource/s-tag-prot'),  # noqa: E501
                {'ResourceARN': 'arn:aws:shield::123456789012:resource/s-tag-prot',  # noqa: E501
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'shield.UntagResource': lambda store: (
                store.create_protection(name='s-untag-prot', resource_arn='arn:aws:shield::123456789012:resource/s-untag-prot'),  # noqa: E501
                store.tag_resource('arn:aws:shield::123456789012:resource/s-untag-prot', [{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                {'ResourceARN': 'arn:aws:shield::123456789012:resource/s-untag-prot',  # noqa: E501
                 'TagKeys': ['env']})[2],
            'shield.ListTagsForResource': lambda store: (
                store.create_protection(name='s-ltf-prot', resource_arn='arn:aws:shield::123456789012:resource/s-ltf-prot'),  # noqa: E501
                store.tag_resource('arn:aws:shield::123456789012:resource/s-ltf-prot', [{'Key': 'env', 'Value': 'test'}]),  # noqa: E501
                {'ResourceARN': 'arn:aws:shield::123456789012:resource/s-ltf-prot'})[2],  # noqa: E501
}
