# Test inputs for signer
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'PutSigningProfile': {'platformId': 'AWSLambda-SHA384-ECDSA',
                'profileName': 'test-profile'},
            'GetSigningProfile': lambda store: (
                p := store.create_profile(profileName='gs-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'gs-profile'}
            )[1],
            'ListSigningProfiles': {},
            'CancelSigningProfile': lambda store: (
                p := store.create_profile(profileName='cs-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'cs-profile'}
            )[1],
            'RevokeSigningProfile': lambda store: (
                p := store.create_profile(profileName='rs-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'rs-profile',
                 'profileVersion': p.profileVersion,
                 'reason': 'test-revocation',
                 'effectiveTime': 1700000000}
            )[1],
            'GetSigningPlatform': {'platformId': 'AWSLambda-SHA384-ECDSA'},
            'ListSigningPlatforms': {},
            'StartSigningJob': lambda store: (
                p := store.create_profile(profileName='sj-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'source': {'s3': {'bucketName': 'test-bucket', 'key': 'test.zip',  # noqa: E501
                    'version': '1'}},
                 'destination': {'s3': {'bucketName': 'out-bucket', 'prefix': 'signed/'}},  # noqa: E501
                 'profileName': 'sj-profile',
                 'clientRequestToken': 'token-12345'}
            )[1],
            'DescribeSigningJob': lambda store: (
                p := store.create_profile(profileName='dj-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                j := store.start_job(
                    source={'s3': {'bucketName': 'tb', 'key': 'x.zip', 'version': '1'}},  # noqa: E501
                    destination={'s3': {'bucketName': 'ob', 'prefix': 's/'}},
                    profileName='dj-profile',
                    clientRequestToken='token-dj'),
                {'jobId': j.jobId}
            )[2],
            'ListSigningJobs': {},
            'RevokeSignature': lambda store: (
                p := store.create_profile(profileName='rvs-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                j := store.start_job(
                    source={'s3': {'bucketName': 'tb2', 'key': 'y.zip', 'version': '1'}},  # noqa: E501
                    destination={'s3': {'bucketName': 'ob2', 'prefix': 's/'}},
                    profileName='rvs-profile',
                    clientRequestToken='token-rvs'),
                {'jobId': j.jobId, 'reason': 'test-revoke'}
            )[2],
            'SignPayload': lambda store: (
                p := store.create_profile(profileName='sp-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'sp-profile',
                 'payload': b'test-payload',
                 'payloadFormat': 'JSON'}
            )[1],
            'AddProfilePermission': lambda store: (
                p := store.create_profile(profileName='ap-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'ap-profile',
                 'action': 'signer:StartSigningJob',
                 'principal': '123456789012',
                 'statementId': 'stmt-001'}
            )[1],
            'RemoveProfilePermission': lambda store: (
                p := store.create_profile(profileName='rp-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                rev := store.add_permission(profileName='rp-profile',
                    action='signer:StartSigningJob', principal='123456789012',
                    statementId='stmt-001'),
                {'profileName': 'rp-profile',
                 'statementId': 'stmt-001',
                 'revisionId': rev}
            )[2],
            'ListProfilePermissions': lambda store: (
                p := store.create_profile(profileName='lp-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'profileName': 'lp-profile'}
            )[1],
            'GetRevocationStatus': lambda store: (
                p := store.create_profile(profileName='grs-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                j := store.start_job(
                    source={'s3': {'bucketName': 'tb3', 'key': 'z.zip', 'version': '1'}},  # noqa: E501
                    destination={'s3': {'bucketName': 'ob3', 'prefix': 's/'}},
                    profileName='grs-profile',
                    clientRequestToken='token-grs'),
                {'signatureTimestamp': 1700000000,
                 'platformId': 'AWSLambda-SHA384-ECDSA',
                 'profileVersionArn': p.profileVersionArn,
                 'jobArn': f'arn:aws:signer:us-east-1:123456789012:/signing-jobs/{j.jobId}',  # noqa: E501
                 'certificateHashes': ['sha256hash']}
            )[2],
            'signer.TagResource': lambda store: (
                p := store.create_profile(profileName='str-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'resourceArn': p.arn,
                 'tags': [{'key': 'test', 'value': 'val'}]}
            )[1],
            'signer.UntagResource': lambda store: (
                p := store.create_profile(profileName='sur-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                store.tag_resource(resourceArn=p.arn,
                    tags={'test': 'val'}),
                {'resourceArn': p.arn,
                 'tagKeys': ['test']}
            )[2],
            'signer.ListTagsForResource': lambda store: (
                p := store.create_profile(profileName='sltr-profile',
                    platformId='AWSLambda-SHA384-ECDSA'),
                {'resourceArn': p.arn}
            )[1],
}
