# Test inputs for ssm
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'ssm.PutParameter': {'Name': 'ssm-test-param', 'Value': 'test-value', 'Type': 'String'},  # noqa: E501
            'ssm.AddTagsToResource': lambda store: (
                store.put_parameter('ssm-tag-param', 'val', 'String'),
                {'ResourceId': 'ssm-tag-param', 'ResourceType': 'Parameter', 'Tags': [{'Key': 'env', 'Value': 'test'}]}  # noqa: E501
            )[1],
            'ssm.DescribeParameters': {},
            'ssm.GetParameters': {'Names': ['ssm-test-param']},
            'ssm.ListTagsForResource': lambda store: (
                store.put_parameter('ssm-lt-param', 'val', 'String'),
                {'ResourceId': 'ssm-lt-param', 'ResourceType': 'Parameter'}
            )[1],
            'ssm.GetParameter': lambda store: (
                store.put_parameter('ssm-get-param', 'get-val', 'String'),
                {'Name': 'ssm-get-param'}
            )[1],
            'ssm.GetParameterHistory': lambda store: (
                store.put_parameter('ssm-hist-param', 'hist-val', 'String'),
                {'Name': 'ssm-hist-param'}
            )[1],
            'ssm.DeleteParameter': lambda store: (
                store.put_parameter('ssm-del-param', 'del-val', 'String'),
                {'Name': 'ssm-del-param'}
            )[1],
            'ssm.RemoveTagsFromResource': lambda store: (
                store.put_parameter('ssm-rt-param', 'rt-val', 'String'),
                {'ResourceId': 'ssm-rt-param', 'ResourceType': 'Parameter', 'TagKeys': ['test']}  # noqa: E501
            )[1],
}
