# Test inputs for sso-admin
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateInstance': {'name': 's-create-inst'},
            'CreateAccountAssignment': lambda store: (
                ia := store.create_instance(name='s-caa-inst')['instanceArn'],
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'targetId': '111111111111', 'targetType': 'AWS_ACCOUNT',  # noqa: E501
                 'permissionSetArn': psa, 'principalType': 'USER', 'principalId': 'test-user-id'})[3],  # noqa: E501
            'CreatePermissionSet': lambda store: (
                ia := store.create_instance(name='s-cps-inst')['instanceArn'],
                {'name': 'test-ps', 'instanceArn': ia})[1],
            'CreateApplication': lambda store: (
                ia := store.create_instance(name='s-cap-inst')['instanceArn'],
                {'instanceArn': ia, 'applicationProviderArn': 'arn:aws:sso::aws:applicationProvider/custom',  # noqa: E501
                 'name': 'test-app'})[1],
            'ListInstances': {},
            'ListPermissionSets': lambda store: (
                ia := store.create_instance(name='s-lps-inst')['instanceArn'],
                {'instanceArn': ia})[1],
            'ListAccountAssignments': lambda store: (
                ia := store.create_instance(name='s-laa-inst')['instanceArn'],
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'accountId': '111111111111', 'permissionSetArn': psa})[3],  # noqa: E501
            'ListAccountAssignmentsForPrincipal': lambda store: (
                ia := store.create_instance(name='s-lafp-inst')['instanceArn'],
                {'instanceArn': ia, 'principalId': 'test-principal', 'principalType': 'USER'})[1],  # noqa: E501
            'ListApplications': lambda store: (
                ia := store.create_instance(name='s-lapp-inst')['instanceArn'],
                {'instanceArn': ia})[1],
            'ListManagedPoliciesInPermissionSet': lambda store: (
                ia := store.create_instance(name='s-lmpip-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa})[3],
            'DescribeInstance': lambda store: (
                ia := store.create_instance(name='s-di-inst')['instanceArn'],
                {'instanceArn': ia})[1],
            'DescribePermissionSet': lambda store: (
                ia := store.create_instance(name='s-dps-inst')['instanceArn'],
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa})[3],
            'DescribeAccountAssignmentCreationStatus': lambda store: (
                ia := store.create_instance(name='s-daacs-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                result := store.create_account_assignment(ia, '111111111111', 'AWS_ACCOUNT', psa, 'USER', 'test-user-id'),  # noqa: E501
                req_id := result['accountAssignmentCreationStatus']['requestId'],  # noqa: E501
                {'instanceArn': ia, 'accountAssignmentCreationRequestId': req_id})[5],  # noqa: E501
            'DescribeAccountAssignmentDeletionStatus': lambda store: (
                ia := store.create_instance(name='s-daads-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                result := store.create_account_assignment(ia, '111111111111', 'AWS_ACCOUNT', psa, 'USER', 'test-user-id'),  # noqa: E501
                req_id := result['accountAssignmentCreationStatus']['requestId'],  # noqa: E501
                {'instanceArn': ia, 'accountAssignmentDeletionRequestId': req_id})[5],  # noqa: E501
            'DescribeApplication': lambda store: (
                ia := store.create_instance(name='s-da-inst')['instanceArn'],
                app := store.create_application(ia, 'arn:aws:sso::aws:applicationProvider/custom', 'test-app'),  # noqa: E501
                app_arn := app['applicationArn'],
                {'applicationArn': app_arn})[3],
            'DeleteInstance': lambda store: (
                ia := store.create_instance(name='s-deli-inst')['instanceArn'],
                {'instanceArn': ia})[1],
            'DeletePermissionSet': lambda store: (
                ia := store.create_instance(name='s-delps-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa})[3],
            'DeleteAccountAssignment': lambda store: (
                ia := store.create_instance(name='s-daa-inst')['instanceArn'],
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                store.create_account_assignment(ia, '111111111111', 'AWS_ACCOUNT', psa, 'USER', 'test-user-id'),  # noqa: E501
                {'instanceArn': ia, 'targetId': '111111111111', 'targetType': 'AWS_ACCOUNT',  # noqa: E501
                 'permissionSetArn': psa, 'principalType': 'USER', 'principalId': 'test-user-id'})[4],  # noqa: E501
            'DeleteApplication': lambda store: (
                ia := store.create_instance(name='s-delapp-inst')['instanceArn'],  # noqa: E501
                app := store.create_application(ia, 'arn:aws:sso::aws:applicationProvider/custom', 'test-app'),  # noqa: E501
                app_arn := app['applicationArn'],
                {'applicationArn': app_arn})[3],
            'DeleteInlinePolicyFromPermissionSet': lambda store: (
                ia := store.create_instance(name='s-dipfp-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa})[3],
            'UpdateInstance': lambda store: (
                ia := store.create_instance(name='s-ui-inst')['instanceArn'],
                {'instanceArn': ia, 'name': 'updated-name'})[1],
            'UpdatePermissionSet': lambda store: (
                ia := store.create_instance(name='s-ups-inst')['instanceArn'],
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa, 'description': 'updated desc'})[3],  # noqa: E501
            'UpdateApplication': lambda store: (
                ia := store.create_instance(name='s-ua-inst')['instanceArn'],
                app := store.create_application(ia, 'arn:aws:sso::aws:applicationProvider/custom', 'test-app'),  # noqa: E501
                app_arn := app['applicationArn'],
                {'applicationArn': app_arn, 'name': 'updated-app'})[3],
            'PutInlinePolicyToPermissionSet': lambda store: (
                ia := store.create_instance(name='s-piptp-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa,
                 'inlinePolicy': '{"Version":"2012-10-17","Statement":[]}'})[3],  # noqa: E501
            'GetInlinePolicyForPermissionSet': lambda store: (
                ia := store.create_instance(name='s-gipfp-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa})[3],
            'AttachManagedPolicyToPermissionSet': lambda store: (
                ia := store.create_instance(name='s-amptp-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                {'instanceArn': ia, 'permissionSetArn': psa,
                 'managedPolicyArn': 'arn:aws:iam::aws:policy/ReadOnlyAccess'})[3],  # noqa: E501
            'DetachManagedPolicyFromPermissionSet': lambda store: (
                ia := store.create_instance(name='s-dmpfp-inst')['instanceArn'],  # noqa: E501
                ps := store.create_permission_set('test-ps', ia),
                psa := ps['permissionSetArn'],
                store.attach_managed_policy_to_permission_set(ia, psa, 'arn:aws:iam::aws:policy/ReadOnlyAccess'),  # noqa: E501
                {'instanceArn': ia, 'permissionSetArn': psa,
                 'managedPolicyArn': 'arn:aws:iam::aws:policy/ReadOnlyAccess'})[4],  # noqa: E501
            'sso-admin.TagResource': lambda store: (
                ia := store.create_instance(name='s-tagr-inst')['instanceArn'],
                {'resourceArn': ia, 'tags': [{'Key': 'env', 'Value': 'test'}]})[1],  # noqa: E501
            'sso-admin.UntagResource': lambda store: (
                ia := store.create_instance(name='s-untagr-inst')['instanceArn'],  # noqa: E501
                {'resourceArn': ia, 'tagKeys': ['env']})[1],
            'sso-admin.ListTagsForResource': lambda store: (
                ia := store.create_instance(name='s-ltfr-inst')['instanceArn'],
                {'resourceArn': ia})[1],
}
