# Test inputs for storagegateway
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'ActivateGateway': {'ActivationKey': 'test-key-12345'},
            'DescribeGatewayInformation': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dgi-key'),
                {'GatewayARN': g['GatewayARN']}
            )[1],
            'ListGateways': {},
            'DeleteGateway': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dg-key'),
                {'GatewayARN': g['GatewayARN']}
            )[1],
            'CreateNFSFileShare': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-nfs-key'),
                {'GatewayARN': g['GatewayARN'], 'Role': 'arn:aws:iam::000000000000:role/test',  # noqa: E501
                 'LocationARN': 'arn:aws:s3:::test-bucket'}
            )[1],
            'CreateSMBFileShare': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-smb-key'),
                {'GatewayARN': g['GatewayARN'], 'Role': 'arn:aws:iam::000000000000:role/test',  # noqa: E501
                 'LocationARN': 'arn:aws:s3:::test-bucket'}
            )[1],
            'DescribeNFSFileShares': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dnfs-key'),
                fs := store.create_nfs_file_share(GatewayARN=g['GatewayARN'],
                    Role='arn:aws:iam::000000000000:role/test', LocationARN='arn:aws:s3:::test'),  # noqa: E501
                {'FileShareARNList': [fs['FileShareARN']]}
            )[2],
            'ListFileShares': {},
            'DeleteFileShare': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dfs-key'),
                fs := store.create_nfs_file_share(GatewayARN=g['GatewayARN'],
                    Role='arn:aws:iam::000000000000:role/test', LocationARN='arn:aws:s3:::test'),  # noqa: E501
                {'FileShareARN': fs['FileShareARN']}
            )[2],
            'CreateCachediSCSIVolume': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-vol-key'),
                {'GatewayARN': g['GatewayARN'], 'VolumeSizeInBytes': 107374182400,  # noqa: E501
                 'TargetName': 'iqn.test-target'}
            )[1],
            'DescribeCachediSCSIVolumes': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dv-key'),
                v := store.create_cached_iscsi_volume(GatewayARN=g['GatewayARN'],  # noqa: E501
                    VolumeSizeInBytes=107374182400, TargetName='iqn.dv-target'),  # noqa: E501
                {'VolumeARNs': [v['VolumeARN']]}
            )[2],
            'ListVolumes': {},
            'DeleteVolume': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-delv-key'),
                v := store.create_cached_iscsi_volume(GatewayARN=g['GatewayARN'],  # noqa: E501
                    VolumeSizeInBytes=107374182400, TargetName='iqn.delv-target'),  # noqa: E501
                {'VolumeARN': v['VolumeARN']}
            )[2],
            'CreateTapes': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-tape-key'),
                {'GatewayARN': g['GatewayARN'], 'TapeSizeInBytes': 107374182400,  # noqa: E501
                 'ClientToken': 'test-token', 'NumTapesToCreate': 1}
            )[1],
            'DescribeTapes': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-dt-key'),
                t := store.create_tapes(GatewayARN=g['GatewayARN'],
                    TapeSizeInBytes=107374182400, ClientToken='dt-token', NumTapesToCreate=1),  # noqa: E501
                {'TapeARNs': t['TapeARNs']}
            )[2],
            'ListTapes': {},
            'DeleteTape': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-delt-key'),
                t := store.create_tapes(GatewayARN=g['GatewayARN'],
                    TapeSizeInBytes=107374182400, ClientToken='delt-token', NumTapesToCreate=1),  # noqa: E501
                {'GatewayARN': g['GatewayARN'], 'TapeARN': t['TapeARNs'][0]}
            )[2],
            'storagegateway.AddTagsToResource': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-atr-key'),
                {'ResourceARN': g['GatewayARN'], 'Tags': [{'Key': 'test', 'Value': 'val'}]}  # noqa: E501
            )[1],
            'storagegateway.ListTagsForResource': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-ltr-key'),
                {'ResourceARN': g['GatewayARN']}
            )[1],
            'storagegateway.RemoveTagsFromResource': lambda store: (
                g := store.activate_gateway(ActivationKey='sg-rtr-key'),
                {'ResourceARN': g['GatewayARN'], 'TagKeys': ['test']}
            )[1],
}
