# Test inputs for textract
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'AnalyzeDocument': {'Document': {'Bytes': 'dGVzdA=='}, 'FeatureTypes': ['TABLES']},  # noqa: E501
            'AnalyzeExpense': {'Document': {'Bytes': 'dGVzdA=='}},
            'AnalyzeID': {'DocumentPages': [{'Document': {'Bytes': 'dGVzdA=='}}]},  # noqa: E501
            'DetectDocumentText': {'Document': {'Bytes': 'dGVzdA=='}},
            'CreateAdapter': {'AdapterName': 'tx-adapter', 'FeatureTypes': ['TABLES']},  # noqa: E501
            'ListAdapters': {},
            'GetAdapter': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-get-adapter', adapter_name='get-me', feature_types=['TABLES'])),  # noqa: E501
                {'AdapterId': 'tx-get-adapter'})[1],
            'UpdateAdapter': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-upd-adapter', adapter_name='update-me', feature_types=['TABLES'])),  # noqa: E501
                {'AdapterId': 'tx-upd-adapter', 'AdapterName': 'tx-updated', 'AutoUpdate': 'ENABLED'})[1],  # noqa: E501
            'DeleteAdapter': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-del-adapter', adapter_name='delete-me', feature_types=['TABLES'])),  # noqa: E501
                {'AdapterId': 'tx-del-adapter'})[1],
            'CreateAdapterVersion': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-ver-adapter', adapter_name='version-me', feature_types=['TABLES'])),  # noqa: E501
                {'AdapterId': 'tx-ver-adapter'})[1],
            'ListAdapterVersions': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-lv-adapter', adapter_name='list-versions', feature_types=['TABLES'])),  # noqa: E501
                {'AdapterId': 'tx-lv-adapter'})[1],
            'GetAdapterVersion': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-gv-adapter', adapter_name='get-version', feature_types=['TABLES'])),  # noqa: E501
                store.get_adapter('tx-gv-adapter').versions.__setitem__('1', AdapterVersionRecord(adapter_version='1', creation_time=0, status='ACTIVE')),  # noqa: E501
                {'AdapterId': 'tx-gv-adapter', 'AdapterVersion': '1'})[2],
            'DeleteAdapterVersion': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-dv-adapter', adapter_name='del-version', feature_types=['TABLES'])),  # noqa: E501
                store.get_adapter('tx-dv-adapter').versions.__setitem__('1', AdapterVersionRecord(adapter_version='1', creation_time=0)),  # noqa: E501
                {'AdapterId': 'tx-dv-adapter', 'AdapterVersion': '1'})[2],
            'StartDocumentAnalysis': {'DocumentLocation': {'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}}, 'FeatureTypes': ['TABLES']},  # noqa: E501
            'StartDocumentTextDetection': {'DocumentLocation': {'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}}},  # noqa: E501
            'StartExpenseAnalysis': {'DocumentLocation': {'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}}},  # noqa: E501
            'StartLendingAnalysis': {'DocumentLocation': {'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}}},  # noqa: E501
            'GetDocumentAnalysis': lambda store: (
                job := store.put_job(JobRecord(job_id='tx-da-job', api='StartDocumentAnalysis', document_location={'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}}, feature_types=['TABLES'])),  # noqa: E501
                {'JobId': 'tx-da-job'})[1],
            'GetDocumentTextDetection': lambda store: (
                job := store.put_job(JobRecord(job_id='tx-dtd-job', api='StartDocumentTextDetection', document_location={'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}})),  # noqa: E501
                {'JobId': 'tx-dtd-job'})[1],
            'GetExpenseAnalysis': lambda store: (
                job := store.put_job(JobRecord(job_id='tx-ea-job', api='StartExpenseAnalysis', document_location={'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}})),  # noqa: E501
                {'JobId': 'tx-ea-job'})[1],
            'GetLendingAnalysis': lambda store: (
                job := store.put_job(JobRecord(job_id='tx-la-job', api='StartLendingAnalysis', document_location={'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}})),  # noqa: E501
                {'JobId': 'tx-la-job'})[1],
            'GetLendingAnalysisSummary': lambda store: (
                job := store.put_job(JobRecord(job_id='tx-las-job', api='StartLendingAnalysis', document_location={'S3Object': {'Bucket': 'tx-bucket', 'Name': 'doc.pdf'}})),  # noqa: E501
                {'JobId': 'tx-las-job'})[1],
            'textract.TagResource': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-tag-adapter', adapter_name='tag-me', feature_types=['TABLES'])),  # noqa: E501
                {'ResourceARN': 'arn:aws:textract:us-east-1:000000000000:adapter/tx-tag-adapter', 'Tags': {'env': 'test'}})[1],  # noqa: E501
            'textract.UntagResource': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-untag-adapter', adapter_name='untag-me', feature_types=['TABLES'])),  # noqa: E501
                store.tag_resource('arn:aws:textract:us-east-1:000000000000:adapter/tx-untag-adapter', {'env': 'test'}),  # noqa: E501
                {'ResourceARN': 'arn:aws:textract:us-east-1:000000000000:adapter/tx-untag-adapter', 'TagKeys': ['env']})[2],  # noqa: E501
            'textract.ListTagsForResource': lambda store: (
                store.put_adapter(AdapterRecord(adapter_id='tx-ltr-adapter', adapter_name='ltr-me', feature_types=['TABLES'])),  # noqa: E501
                store.tag_resource('arn:aws:textract:us-east-1:000000000000:adapter/tx-ltr-adapter', {'env': 'test'}),  # noqa: E501
                {'ResourceARN': 'arn:aws:textract:us-east-1:000000000000:adapter/tx-ltr-adapter'})[2],  # noqa: E501
}
