# Test inputs for timestream-influxdb
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateDbCluster': {'name': 'test-cluster', 'dbInstanceType': 'db.influx.medium',  # noqa: E501
                'vpcSubnetIds': ['subnet-abc123'], 'vpcSecurityGroupIds': ['sg-abc123']},  # noqa: E501
            'GetDbCluster': lambda store: (
                c := store.create_db_cluster(name='ts-gc', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'dbClusterId': c['id']}
            )[1],
            'ListDbClusters': {},
            'DeleteDbCluster': lambda store: (
                c := store.create_db_cluster(name='ts-dc', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'dbClusterId': c['id']}
            )[1],
            'UpdateDbCluster': lambda store: (
                c := store.create_db_cluster(name='ts-uc', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'dbClusterId': c['id'], 'port': 8087}
            )[1],
            'RebootDbCluster': lambda store: (
                c := store.create_db_cluster(name='ts-rc', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'dbClusterId': c['id']}
            )[1],
            'CreateDbInstance': {'name': 'test-instance', 'password': 'TestPass123!',  # noqa: E501
                'dbInstanceType': 'db.influx.medium', 'vpcSubnetIds': ['subnet-abc123'],  # noqa: E501
                'vpcSecurityGroupIds': ['sg-abc123'], 'allocatedStorage': 400},
            'GetDbInstance': lambda store: (
                i := store.create_db_instance(name='ts-gi', password='TestPass123!',  # noqa: E501
                    dbInstanceType='db.influx.medium', vpcSubnetIds=['subnet-abc123'],  # noqa: E501
                    vpcSecurityGroupIds=['sg-abc123'], allocatedStorage=400),
                {'identifier': i['id']}
            )[1],
            'ListDbInstances': {},
            'ListDbInstancesForCluster': lambda store: (
                c := store.create_db_cluster(name='ts-lic', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'dbClusterId': c['id']}
            )[1],
            'DeleteDbInstance': lambda store: (
                i := store.create_db_instance(name='ts-di', password='TestPass123!',  # noqa: E501
                    dbInstanceType='db.influx.medium', vpcSubnetIds=['subnet-abc123'],  # noqa: E501
                    vpcSecurityGroupIds=['sg-abc123'], allocatedStorage=400),
                {'identifier': i['id']}
            )[1],
            'UpdateDbInstance': lambda store: (
                i := store.create_db_instance(name='ts-ui', password='TestPass123!',  # noqa: E501
                    dbInstanceType='db.influx.medium', vpcSubnetIds=['subnet-abc123'],  # noqa: E501
                    vpcSecurityGroupIds=['sg-abc123'], allocatedStorage=400),
                {'identifier': i['id'], 'port': 8087}
            )[1],
            'RebootDbInstance': lambda store: (
                i := store.create_db_instance(name='ts-ri', password='TestPass123!',  # noqa: E501
                    dbInstanceType='db.influx.medium', vpcSubnetIds=['subnet-abc123'],  # noqa: E501
                    vpcSecurityGroupIds=['sg-abc123'], allocatedStorage=400),
                {'identifier': i['id']}
            )[1],
            'CreateDbParameterGroup': {'name': 'test-pg'},
            'GetDbParameterGroup': lambda store: (
                pg := store.create_db_parameter_group(name='ts-gpg'),
                {'identifier': pg['id']}
            )[1],
            'ListDbParameterGroups': {},
            'timestream-influxdb.TagResource': lambda store: (
                c := store.create_db_cluster(name='ts-tag', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'resourceArn': c['arn'], 'tags': [{'key': 'test', 'value': 'val'}]}  # noqa: E501
            )[1],
            'timestream-influxdb.UntagResource': lambda store: (
                c := store.create_db_cluster(name='ts-ut', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'resourceArn': c['arn'], 'tagKeys': ['test']}
            )[1],
            'timestream-influxdb.ListTagsForResource': lambda store: (
                c := store.create_db_cluster(name='ts-ltr', dbInstanceType='db.influx.medium',  # noqa: E501
                    vpcSubnetIds=['subnet-abc123'], vpcSecurityGroupIds=['sg-abc123']),  # noqa: E501
                {'resourceArn': c['arn']}
            )[1],
}
