# Test inputs for transcribe
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'transcribe.CreateVocabulary': {'VocabularyName': 'tr-test-vocab', 'LanguageCode': 'en-US', 'Phrases': ['hello', 'world']},  # noqa: E501
            'transcribe.CreateVocabularyFilter': {'VocabularyFilterName': 'tr-test-filter', 'LanguageCode': 'en-US', 'Words': ['badword']},  # noqa: E501
            'transcribe.StartTranscriptionJob': {'TranscriptionJobName': 'tr-test-job', 'Media': {'MediaFileUri': 's3://test-bucket/test.mp3'}, 'LanguageCode': 'en-US'},  # noqa: E501
            'transcribe.CreateLanguageModel': {'LanguageCode': 'en-US', 'BaseModelName': 'NarrowBand', 'ModelName': 'tr-test-model', 'InputDataConfig': {'S3Uri': 's3://test-bucket/', 'TuningDataS3Uri': 's3://test-bucket/tuning/', 'DataAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}},  # noqa: E501
            'transcribe.ListVocabularies': {},
            'transcribe.ListVocabularyFilters': {},
            'transcribe.ListTranscriptionJobs': {},
            'transcribe.ListLanguageModels': {},
            'transcribe.GetVocabulary': lambda store: (
                v := store.create_vocabulary(VocabularyName='tr-get-vocab', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyName': v['VocabularyName']}
            )[1],
            'transcribe.GetVocabularyFilter': lambda store: (
                vf := store.create_vocabulary_filter(VocabularyFilterName='tr-get-filter', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyFilterName': vf['VocabularyFilterName']}
            )[1],
            'transcribe.GetTranscriptionJob': lambda store: (
                j := store.start_transcription_job(TranscriptionJobName='tr-get-job', Media={'MediaFileUri': 's3://test-bucket/test.mp3'}, LanguageCode='en-US'),  # noqa: E501
                {'TranscriptionJobName': j['TranscriptionJob']['TranscriptionJobName']}  # noqa: E501
            )[1],
            'transcribe.DescribeLanguageModel': lambda store: (
                m := store.create_language_model(LanguageCode='en-US', BaseModelName='NarrowBand', ModelName='tr-get-model', InputDataConfig={'S3Uri': 's3://test-bucket/', 'TuningDataS3Uri': 's3://test-bucket/tuning/', 'DataAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                {'ModelName': m['ModelName']}
            )[1],
            'transcribe.DeleteVocabulary': lambda store: (
                v := store.create_vocabulary(VocabularyName='tr-del-vocab', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyName': v['VocabularyName']}
            )[1],
            'transcribe.DeleteVocabularyFilter': lambda store: (
                vf := store.create_vocabulary_filter(VocabularyFilterName='tr-del-filter', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyFilterName': vf['VocabularyFilterName']}
            )[1],
            'transcribe.DeleteTranscriptionJob': lambda store: (
                j := store.start_transcription_job(TranscriptionJobName='tr-del-job', Media={'MediaFileUri': 's3://test-bucket/test.mp3'}, LanguageCode='en-US'),  # noqa: E501
                {'TranscriptionJobName': j['TranscriptionJob']['TranscriptionJobName']}  # noqa: E501
            )[1],
            'transcribe.DeleteLanguageModel': lambda store: (
                m := store.create_language_model(LanguageCode='en-US', BaseModelName='NarrowBand', ModelName='tr-del-model', InputDataConfig={'S3Uri': 's3://test-bucket/', 'TuningDataS3Uri': 's3://test-bucket/tuning/', 'DataAccessRoleArn': 'arn:aws:iam::000000000000:role/test'}),  # noqa: E501
                {'ModelName': m['ModelName']}
            )[1],
            'transcribe.UpdateVocabulary': lambda store: (
                v := store.create_vocabulary(VocabularyName='tr-upd-vocab', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyName': v['VocabularyName'], 'LanguageCode': 'en-US', 'Phrases': ['updated']}  # noqa: E501
            )[1],
            'transcribe.UpdateVocabularyFilter': lambda store: (
                vf := store.create_vocabulary_filter(VocabularyFilterName='tr-upd-filter', LanguageCode='en-US'),  # noqa: E501
                {'VocabularyFilterName': vf['VocabularyFilterName'], 'Words': ['updatedword']}  # noqa: E501
            )[1],
}
