# Test inputs for verifiedpermissions
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreatePolicyStore': {'ValidationSettings': {'mode': 'STRICT'}},
            'GetPolicyStore': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId']}
            )[1],
            'ListPolicyStores': {},
            'DeletePolicyStore': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId']}
            )[1],
            'PutSchema': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'], 'Definition': {'cedarJson': '{"test":1}'}}  # noqa: E501
            )[1],
            'GetSchema': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                store.put_schema(PolicyStoreId=ps['policyStoreId'], Definition={'cedarJson': '{"test":1}'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId']}
            )[2],
            'CreatePolicy': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'],
                 'Definition': {'Static': {'Statement': 'permit(principal, action, resource);'}}}  # noqa: E501
            )[1],
            'GetPolicy': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                p := store.create_policy(PolicyStoreId=ps['policyStoreId'],
                    Definition={'Static': {'Statement': 'permit(principal, action, resource);'}}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'], 'PolicyId': p['policyId']}  # noqa: E501
            )[2],
            'ListPolicies': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId']}
            )[1],
            'DeletePolicy': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                p := store.create_policy(PolicyStoreId=ps['policyStoreId'],
                    Definition={'Static': {'Statement': 'permit(principal, action, resource);'}}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'], 'PolicyId': p['policyId']}  # noqa: E501
            )[2],
            'CreateIdentitySource': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'],
                 'Configuration': {'CognitoUserPoolConfiguration': {'UserPoolArn': 'arn:aws:cognito-idp:us-east-1:000000000000:userpool/test'}}}  # noqa: E501
            )[1],
            'GetIdentitySource': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                iss := store.create_identity_source(PolicyStoreId=ps['policyStoreId'],  # noqa: E501
                    Configuration={'CognitoUserPoolConfiguration': {'UserPoolArn': 'arn:aws:cognito-idp:us-east-1:000000000000:userpool/test'}}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'], 'IdentitySourceId': iss['identitySourceId']}  # noqa: E501
            )[2],
            'ListIdentitySources': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId']}
            )[1],
            'DeleteIdentitySource': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                iss := store.create_identity_source(PolicyStoreId=ps['policyStoreId'],  # noqa: E501
                    Configuration={'CognitoUserPoolConfiguration': {'UserPoolArn': 'arn:aws:cognito-idp:us-east-1:000000000000:userpool/test'}}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'], 'IdentitySourceId': iss['identitySourceId']}  # noqa: E501
            )[2],
            'IsAuthorized': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'PolicyStoreId': ps['policyStoreId'],
                 'Principal': {'EntityType': 'User', 'EntityId': 'test-user'},
                 'Action': {'ActionType': 'Action', 'ActionId': 'test-action'},
                 'Resource': {'EntityType': 'Resource', 'EntityId': 'test-resource'}}  # noqa: E501
            )[1],
            'verifiedpermissions.TagResource': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'ResourceArn': ps['arn'], 'Tags': [{'Key': 'test', 'Value': 'val'}]}  # noqa: E501
            )[1],
            'verifiedpermissions.ListTagsForResource': lambda store: (
                ps := store.create_policy_store(ValidationSettings={'mode': 'STRICT'}),  # noqa: E501
                {'ResourceArn': ps['arn']}
            )[1],
}
