# Test inputs for wafv2
# Auto-generated by foreman refactoring (QUALITY-001)
# ruff: noqa  # generated file — runtime-injected Record classes, walrus vars for tuple-positioning  # noqa: E501
# noqa: E501  # long lambda lines from original monolithic file
TEST_INPUTS = {
            'CreateWebACL': {'Name': 'test-webacl', 'Scope': 'REGIONAL',
                             'DefaultAction': {'Block': {}},
                             'VisibilityConfig': {'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}},  # noqa: E501
            'CreateRuleGroup': {'Name': 'test-rulegroup', 'Scope': 'REGIONAL',
                                'VisibilityConfig': {'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'},  # noqa: E501
                                'Capacity': 100},
            'CreateIPSet': {'Name': 'test-ipset', 'Scope': 'REGIONAL',
                            'IPAddressVersion': 'IPV4', 'Addresses': ['10.0.0.0/16']},  # noqa: E501
            'CreateRegexPatternSet': {'Name': 'test-regexset', 'Scope': 'REGIONAL',  # noqa: E501
                                      'RegularExpressionList': [{'RegexString': '^test.*'}]},  # noqa: E501
            'ListWebACLs': {'Scope': 'REGIONAL'},
            'ListRuleGroups': {'Scope': 'REGIONAL'},
            'ListIPSets': {'Scope': 'REGIONAL'},
            'ListRegexPatternSets': {'Scope': 'REGIONAL'},
            'ListLoggingConfigurations': {'Scope': 'REGIONAL'},
            'ListTagsForResource': lambda store: (
                store.create_web_acl(name='s-ltfr-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN']})[1],
            'TagResource': lambda store: (
                store.create_web_acl(name='s-tag-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],
                 'Tags': [{'Key': 'env', 'Value': 'test'}]})[1],
            'UntagResource': lambda store: (
                store.create_web_acl(name='s-untag-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),
                store.tag_resource(
                    store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],
                    [{'Key': 'env', 'Value': 'test'}]),
                {'ResourceARN': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],
                 'TagKeys': ['env']})[2],  # noqa: E501
            'ListResourcesForWebACL': {'WebACLArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/test/abc123'},  # noqa: E501
            'GetWebACL': lambda store: (
                store.create_web_acl(name='s-get-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                {'Name': 's-get-webacl', 'Scope': 'REGIONAL'})[1],
            'GetRuleGroup': lambda store: (
                store.create_rule_group(name='s-get-rulegroup', scope='REGIONAL',  # noqa: E501
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'},  # noqa: E501
                    capacity=100),
                {'Name': 's-get-rulegroup', 'Scope': 'REGIONAL'})[1],
            'GetIPSet': lambda store: (
                store.create_ip_set(name='s-get-ipset', scope='REGIONAL',
                    ip_address_version='IPV4', addresses=['10.0.0.0/16']),
                {'Name': 's-get-ipset', 'Scope': 'REGIONAL'})[1],
            'GetRegexPatternSet': lambda store: (
                store.create_regex_pattern_set(name='s-get-regexset', scope='REGIONAL',  # noqa: E501
                    regular_expression_list=[{'RegexString': '^test.*'}]),
                {'Name': 's-get-regexset', 'Scope': 'REGIONAL'})[1],
            'GetLoggingConfiguration': lambda store: (
                store.put_logging_configuration({'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-get-log/abc', 'LogDestinationConfigs': ['arn:aws:firehose:us-east-1:123456789012:deliverystream/test']}),  # noqa: E501
                {'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-get-log/abc'})[1],  # noqa: E501
            'GetPermissionPolicy': lambda store: (
                store.put_permission_policy('arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-get-pol/abc', '{"Version":"2012-10-17","Statement":[]}'),  # noqa: E501
                {'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-get-pol/abc'})[1],  # noqa: E501
            'GetWebACLForResource': lambda store: (
                store.create_web_acl(name='s-gwfr-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                store.associate_web_acl(
                    web_acl_arn=store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],  # noqa: E501
                    resource_arn='arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-gwfr/abc'),  # noqa: E501
                {'ResourceArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-gwfr/abc'})[2],  # noqa: E501
            'DeleteWebACL': lambda store: (
                store.create_web_acl(name='s-del-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                _get_lock(store.get_web_acl(None, 's-del-webacl', 'REGIONAL'),
                    {'Name': 's-del-webacl', 'Scope': 'REGIONAL'}))[1],
            'DeleteRuleGroup': lambda store: (
                store.create_rule_group(name='s-del-rulegroup', scope='REGIONAL',  # noqa: E501
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'},  # noqa: E501
                    capacity=100),
                _get_lock(store.get_rule_group(None, 's-del-rulegroup', 'REGIONAL'),  # noqa: E501
                    {'Name': 's-del-rulegroup', 'Scope': 'REGIONAL'}))[1],
            'DeleteIPSet': lambda store: (
                store.create_ip_set(name='s-del-ipset', scope='REGIONAL',
                    ip_address_version='IPV4', addresses=['10.0.0.0/16']),
                _get_lock(store.get_ip_set(None, 's-del-ipset', 'REGIONAL'),
                    {'Name': 's-del-ipset', 'Scope': 'REGIONAL'}))[1],
            'DeleteRegexPatternSet': lambda store: (
                store.create_regex_pattern_set(name='s-del-regexset', scope='REGIONAL',  # noqa: E501
                    regular_expression_list=[{'RegexString': '^test.*'}]),
                _get_lock(store.get_regex_pattern_set(None, 's-del-regexset', 'REGIONAL'),  # noqa: E501
                    {'Name': 's-del-regexset', 'Scope': 'REGIONAL'}))[1],
            'DeleteLoggingConfiguration': lambda store: (
                store.put_logging_configuration({'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-del-log/abc', 'LogDestinationConfigs': ['arn:aws:firehose:us-east-1:123456789012:deliverystream/test']}),  # noqa: E501
                {'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-del-log/abc'})[1],  # noqa: E501
            'DeletePermissionPolicy': lambda store: (
                store.put_permission_policy('arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-del-pol/abc', '{"Version":"2012-10-17","Statement":[]}'),  # noqa: E501
                {'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/s-del-pol/abc'})[1],  # noqa: E501
            'UpdateWebACL': lambda store: (
                store.create_web_acl(name='s-upd-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                _get_lock(store.get_web_acl(None, 's-upd-webacl', 'REGIONAL'),
                    {'Name': 's-upd-webacl', 'Scope': 'REGIONAL',
                     'DefaultAction': {'Block': {}},
                     'VisibilityConfig': {'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}}))[1],  # noqa: E501
            'UpdateRuleGroup': lambda store: (
                store.create_rule_group(name='s-upd-rulegroup', scope='REGIONAL',  # noqa: E501
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'},  # noqa: E501
                    capacity=100),
                _get_lock(store.get_rule_group(None, 's-upd-rulegroup', 'REGIONAL'),  # noqa: E501
                    {'Name': 's-upd-rulegroup', 'Scope': 'REGIONAL',
                     'VisibilityConfig': {'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}}))[1],  # noqa: E501
            'UpdateIPSet': lambda store: (
                store.create_ip_set(name='s-upd-ipset', scope='REGIONAL',
                    ip_address_version='IPV4', addresses=['10.0.0.0/16']),
                _get_lock(store.get_ip_set(None, 's-upd-ipset', 'REGIONAL'),
                    {'Name': 's-upd-ipset', 'Scope': 'REGIONAL',
                     'Addresses': ['10.0.0.0/16']}))[1],
            'UpdateRegexPatternSet': lambda store: (
                store.create_regex_pattern_set(name='s-upd-regexset', scope='REGIONAL',  # noqa: E501
                    regular_expression_list=[{'RegexString': '^test.*'}]),
                _get_lock(store.get_regex_pattern_set(None, 's-upd-regexset', 'REGIONAL'),  # noqa: E501
                    {'Name': 's-upd-regexset', 'Scope': 'REGIONAL',
                     'RegularExpressionList': [{'RegexString': '^test.*'}]}))[1],  # noqa: E501
            'AssociateWebACL': lambda store: (
                store.create_web_acl(name='s-assoc-webacl', scope='REGIONAL',
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                {'WebACLArn': store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],  # noqa: E501
                 'ResourceArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-assoc/abc'})[1],  # noqa: E501
            'DisassociateWebACL': lambda store: (
                store.create_web_acl(name='s-disassoc-webacl', scope='REGIONAL',  # noqa: E501
                    default_action={'Block': {}},
                    visibility_config={'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True, 'MetricName': 'test'}),  # noqa: E501
                store.associate_web_acl(
                    web_acl_arn=store.list_web_acls('REGIONAL')['WebACLs'][-1]['ARN'],  # noqa: E501
                    resource_arn='arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-disassoc/abc'),  # noqa: E501
                {'ResourceArn': 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/s-disassoc/abc'})[2],  # noqa: E501
            'PutLoggingConfiguration': {'LoggingConfiguration': {
                'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/test/abc123',  # noqa: E501
                'LogDestinationConfigs': ['arn:aws:firehose:us-east-1:123456789012:deliverystream/test']}},  # noqa: E501
            'PutPermissionPolicy': {'ResourceArn': 'arn:aws:wafv2:us-east-1:123456789012:regional/webacl/test-policy/abc',  # noqa: E501
                                    'Policy': '{"Version":"2012-10-17","Statement":[]}'},  # noqa: E501
}
